#! /bin/sh

version=10.5p1
revision=2
tarball_url="https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${version}.tar.gz"
tarball_blake2b="8e8be4e4aff6b5f16e19f85b994fcc9b7679021cf639fad4323dc15f6bc0041b45370024a5f51065e2a92d965428cf3787323957f2c41f4d27fc1146dc3690cf"
hostdeps="gcc pkg-config"
deps="core-libs zlib openssl"

prepare() {
    autotools_recursive_regen
}

configure() {
        ossh_cv_utmpx_h_has_ut_addr=no \
    autotools_configure \
        --sysconfdir=/etc/ssh \
        --disable-strip \
        --with-privsep-user=nobody \
        --with-privsep-path=${prefix}/share/empty.sshd \
        --with-default-path=${prefix}/local/sbin:${prefix}/local/bin:${prefix}/bin \
        --without-zlib-version-check \
        --with-xauth=/usr/bin/xauth \
        --with-pid-dir=/run
}

build() {
    make -j${parallelism}
}

package() {
    install -v -m700 -d "${dest_dir}${prefix}"/share/empty.sshd
    install -v -d "${dest_dir}"/run

    DESTDIR="${dest_dir}" make install

    post_package_strip
}
