#! /bin/sh

version=10.6p1
revision=1
tarball_url="https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${version}.tar.gz"
tarball_blake2b="9ccb92fde6319f00373f38d27c9fbd6802c7b94bdf881bacecbace1676ef9909213f70be99184c5f9cdda06c9192196acb56503c5965d4d50ef1c701b029d06d"
hostdeps="gcc pkg-config"
deps="core-libs zlib openssl"
conf_files="/etc/ssh/ssh_config /etc/ssh/sshd_config"

prepare() {
    autotools_recursive_regen
}

configure() {
        select_works_with_rlimit=yes \
        ossh_cv_utmpx_h_has_ut_addr=no \
    autotools_configure \
        --sysconfdir=/etc/ssh \
        --disable-strip \
        --disable-lastlog \
        --with-privsep-user=nobody \
        --with-privsep-path=${prefix}/share/empty.sshd \
        --with-default-path=${prefix}/local/sbin:${prefix}/local/bin:${prefix}/bin \
        --without-zlib-version-check \
        --with-xauth=/usr/bin/xauth \
        --with-pid-dir=/run
}

build() {
    make -j${parallelism}
}

package() {
    install -v -m700 -d "${dest_dir}${prefix}"/share/empty.sshd
    install -v -d "${dest_dir}"/run

    DESTDIR="${dest_dir}" make install

    install -v -m755 "${source_dir}"/contrib/ssh-copy-id "${dest_dir}${prefix}"/bin
    install -v -m755 "${source_dir}"/contrib/findssl.sh "${dest_dir}${prefix}"/bin
    install -v -m644 "${source_dir}"/contrib/ssh-copy-id.1 \
        "${dest_dir}${prefix}"/share/man/man1

    post_package_strip
}
