#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=6
source_dir="gloire-install"
deps="bash dialog e2fsprogs dosfstools gptfdisk limine"

package() {
    mkdir -p "${dest_dir}"/usr/bin
    cp -f "${source_dir}"/gloire-install "${dest_dir}"/usr/bin/gloire-install
}
