#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=8
source_dir="gloire-install"
deps="core-libs dialog e2fsprogs dosfstools gptfdisk limine"

package() {
    install -Dm755 "${source_dir}"/gloire-install "${dest_dir}${prefix}"/bin/gloire-install
}
