#! /bin/sh

version=0.8.8
revision=8
tarball_url="https://download.gnome.org/sources/libnotify/0.8/libnotify-${version}.tar.xz"
tarball_blake2b="ad578934a78516ea1142b1ba804be401a6cf6d242b319581dde6da0ec3d20df45342efa94f38580169064872a7d62abd63423b0d8a0d8125e5b8ed4e00a09854"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gdk-pixbuf"

configure() {
    meson_configure \
        -Dgtk_doc=false \
        -Dtests=false \
        -Dintrospection=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
