#! /bin/sh

version=0.8.8
revision=3
git_url="https://gitlab.gnome.org/GNOME/libnotify.git"
commit=8b35b6b74e4af71a20b024330b71ce0daf6c022f
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3"

configure() {
    meson_configure \
        -Dgtk_doc=false \
        -Dtests=false \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
