#! /bin/sh

version=2.44.8
revision=2
tarball_url="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/${version}/gdk-pixbuf-${version}.tar.gz"
tarball_blake2b="3294933dc80653beef24ae393436320b33480e5e6123d2e4fc59cdc4a32fc231fc1055d481f42f5d86b4d7b23b815283859fc5fdb56bed6dab65cdc7d8f17e96"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libjpeg-turbo libpng libx11 libtiff"

configure() {
    meson_configure \
        -Dgio_sniffing=false \
        -Dman=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    gdk-pixbuf-query-loaders --update-cache >/dev/null
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL
}
