#! /bin/sh

version=2.44.8
revision=8
tarball_url="https://download.gnome.org/sources/gdk-pixbuf/2.44/gdk-pixbuf-${version}.tar.xz"
tarball_blake2b="a95bb18e3982036f9d0f840ea774a45980ec7681ffb71ebcb496a4023bdc6da208ee2f6ccc68eab9f107e70530dfcb33ca344329a65e32851aedf08cf9477df1"
imagedeps="libglib2.0-dev-bin libglib2.0-bin python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libjpeg-turbo libpng libtiff shared-mime-info"

configure() {
    meson_configure \
        -Dandroid=disabled \
        -Dglycin=disabled \
        -Dintrospection=disabled \
        -Dtests=false \
        -Dinstalled_tests=false \
        -Dman=true
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    sed -i 's|\.\./\.\./\.\./base_dir/sources/gdk-pixbuf/||g' \
        "${dest_dir}${prefix}"/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-marshal.h

    post_package_strip

    install_hook_add 'gdk-pixbuf-query-loaders --update-cache >/dev/null'
}
