#! /bin/sh

version=2.44.7
revision=1
tarball_url="https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/${version}/gdk-pixbuf-${version}.tar.gz"
tarball_blake2b="3c2eced769901be9c6f7998abb21de375268861e4b4f3507339efb151cf34bc4fe7d00d3191db0a18d11352b51c9705c4cdd17789a982c76493250358dcab8ab"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libjpeg-turbo libpng libx11 libtiff"

configure() {
    meson_configure \
        -Dgio_sniffing=false \
        -Dman=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    gdk-pixbuf-query-loaders --update-cache >/dev/null
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL
}
