#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=18
git_url="https://codeberg.org/Ironclad/util-ironclad.git"
commit=931f89b52322a7724e7d5db3959372b23891977d
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
