#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=24
git_url="https://codeberg.org/Ironclad/util-ironclad.git"
commit=ed0f9865fe616f6f8a9f0fcb2bd3be8d139a3dda
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
