#! /bin/sh

version=1.29.1
revision=7
tarball_url="https://github.com/mate-desktop/marco/releases/download/v${version}/marco-${version}.tar.xz"
tarball_blake2b="e199d76a539fe2bbf49b0edc71ed1e0ad15e2bd9f4ea709591f425fd7621a9239c74152b1c790a0599584c5f308c3e7d01c957d4799cb8b2daadf276fd68af2d"
imagedeps="libgdk-pixbuf2.0-bin libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo gdk-pixbuf glib2 gtk3 libcanberra libgtop libice libsm libx11 libxcomposite libxcursor libxdamage libxext libxfixes libxinerama libxpresent libxrandr libxrender libxres mate-desktop pango"

configure() {
    meson_configure \
        -Dstartup-notification=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    generate_glib_schemas_hook
}
