#! /bin/sh

version=0.116
revision=1
tarball_url="https://dbus.freedesktop.org/releases/dbus-glib/dbus-glib-${version}.tar.gz"
tarball_blake2b="9f1870ae2d11d3452cfa8d2db14ab3bb17c36b2837652c00f74591327d8cbce932be5b865c976e71b03f2257549351be3e870bb3a79b6468c6cf76fb4eb25bc1"
imagedeps="libdbus-glib-1-dev-bin libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs dbus glib2 libexpat"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-gtk-doc \
        --with-dbus-binding-tool=dbus-binding-tool
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
