#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/recipes/gcc/recipe" && echo ${version})"
revision=5
hostdeps="gcc pkg-config"
imagedeps="build-essential"
deps="glibc"

package() {
    cd "${build_dir}"/host-builds/gcc/build

    rm -rf tmp_libgcc_dir
    mkdir tmp_libgcc_dir

    DESTDIR="$(realpath tmp_libgcc_dir)" make install-target-libgcc

    mkdir -p "${dest_dir}${prefix}"

    cp -r tmp_libgcc_dir/usr/local/lib "${dest_dir}${prefix}"/
    cp -r tmp_libgcc_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
