#! /bin/sh

version=0.23.2
revision=1
tarball_url="https://github.com/rockdaboot/libpsl/releases/download/${version}/libpsl-${version}.tar.gz"
tarball_blake2b="f58c82fcfc52031a23bce74369b00a89111a78a480073d910c088dfd8e2d6c9fa5f415e53592bb169d1287d853f0860a1761bd34b8505de611dcc3ed5dc13e00"
hostdeps="gcc pkg-config"
deps="core-libs libidn2 libunistring"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
