#! /bin/sh

version=0.23.0
revision=1
tarball_url="https://github.com/rockdaboot/libpsl/releases/download/${version}/libpsl-${version}.tar.gz"
tarball_blake2b="d0f2c39ba05b76b36f2a79a507bf3a09fc04c81b11bdad0d695ffff43c89dc54cb489be0a535bdbf77f65322710174387716bb8dfa01bca476cb519cfe73911b"
hostdeps="gcc pkg-config"
deps="core-libs libidn2 libunistring"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
