#! /bin/sh

version=0.23.1
revision=1
tarball_url="https://github.com/rockdaboot/libpsl/releases/download/${version}/libpsl-${version}.tar.gz"
tarball_blake2b="1f9a5da8522237444fd1f71850d8a866af6ff501843e3160ef5baa1d962d04ddf8953556feceb55887949ae9f5fba83aef6e25217e04061e445a7b4c3f4f45c7"
hostdeps="gcc pkg-config"
deps="core-libs libidn2 libunistring"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
