#! /bin/sh

version=0.84.0
revision=1
tarball_url="https://gitlab.gnome.org/api/v4/projects/1893/packages/generic/vte/${version}/vte-${version}.tar.xz"
tarball_blake2b="c3d95206436fa6f1949cc7130234afa053b9f8c950dd11a6a143de1251aa41c363c7c89ab087a3b7c821730029c826b01cec727f1004574c9e10980b60f2efa4"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs fast_float simdutf fmt gnutls gtk3 cairo fribidi glib2 icu pango pcre2 lz4 libxml2"

configure() {
    meson_configure \
        -Da11y=true \
        -Ddebug=false \
        -Ddocs=false \
        -Dgir=false \
        -Dfribidi=true \
        -Dglade=true \
        -Dgnutls=true \
        -Dgtk3=true \
        -Dgtk4=false \
        -Dicu=true \
        -D_systemd=false \
        -Dvapi=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
