#! /bin/sh

version=3.53.4
revision=2
tarball_url="https://sqlite.org/2026/sqlite-autoconf-3530300.tar.gz"
tarball_blake2b="61ee1a88258fdfed02c51c9b0302a0eb27e58b90b5285be6e89753293f1662caa0a7d6de586bdfd72ddeffe166a0704702bed99040d2998674b22289718f3935"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs readline zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    "${source_dir}/configure" \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --soname=legacy \
        --disable-static \
        --enable-shared \
        --enable-fts4 \
        --enable-fts5 \
        --enable-readline \
        --with-readline-header=${sysroot}${prefix}/include/readline/readline.h \
        CFLAGS="$TARGET_CFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_SECURE_DELETE=1" \
        LDFLAGS="$TARGET_LDFLAGS"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
