#! /bin/sh

name=gobject-introspection
version=1.82.0
revision=1
tarball_url="https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-${version}.tar.xz"
tarball_blake2b="8336ae26d48a71a203655d9d268076f603055ceabb55dbfa676f2c67b4096b83afc106d485dc45d02b3a8be806f9ef50d54806a82e61f2a252ae59543c61e934"
# imagedeps="meson ninja-build libglib2.0-dev"
# hostdeps="gcc pkg-config"
# deps="core-libs"

# prepare() {
#         LIBTOOLIZE=true \
#     autotools_recursive_regen
# }
