#! /bin/sh

name=gtk-doc
version=1.34.0
revision=1
tarball_url="https://download.gnome.org/sources/gtk-doc/1.34/gtk-doc-${version}.tar.xz"
tarball_blake2b="cb8550debed9f32b967de9d4ebdde8dbe83551eb8527221d2d788355431f34e62a4beedda3e7f5722516ae8e23794a56b97a4f761ede0f7f2c0ef288624b5f7a"
# imagedeps="meson ninja-build libglib2.0-dev"
# hostdeps="gcc pkg-config"
# deps="core-libs"

# prepare() {
#         LIBTOOLIZE=true \
#     autotools_recursive_regen
# }
