#! /bin/sh

repology_id=pkgconf
version=3.0.7
revision=1
tarball_url="https://distfiles.ariadne.space/pkgconf/pkgconf-${version}.tar.xz"
tarball_blake2b="650ba75df56c8c0428ef361428c888b2672c201ae4443e12d126f840ef891430a6390615f48e09eaa534c080bc4fdbc09d25ec72c9999890e6a7aee8f0829ae3"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -s pkgconf "${dest_dir}${prefix}"/bin/pkg-config
    ln -s pkgconf.1 "${dest_dir}${prefix}"/share/man/man1/pkg-config.1

    post_package_strip
}
