#! /bin/sh

version=0.20
revision=2
git_url="https://gitlab.freedesktop.org/xdg/xdg-user-dirs.git"
commit=cd05b6d29da1abdb3cd253ef496ae7fd1593e4bb
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
