#! /bin/sh

version=26.08.0
revision=10
tarball_url="https://poppler.freedesktop.org/poppler-${version}.tar.xz"
tarball_blake2b="406771a67f2760b1195f89ece86b1463f5e712b3a5802d26e7a1c652e46f3a06403cd74c0460c1b07f1d44b5b154d59bcd989c054324de7d90e65118e92cefcd"
hostdeps="gcc pkg-config"
deps="core-libs fontconfig freetype2 glib2 cairo curl lcms2 libjpeg-turbo libpng libtiff nspr nss openjpeg2 zlib"

configure() {
    cmake_configure \
        -DBUILD_GTK_TESTS=OFF \
        -DBUILD_QT5_TESTS=OFF \
        -DBUILD_QT6_TESTS=OFF \
        -DBUILD_CPP_TESTS=OFF \
        -DRUN_GPERF_IF_PRESENT=OFF \
        -DENABLE_BOOST=OFF \
        -DENABLE_GPGME=OFF \
        -DENABLE_QT5=OFF \
        -DENABLE_QT6=OFF \
        -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
