#! /bin/sh

version=26.09.0
revision=2
tarball_url="https://poppler.freedesktop.org/poppler-${version}.tar.xz"
tarball_blake2b="91d795dda70c1722b65e80cef7d69f2d891148be0b02fbe43c3f404ba2f688a577058cfb2a1eeb8993ee6d0e1b2fbae1d9f8104e772e754fcfb6311b07baf9b7"
hostdeps="gcc pkg-config"
deps="core-libs fontconfig freetype2 glib2 cairo curl lcms2 libjpeg-turbo libpng libtiff nspr nss openjpeg2 zlib harfbuzz"

configure() {
    cmake_configure \
        -DBUILD_GTK_TESTS=OFF \
        -DBUILD_QT5_TESTS=OFF \
        -DBUILD_QT6_TESTS=OFF \
        -DBUILD_CPP_TESTS=OFF \
        -DRUN_GPERF_IF_PRESENT=OFF \
        -DENABLE_BOOST=OFF \
        -DENABLE_GPGME=OFF \
        -DENABLE_QT5=OFF \
        -DENABLE_QT6=OFF \
        -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
