#! /bin/sh

version=26.08.0
revision=5
git_url="https://gitlab.freedesktop.org/poppler/poppler.git"
commit=d663f8fe0237073fadf43e4e19acc46b3ba3e80a
hostdeps="gcc pkg-config"
deps="core-libs fontconfig glib2 cairo curl libjpeg-turbo libpng libtiff openjpeg2"

configure() {
    cmake_configure \
        -DBUILD_GTK_TESTS=OFF \
        -DBUILD_QT5_TESTS=OFF \
        -DBUILD_QT6_TESTS=OFF \
        -DBUILD_CPP_TESTS=OFF \
        -DRUN_GPERF_IF_PRESENT=OFF \
        -DENABLE_BOOST=OFF \
        -DENABLE_ZLIB_UNCOMPRESS=OFF \
        -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
        -DWITH_Cairo=ON \
        -DENABLE_LIBCURL=ON \
        -DENABLE_CPP=ON \
        -DENABLE_GPGME=OFF \
        -DENABLE_LIBOPENJPEG=none \
        -DENABLE_LCMS=OFF \
        -DENABLE_NSS3=OFF \
        -DWITH_PNG=ON \
        -DENABLE_QT5=OFF \
        -DENABLE_QT6=OFF \
        -DENABLE_LIBTIFF=ON \
        -DENABLE_UTILS=ON \
        -DWITH_GObjectIntrospection=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
