#! /bin/sh

version=4.2.2
revision=4
tarball_url="https://ftp.gnu.org/gnu/mpfr/mpfr-${version}.tar.xz"
tarball_blake2b="6bbf5658e70fbb673a3b65246a6bac708d1571aa6943c6742efd92f468ac71e6f0fe351b757f7133440ea312d9a5fc3549acd89d54f4d975c58bdc204d7b21ec"
hostdeps="gcc pkg-config"
deps="core-libs gmp texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-thread-safe
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
}
