#! /bin/sh

version=1.4
revision=4
tarball_url="https://www.delorie.com/store/ace/ace-${version}.tar.gz"
tarball_blake2b="62d32bcada9a945d0a409757ca24c8c5c032e905528d56a51b95f82844c6c8057d39763016fa05015877f23313d842effeaaa362507bb049816d7cf6bdf01a1a"
imagedeps="build-essential libpng-dev"
hostdeps="gcc pkg-config"
builddeps="libxpm"
deps="core-libs libx11 libpng"

prepare() {
    cp -v "${recipe_dir}"/jack.png    ./lib/png/
    cp -v "${recipe_dir}"/king.png    ./lib/png/
    cp -v "${recipe_dir}"/penguin.png ./lib/png/
    cp -v "${recipe_dir}"/queen.png   ./lib/png/
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        CFLAGS="${TARGET_CFLAGS} -std=gnu17"
}

build() {
    make -j${parallelism} \
        BUILD_CFLAGS="${HOST_CFLAGS}" \
        BUILD_CPPFLAGS="" \
        BUILD_LDFLAGS="${HOST_LDFLAGS}"
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
