#! /bin/sh

version=0.12
revision=3
tarball_url="https://downloads.xiph.org/releases/opus/opusfile-${version}.tar.gz"
tarball_blake2b="d54d9b8ed011c018dc6de77afab524d2e47ba6cca69b911efacf361b41f3b59a31424cb15a778db14166815ba5e2352f33f8aa7987c30e5e14339c652558d18d"
hostdeps="gcc pkg-config"
deps="core-libs libogg opus openssl"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
