#! /bin/sh

name=at-spi2-core
version=2.58.2
revision=1
git_url="https://gitlab.gnome.org/GNOME/at-spi2-core.git"
commit=aeed81f032c4cf625193bf51e3c8c8e9547eccda
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs bash dbus glib2 gsettings-desktop-schemas libx11 libxi libxkbcommon libxml2 libxtst"

configure() {
    meson_configure \
        -Dsystemd_user_dir=/remove_later \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -rv "${dest_dir}"/remove_later

    post_package_strip
}
