#! /bin/sh

name=at-spi2-core
version=2.56.4
revision=1
git_url="https://gitlab.gnome.org/GNOME/at-spi2-core.git"
commit=7f111fc91751b49bd7fec885035024b401253adb
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs bash dbus glib2 gsettings-desktop-schemas libx11 libxi libxkbcommon libxml2 libxtst"

configure() {
    meson_configure \
        -Dsystemd_user_dir=/tmp \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
