#! /bin/sh

name=atril
version=1.28.1
revision=1
tarball_url="https://github.com/mate-desktop/atril/releases/download/v${version}/atril-${version}.tar.xz"
tarball_blake2b="7c90f1bd8c4e30d1208a5514e8c9153b919443ca0fcbbb7de4db3e74c14330f24fad41f57f1781b243707e724bb9ce4952ca9267755d4482bad7e605421e501f"
imagedeps="libglib2.0-dev-bin itstool libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core poppler glib2 libxml2 mate-desktop zlib gdk-pixbuf gtk3 libice libsm libx11 cairo pango caja libtiff libarchive"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-comics \
        --enable-pdf \
        --enable-pixbuf \
        --enable-previewer \
        --enable-thumbnailer \
        --without-keyring \
        --disable-caja \
        --enable-dbus \
        --disable-debug \
        --disable-djvu \
        --disable-dvi \
        --disable-epub \
        --disable-introspection \
        --enable-nls \
        --disable-ps \
        --disable-synctex \
        --disable-t1lib \
        --disable-tests \
        --enable-tiff \
        --disable-xps
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
