#! /bin/sh

name=atril
version=1.28.2
revision=3
git_url="https://github.com/mate-desktop/atril.git"
commit=6e116cd028790a0123db5b9e6be7ae9bc03c33c3
imagedeps="libglib2.0-dev-bin itstool libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core poppler glib2 libxml2 mate-desktop zlib gdk-pixbuf gtk3 libice libsm libx11 cairo pango caja libtiff libarchive"

early_prepare() {
    # Fix revision of mate-submodules
    sed -i 's/^revision=.*/revision = 4074560e3642a53ace07b31baaf3f04c060dcd0b/g' subprojects/mate-submodules.wrap

    meson subprojects download
}

configure() {
    meson_configure \
        -Dcomics=true \
        -Ddjvu=false \
        -Ddvi=false \
        -Dt1lib=false \
        -Depub=false \
        -Dpdf=true \
        -Dpixbuf=true \
        -Dps=false \
        -Dtiff=true \
        -Dxps=false \
        -Dkeyring=false \
        -Dpreviewer=true \
        -Dthumbnailer=true \
        -Dintrospection=false \
        -Denable_dbus=true \
        -Denable_debug=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
