#! /bin/sh

name=base
version=0.0
revision=1
deps="base-files bash binutils bzip2 coreutils diffutils epoch findutils
gawk gcc gcon gmp grep gzip ironclad less make mpc mpfr nano ncurses pcre2
readline sed tar tzdata util-ironclad xz zlib zstd metalog cronie"
