#! /bin/sh

name=bash
_version=5.3
_patch=3
version=${_version}.${_patch}
revision=3
tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-${_version}.tar.gz"
tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs ncurses readline"

_get_patch() {
    TMP_PATCH=$(mktemp)
    curl -Lo "${TMP_PATCH}" https://ftpmirror.gnu.org/gnu/bash/bash-${_version}-patches/bash$(echo "${_version}" | sed 's/\.//g')-$1
    if ! b2sum "${TMP_PATCH}" | grep -q $2; then
        die "b2sum checksum fail for bash patch $1
        expected $2
        got      $(b2sum "${TMP_PATCH}")"
    fi
    patch -p0 <"${TMP_PATCH}"
}

early_prepare() {
    _get_patch 001 ca275ade6a7132d316a4d1ffd401c9bfc6de691c58531385d85087c4d50723aeacb5b4bc7abef0165b4fb3cbed146a0fefd9dae4c99c1547f61618798a772d29
    _get_patch 002 fec52c475b8126774290eab7a514f8145ae51edab150d413c09f5540719c9578fe1cb99987b6190a9cd82bd947e059c32e740a03d26e9d472af51356cafd8a32
    _get_patch 003 6bb6f6679726d65f95c11b4ac1fb0729eaebfeef02de06e9fda4e3ac2bb3d328cc6f7fd6e29976a0907390ed6709cd5a0a6046682acbed73eb0470143bf144e1
}

prepare() {
    autotools_recursive_regen
}

configure() {
        bash_cv_func_sigsetjmp=missing \
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS \
            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
            -DNON_INTERACTIVE_LOGIN_SHELLS \
        " \
        --with-curses \
        --enable-readline \
        --without-bash-malloc \
        --with-installed-readline="${sysroot}${prefix}/lib"
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
    ln -s bash "${dest_dir}${prefix}"/bin/sh
    ln -s bash "${dest_dir}${prefix}"/bin/rbash

    mkdir -p "${dest_dir}"/etc
    cp -v "${base_dir}"/build-support/bash/bash.bashrc "${dest_dir}"/etc/
    cp -v "${base_dir}"/build-support/bash/bash.bash_logout "${dest_dir}"/etc/

    post_package_strip
}
