#! /bin/sh

name=binutils
version=2.46.0
revision=2
tarball_url="https://ftp.gnu.org/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="9f4fd8897d237eb5003bdf439537dfc5f8c681e9ff939fb06bb8235ed298031ea4cc91611edb640ffc432199d5791289d003fe0d07acce80327dc40595a5eb9e"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --target=${OS_TRIPLET} \
        --with-build-sysroot=${sysroot_dir} \
        --enable-separate-code \
        --enable-cet \
        --enable-colored-disassembly \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-ld=default \
        --enable-new-dtags \
        --enable-plugins \
        --enable-relro \
        --enable-threads \
        --disable-werror \
        --with-pic \
        --with-system-zlib
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove unnecessary directory
    rm -rf "${dest_dir}${prefix}"/${OS_TRIPLET}

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
