#! /bin/sh

name=bzip3
version=1.5.3
revision=1
tarball_url="https://github.com/iczelia/bzip3/releases/download/${version}/bzip3-${version}.tar.xz"
tarball_blake2b="44033765eeecd159265d234c5bf9faf03df18722fbc241322cabf2adbdd55aad9e835f7ef55e93694da25a3a306850f2b97c3e902ade3dabed5c6fd07be0f9eb"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
