#! /bin/sh

name=ca-certificates
version_url=1.16.1
# While unusual, version will be the date of the last bump + the NSS version used.
# If needed, we can always fetch a set NSS commit past the last release to fix critical bugs.
version=20250828.3.115.1
revision=1
tarball_url="https://github.com/lfs-book/make-ca/archive/v${version_url}/make-ca-${version_url}.tar.gz"
tarball_blake2b="f054fe6e96b74bfc02038e9dc4dd09628a22b75711f692a346c4952a6fa07456b63cff7863d3c11feddeb1ef37b1b786934e2713008b808570da8443e978ece3"
imagedeps="p11-kit"
hostdeps="gcc pkg-config"
deps="core-libs nss openssl p11-kit"

build() {
    cp -rp "${source_dir}"/. ./
}

package() {
    DESTDIR="${dest_dir}" make install

    install -v -dm755 "${dest_dir}/etc/ssl/local"

    # Move /usr/sbin to /usr/bin
    mv "${dest_dir}${prefix}/sbin" "${dest_dir}${prefix}/bin"

    # Create the initial CA certificate store
    export P11_KIT_TRUST_PATH="${dest_dir}/etc/pki/anchors"
    ./make-ca -f -C "${sysroot_dir}${prefix}/share/nss/certdata.txt" -D "${dest_dir}"

    # Fix permissions
    chmod -v 0755 "${dest_dir}/etc/ssl/certs"

    # Remove unneeded systemd timers
    rm -rvf ${dest_dir}${prefix}/lib

    post_package_strip
}
