#! /bin/sh

name=ca-certificates
skip_pkg_check=yes
version_url=1.16.1
version="$(. "${base_dir}/recipes/nss" && echo "${version}")"
revision=2
tarball_url="https://github.com/lfs-book/make-ca/archive/v${version_url}/make-ca-${version_url}.tar.gz"
tarball_blake2b="f054fe6e96b74bfc02038e9dc4dd09628a22b75711f692a346c4952a6fa07456b63cff7863d3c11feddeb1ef37b1b786934e2713008b808570da8443e978ece3"
imagedeps="p11-kit"
hostdeps="gcc pkg-config"
deps="core-libs nss openssl p11-kit"

build() {
    cp -rp "${source_dir}"/. ./
}

package() {
    chmod +x ./make-ca
    ./make-ca -f -C "${sysroot_dir}${prefix}/share/nss/certdata.txt" -D "${dest_dir}"

    # Remove unneeded systemd timers
    rm -rvf ${dest_dir}${prefix}/lib

    post_package_strip
}
