#! /bin/sh

name=cal
version=4.1
revision=1
tarball_url="https://deb.debian.org/debian/pool/main/c/cal/cal_${version}.orig.tar.xz"
tarball_blake2b="a0e5171898331a70a4e22a828b6c184718249c1f339c8d5f571a0025b5568e3d3a267c594e1f2616461b5300ff776bc29d67df92fba9e96702782e567839711d"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp ${source_dir}/. ./

    make -C src -f makefile.unx CC=${OS_TRIPLET}-gcc CFLAGS="$TARGET_CFLAGS -DNO_EXECINFO $TARGET_LDFLAGS"
}

package() {
    mkdir -p "${dest_dir}/usr/share/man/man1"
    mkdir -p "${dest_dir}/usr/bin"
    make -C src -f makefile.unx BINDIR="${dest_dir}/usr/bin" MANDIR="${dest_dir}/usr/share/man" CC=${OS_TRIPLET}-gcc CFLAGS="-DNO_EXECINFO ${CFLAGS}" install
    post_package_strip
}
