#! /bin/sh

name=curl
version=8.16.0
revision=2
git_url="https://github.com/curl/curl.git"
commit=11b991232fbcaa88e2b1faecac224416b0001e35
hostdeps="gcc pkg-config"
deps="core-libs openssl zlib zstd libpsl libidn2 brotli nghttp2"

configure() {
    cmake_configure \
        -DENABLE_THREADED_RESOLVER=ON \
        -DCURL_USE_OPENSSL=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
