#! /bin/sh

name=curl
version=8.14.1
revision=1
tarball_url="https://curl.se/download/curl-${version}.tar.xz"
tarball_blake2b="4ce2277d143084823855b714e86047a94d4c52a686b8d16d9ab76c31168f1a74d63dfa7608cff36706a8a0b9bf9cc611a9b99860b176a227bca580cd95e9cff2"
hostdeps="gcc pkg-config"
deps="core-libs openssl zlib zstd libpsl libidn2"

configure() {
    cmake_configure \
        -DENABLE_THREADED_RESOLVER=ON \
        -DCURL_USE_OPENSSL=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
