#! /bin/sh

name=curl
version=8.18.0
fixed_version=$(echo ${version} | sed 's/\./_/g')
revision=1
tarball_url="https://github.com/curl/curl/releases/download/curl-${fixed_version}/curl-${version}.tar.xz"
tarball_blake2b="16e1539616c1800dfa08a5bd3e38ff75d2906a4a574b1541509c69200aebe680b0a5efdf1b1e0c89f3cccb6001bfe1c1459b9fd815053c964e1a1434be1e2e0e"
hostdeps="gcc pkg-config"
deps="core-libs ca-certificates openssl zlib zstd libpsl libidn2 brotli nghttp2"

configure() {
    cmake_configure \
        -DENABLE_THREADED_RESOLVER=ON \
        -DCURL_USE_OPENSSL=ON \
        -DCURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
