#! /bin/sh

name=cvs
version=1.12.13
revision=1
tarball_url="http://deb.debian.org/debian/pool/main/c/cvs/cvs_${version}+real.orig.tar.gz"
tarball_blake2b="04be16ac95e6e701bc8629b3aafcc28b6d42162419f192d79534dbbc5b62151c244500eaddfe554cc4165267d69b201cbaf485e7803af39c0aafc86343bfce9d"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    EDITOR=nano cvs_cv_func_printf_ptr=1 autotools_configure \
        CFLAGS="$TARGET_CFLAGS -std=gnu17" \
        --with-editor
}

build() {
    make AR=${OS_TRIPLET}-ar -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
