#! /bin/sh

name=dbus-glib
version=0.112
revision=1
tarball_url="https://dbus.freedesktop.org/releases/dbus-glib/dbus-glib-${version}.tar.gz"
tarball_blake2b="24e1c222f0116b32c109682816f6c35771647f4c63cab93a6621bd68b71ea4dca62fbf9e6bb360386b8658146dbf34b0d7dc471db7525585412d120340c4c969"
source_hostdeps="automake autoconf libtool pkg-config"
source_imagedeps="gtk-doc-tools"
imagedeps="libdbus-glib-1-dev-bin libglib2.0-dev-bin"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs dbus glib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-gtk-doc \
        --with-dbus-binding-tool=dbus-binding-tool
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
