#! /bin/sh

name=dconf
version=0.49.0
revision=2
git_url="https://gitlab.gnome.org/GNOME/dconf.git"
commit=a6b86bd66d3b42d8cfeacc2cc71a4fc78abadb71
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs dbus glib2 bash-completion"

early_prepare() {
    git submodule update --init --recursive
}

configure() {
    meson_configure \
        -Dvapi=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    gio-querymodules /usr/lib/gio/modules/ >/dev/null
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL
}
