#! /bin/sh

name=dconf
version=0.40.0
revision=2
tarball_url="https://download.gnome.org/sources/dconf/0.40/dconf-${version}.tar.xz"
tarball_blake2b="bdbc48b71e46fdc4353358cd08fb96933d07af587300a6f91bc45826aeafb3f34f482fe6e09041dd839e507b863a8e33d09bad88a91c1c868983f8afb52c5c85"
imagedeps="meson ninja-build libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs dbus glib2 bash-completion"

configure() {
    meson_configure \
        -Dvapi=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
