#! /bin/sh

name=dosfstools
version=4.2
revision=1
tarball_url="https://github.com/dosfstools/dosfstools/releases/download/v${version}/dosfstools-${version}.tar.gz"
tarball_blake2b="c55c7592aa80f1fe39e838c83e147ad7141ddd0f72c9c000ba7708ecb7287c3a92b4b52f72c8d0d1171b0f9609dfb7861bbbe475c5cbd7011151c93c2b1d3d0d"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
  autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
