#! /bin/sh

name=dunst
version=1.13.1
revision=1
git_url="https://github.com/dunst-project/dunst.git"
commit=da6174d6079ee7bf29f52898ee215d656a69f434
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libxext libxmu libxrender libxi libxcb dbus pango gdk-pixbuf libxscrnsaver libxinerama libnotify"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
