#! /bin/sh

name=e2fsprogs
version=1.47.4
revision=1
tarball_url="https://github.com/tytso/e2fsprogs/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="065bae5f04f6ac66edc92c138e3cfea11a511aea02e8f95c2e739546fba539a65404dec5cc58282a5a6de44f7b5418f48107042e382a13dfb134f01cdd5b18e8"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-elf-shlibs
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove static libraries.
    rm -v "${dest_dir}${prefix}/lib"/*.a

    post_package_strip
}
