#! /bin/sh

name=e2fsprogs
version=1.47.0
revision=1
tarball_url="https://github.com/tytso/e2fsprogs/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="5b87b873c617f328162d20f109e47e1f452bc11172e5319c087190f1782e3ba846389b14b8cd9df664a9795da8d6783b9818e4475d922bd0a26d493710cbcb83"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
  LIBS="-lintl" \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
