#! /bin/sh

name=epoch
version=1.3.0
revision=5
tarball_url="https://github.com/Subsentient/epoch/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="f38b756344289f585848d408e361d090e7e2cadd38bea1481acf534908727d4163a9b556940a30a194dc52c50cb9bb723ecd6a0c8e18256f6c115eb66c9b052b"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp ${source_dir}/. ./

    make CC=${OS_TRIPLET}-gcc CFLAGS="$TARGET_CFLAGS -DNO_EXECINFO" LDFLAGS="$TARGET_LDFLAGS"
}

package() {
    mkdir -p "${dest_dir}${prefix}"/bin
    mkdir -p "${dest_dir}"/etc/epoch
    cp -r built/sbin/* "${dest_dir}${prefix}"/bin/
    cp -r built/bin/*  "${dest_dir}${prefix}"/bin/
    cp -v "${base_dir}"/build-support/epoch/epoch.conf "${dest_dir}"/etc/epoch/
    post_package_strip
}
