#! /bin/sh

name=exempi
version=2.6.6
revision=1
tarball_url="https://libopenraw.freedesktop.org/download/exempi-${version}.tar.xz"
tarball_blake2b="96d400e94deb46ac45c7a425268a859ef7e8d12357cbbb0143c0a0dfd367d31fbf763e50e62f7bad67ab7771562f8b8b6208b98adbb1f16b9e0457fc79f66a37"
hostdeps="gcc pkg-config"
deps="core-libs libexpat zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-unittest=no
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
