#! /bin/sh

name=fastfetch
version=2.56.0
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=e50421a6ce8736be5e2fb80a23b2af60fd2ead8a
hostdeps="gcc pkg-config"
deps="core-libs zlib libxcb libxrandr glib2 dconf sqlite"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
