#! /bin/sh

name=fast_float
repology_id="fast-float"
version=8.2.0
revision=1
git_url="https://github.com/fastfloat/fast_float.git"
commit=dd77fb5e4c3339725775fd61e51034a5e5a55cbb
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
