#! /bin/sh

name=fastfetch
version=2.53.0
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=9ab5c33008c4bd116135867dacdc29caad7c6efd
hostdeps="gcc pkg-config"
deps="core-libs zlib libxcb libxrandr glib2 dconf sqlite"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
