#! /bin/sh

name=fast_float
repology_id="fast-float"
version=8.1.0
revision=1
git_url="https://github.com/fastfloat/fast_float.git"
commit=88b1e5321c6918cbe091afd76728296290668403
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
