#! /bin/sh

name=fastfetch
version=2.55.0
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=7a2bf4e0ac1fc44d444b712a1565ee3dd5856986
hostdeps="gcc pkg-config"
deps="core-libs zlib libxcb libxrandr glib2 dconf sqlite"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
