#! /bin/sh

name=feh
version=3.11.1
revision=1
tarball_url="https://feh.finalrewind.org/feh-${version}.tar.bz2"
tarball_blake2b="ced910ad6297e1ad227e6122c95ac03d45ee93d390cf761e3ae885ba34acde087b4df2bff05fee53f5a56f05f526dd00bba9b025d1baa5c04a750af27c01877a"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libpng imlib2"

build() {
    cp -rp "${source_dir}"/. ./
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        PREFIX="${prefix}" \
        curl=0 \
        xinerama=0 \
        -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install

    post_package_strip
}
