#! /bin/sh

name=feh
version=3.11.3
revision=1
tarball_url="https://feh.finalrewind.org/feh-${version}.tar.bz2"
tarball_blake2b="eba549f799f1f7d0822c513fb80be495d54976ef2511a8830242acb2564c2a9f170f8f04699c14cb838c43721ff33b9d286c2fdf811e60ce49a6029fb62b9c1e"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libpng imlib2"

build() {
    cp -rp "${source_dir}"/. ./
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        PREFIX="${prefix}" \
        curl=0 \
        xinerama=0 \
        -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install

    post_package_strip
}
