#! /bin/sh

name=fontconfig
version=2.17.1
revision=1
git_url="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
commit=6d0a98982ec351c165c9224c8b7dbdfca3010e47
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libexpat libxml2"

configure() {
    meson_configure \
        -Dxml-backend=libxml2
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
    post_package_strip
}
