#! /bin/sh

name=fox
version=1.6.57
revision=1
tarball_url="https://github.com/franko/fox/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="9bc6f30396e3626e20a85cae83404b040d98da459e24454274d2acef73bc29c2deaf34879cf9c1b5f4eb679e4abb16dbcec30984991be841f015c7702a1a79d9"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libx11 libxft libxext freetype2 glu"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

        configure_script_path=./configure \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
