#! /bin/sh

name=freetype2
repology_id=freetype
version=2.14.1
revision=1
git_url="https://gitlab.freedesktop.org/freetype/freetype.git"
commit=526ec5c47b9ebccc4754c85ac0c0cdf7c85a5e9b
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libpng brotli zlib"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
