#! /bin/sh

name=freetype2
repology_id=freetype
version=2.14.3
revision=1
git_url="https://gitlab.freedesktop.org/freetype/freetype.git"
commit=0a0221a1347e2f1e07c395263540026e9a0aa7c7
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libpng brotli zlib"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
