#! /bin/sh

name=freetype2
repology_id=freetype
version=2.14.2
revision=1
git_url="https://gitlab.freedesktop.org/freetype/freetype.git"
commit=f4205da14867c5387cd6a329b90ee10a6df6eeff
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libpng brotli zlib"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
