#! /bin/sh

name=freestnd-c-hdrs
skip_pkg_check=yes
version=4039f438fb1dc1064d8e98f70e1cf122f91b763b
revision=1
git_url="https://codeberg.org/osdev/freestnd-c-hdrs.git"
commit=${version}

build() {
    cp -rpf "${source_dir}"/. ./
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install
}
