#! /bin/sh

name=frigg
skip_pkg_check=yes
version=0.0git
revision=3
git_url="https://github.com/managarm/frigg.git"
commit=5304639c1c9fd3713fd759453b0415b968dcaa06
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
