#! /bin/sh

name=frigg
skip_pkg_check=yes
version=0.0git
revision=1
git_url="https://github.com/managarm/frigg.git"
commit=41b8f556db2646c4417d227b5174a66f03d86a43
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
