#! /bin/sh

name=gcon
skip_pkg_check=yes
version=0.0git
revision=7
git_url="https://codeberg.org/Ironclad/gcon.git"
commit=89af0979495ee53497ff570512de5cee610b1300
source_allow_network="yes"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    meson subprojects download
}

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
