#! /bin/sh

name=gcon
skip_pkg_check=yes
version=0.0git
revision=14
git_url="https://codeberg.org/Ironclad/gcon.git"
commit=4444ea9d94a4466cdcfefab804f2004bacabdaf0
hostdeps="gcc pkg-config"
deps="core-libs"

early_prepare() {
    meson subprojects download
}

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
