#! /bin/sh

name=gcon
skip_pkg_check=yes
version=0.0git
revision=2
git_url="https://codeberg.org/Ironclad/gcon"
commit=82e546616875125ac0cb78369e9c89eb0f823ff1
source_imagedeps="git"
source_hostdeps="automake autoconf pkg-config"
source_allow_network="yes"
hostdeps="gcc autoconf automake pkg-config"
deps="core-libs"

prepare() {
    ./bootstrap
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
