#! /bin/sh

name=gdb
version=16.3
revision=2
tarball_url="https://ftpmirror.gnu.org/gnu/gdb/gdb-${version}.tar.xz"
tarball_blake2b="a75c8655b39580a7f6e0d85ef663f60932fbed9a92ade6d58a2e99bc8b1416b36f8410c66c23bdada83e221a65c1cdfdeb7bb7ae9a930c443557864a1769dbee"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs zlib zstd gmp mpfr readline"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --target=${OS_TRIPLET} \
        --with-build-sysroot=${sysroot_dir} \
        --disable-nls \
        --enable-tui \
        --enable-interwork \
        --disable-werror \
        --with-pic \
        --disable-binutils \
        --with-system-zlib \
        --with-system-readline
}

build() {
    make -j${parallelism}
}

package() {
    make -C gdb DESTDIR="${dest_dir}" install
    post_package_strip
}
