#! /bin/sh

name=gdb
version=16.3
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/gdb/gdb-${version}.tar.xz"
tarball_blake2b="a75c8655b39580a7f6e0d85ef663f60932fbed9a92ade6d58a2e99bc8b1416b36f8410c66c23bdada83e221a65c1cdfdeb7bb7ae9a930c443557864a1769dbee"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs zlib zstd gmp mpfr readline"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --target=${OS_TRIPLET} \
        --with-build-sysroot=${sysroot_dir} \
        --enable-separate-code \
        --enable-cet \
        --enable-colored-disassembly \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-gold \
        --enable-ld=default \
        --enable-new-dtags \
        --enable-plugins \
        --enable-relro \
        --enable-threads \
        --disable-werror \
        --with-pic \
        --with-system-zlib \
        --with-system-readline
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    post_package_strip
}
