#! /bin/sh

name=gdk-pixbuf
version=2.44.2
revision=1
tarball_url="https://download.gnome.org/sources/gdk-pixbuf/2.44/gdk-pixbuf-${version}.tar.xz"
tarball_blake2b="bd02058980dfd6dbeb8ff1328d2160ea2deed8a957e456a15803ef7619818939a868f711c9d85a7947fe9ebea023210c930aaf8be09ad38351ae8ed3ce511188"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libjpeg-turbo libpng libx11 libtiff"

configure() {
    meson_configure \
        -Dgio_sniffing=false \
        -Dman=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
