#! /bin/sh

name=gdk-pixbuf
version=2.44.4
revision=1
git_url="https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
commit=c9e6d11cbfa085d7b59dd6ad3b1cbfa26348ce13
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libjpeg-turbo libpng libx11 libtiff"

configure() {
    meson_configure \
        -Dgio_sniffing=false \
        -Dman=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
