#! /bin/sh

name=giflib
version=6.1.2
revision=1
tarball_url="https://sourceforge.net/projects/giflib/files/giflib-${version}.tar.gz"
tarball_blake2b="3716747d8969a95dd27aade75b266916a6f9f12c0b31b810e9c334d62fa270b22d2db181d925fadd86e0e56e0a057f2517090206fb81df70cdbee2c1fef1d0f9"
imagedeps="imagemagick"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make \
        CC="${OS_TRIPLET}-gcc" \
        AR="${OS_TRIPLET}-ar" \
        OFLAGS="$TARGET_CFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS"
}

package() {
    make install \
        DESTDIR="${dest_dir}" \
        PREFIX="${prefix}" \

    rm -v "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
