#! /bin/sh

name=git
version=2.52.0
revision=1
tarball_url="https://www.kernel.org/pub/software/scm/git/git-${version}.tar.xz"
tarball_blake2b="f228174814b1048f12543a6a20f771017991f9a23778f12fc32020b38837990eb19bc69e891078692ac4ad4ae1cb2e0e77400760964e09c491046e4ed8b16f96"
imagedeps="build-essential libcurl4-gnutls-dev"
hostdeps="gcc pkg-config"
deps="core-libs python zlib curl openssl openssh"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp ${source_dir}/. .

        configure_script_path=./configure \
        ac_cv_iconv_omits_bom=yes \
        ac_cv_fread_reads_directories=no \
        ac_cv_snprintf_returns_bogus=no \
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS" \
        --with-gitconfig=/etc/gitconfig \
        --with-python=python3
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
