#! /bin/sh

name=glib2
repology_id=glib
version=2.84.4
revision=2
git_url="https://gitlab.gnome.org/GNOME/glib.git"
commit=41eca60845d3fc309af361f5e7f801ba339099aa
imagedeps="python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 libffi zlib"
source_allow_network=yes

early_prepare() {
    git submodule update --init --recursive
}

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled \
        -Dxattr=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
