#! /bin/sh

name=glib2
repology_id=glib
version=2.86.1
revision=1
git_url="https://gitlab.gnome.org/GNOME/glib.git"
commit=7b2afbd420c33878e7009ce9101c7d00ee2c2c8e
imagedeps="python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 libffi zlib"

early_prepare() {
    git submodule update --init --recursive
}

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled \
        -Dxattr=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
