#! /bin/sh

name=glib2
repology_id=glib
version=2.86.4
revision=1
tarball_url="https://download.gnome.org/sources/glib/2.86/glib-${version}.tar.xz"
tarball_blake2b="20dee8c99fdb410d7f9c09366f1688dbc075638fdecd44f67562cc9cc46e34712cd1357d5a4facadd36f3c45fceeb83c7910be4f9c819ad20778339cdfb34452"
imagedeps="python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 libffi zlib"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled \
        -Dxattr=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
    generate_glib_schemas_hook
}
