#! /bin/sh

name=gloire-install
skip_pkg_check=yes
version=4a28ac6fbd7e2239d89211fc0ddcb0ffb56b3721
revision=1
git_url="https://codeberg.org/Ironclad/gloire-install.git"
commit=${version}
deps="bash"

package() {
    mkdir -p "${dest_dir}"/usr/bin
    cp -f "${source_dir}"/gloire-install "${dest_dir}"/usr/bin/gloire-install
}
