#! /bin/sh

name=gnutls
version=3.8.10
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-${version}.tar.xz"
tarball_blake2b="0b62e93b2818d2265ca11e561724547fa3c24d08986eb77ea743b4af52773db975c1859164c7d405d9a9bedfa981af58f10f85100b6c0e3542a38c49af407a4d"
hostdeps="gcc pkg-config"
deps="core-libs libffi libunistring libtasn1 nettle p11-kit zlib brotli zstd libidn2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-default-trust-store-pkcs11="pkcs11:" \
        --enable-openssl-compatibility
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
