#! /bin/sh

name=gobject-introspection
version=1.84.0
version_short=1.84
revision=1
tarball_url="https://download.gnome.org/sources/gobject-introspection/${version_short}/gobject-introspection-${version}.tar.xz"
tarball_blake2b="c888cc36f980db61bf7da46199fecfbe944034b9ffdf3e6e21cc56b2177c3ece1a0571166ab37c63c6f0d5c80be91963c9e342f5162e2b908838d8eef9e193e3"
imagedeps="libpython3-dev gobject-introspection"
hostdeps="gcc pkg-config"
deps="core-libs glib2 python"

configure() {
    meson_configure \
        -Dgtk_doc=false \
        -Dbuild_introspection_data=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
