#! /bin/sh

name=gsettings-desktop-schemas
version=49.0
revision=1
tarball_url="https://download.gnome.org/sources/gsettings-desktop-schemas/49/gsettings-desktop-schemas-${version}.tar.xz"
tarball_blake2b="006f2b04762ed9aa93c638714d9037e5e5def07ec2236f57842f69628518756221c2390d9d48e0894a325c4214c89971ce74bdb90737fd2d33c60c4bc2714435"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2"

prepare() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
}

configure() {
    meson_configure \
        -Dintrospection=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    glib-compile-schemas "${dest_dir}${prefix}"/share/glib-2.0/schemas
    rm "${dest_dir}${prefix}"/share/glib-2.0/schemas/gschemas.compiled

    post_package_strip
}
