#! /bin/sh

name=gsettings-desktop-schemas
version=50.0
revision=1
git_url="https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git"
commit=0b3ea8e1a25ecfc33e9f6af1b1db93c4032b84e6
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2"

prepare() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
}

configure() {
    meson_configure \
        -Dintrospection=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    glib-compile-schemas "${dest_dir}${prefix}"/share/glib-2.0/schemas
    rm "${dest_dir}${prefix}"/share/glib-2.0/schemas/gschemas.compiled

    post_package_strip
    generate_glib_schemas_hook
}
