#! /bin/sh

name=gtest
version=1.17.0
revision=3
git_url="https://github.com/google/googletest.git"
commit=52eb8108c5bdec04579160ae17225d66034bd723
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
