#! /bin/sh

name=gtk3
repology_id=gtk
repology_srcname=gtk3
version=3.24.51
revision=2
git_url="https://gitlab.gnome.org/GNOME/gtk.git"
commit=0d3e55cf22abc81b532a3011462b3195f1480974
imagedeps="libglib2.0-dev libgdk-pixbuf-2.0 python3-packaging"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo glib2 gdk-pixbuf libx11 libxext libxcb libxinerama libxrender libxrandr libxfixes libxdamage pango fribidi libepoxy libxkbcommon fontconfig freetype2 libxi harfbuzz libxcursor gsettings-desktop-schemas dbus hicolor-icon-theme"

configure() {
    meson_configure \
        -Dprint_backends=file \
        -Dintrospection=false \
        -Dx11_backend=true \
        -Dbroadway_backend=true \
        -Dwayland_backend=false \
        -Dcolord=no
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
    generate_glib_schemas_hook

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    glib-compile-schemas /usr/share/glib-2.0/schemas/ >/dev/null
    gtk-query-immodules-3.0 --update-cache >/dev/null
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL
}
