#! /bin/sh

name=gtksourceview4
repology_id=gtksourceview
repology_srcname=gtksourceview4
version=4.8.4
revision=1
git_url="https://gitlab.gnome.org/GNOME/gtksourceview.git"
commit=7fd3adb3134bbec167167bb6400e018e4f781eb9
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3"

configure() {
    meson_configure \
        -Dglade_catalog=false \
        -Dgir=false \
        -Dvapi=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
