#! /bin/sh

name=gtksourceview4
version=4.8.2
revision=1
tarball_url="https://gitlab.gnome.org/GNOME/gtksourceview/-/archive/${version}/gtksourceview-${version}.tar.gz"
tarball_blake2b="ce1112c8e1942469d329a642418368522f44732cafd9d2ffc90a04c92f9ce8b196811fa13b22c5c91eca11e0e72d0c6e6c8d6ed51db0acf5c3bce5de26645ef8"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3"

configure() {
    meson_configure \
        -Dglade_catalog=false \
        -Dgir=false \
        -Dvapi=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
