#! /bin/sh

name=harfbuzz
version=11.3.2
revision=1
git_url="https://github.com/harfbuzz/harfbuzz.git"
commit=4e3df1c1383481ed5717603d5dd3453a04fb16ba
hostdeps="gcc pkg-config"
deps="core-libs graphite2 glib2 zlib freetype2 cairo icu"

configure() {
    meson_configure \
        -Dcpp_std=c++17 \
        -Dgraphite2=enabled \
        -Dglib=enabled \
        -Dgobject=disabled \
        -Dicu=enabled \
        -Dfreetype=enabled \
        -Dcairo=enabled \
        -Dintrospection=disabled \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
