#! /bin/sh

name=harfbuzz
version=14.1.0
revision=1
tarball_url="https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz"
tarball_blake2b="e42e81b38a94d5859ce170045c1313878ee3835ecb0d3522d80ad23138c4f2f856e87326d8e6abbf934e439d79d9dc59cf731f3e851f50a6f655d1fa92e97930"
hostdeps="gcc pkg-config"
deps="core-libs graphite2 glib2 zlib freetype2 cairo icu"

configure() {
    meson_configure \
        -Dgraphite2=enabled \
        -Dglib=enabled \
        -Dgobject=disabled \
        -Dicu=enabled \
        -Dfreetype=enabled \
        -Dcairo=enabled \
        -Dintrospection=disabled \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
