#! /bin/sh

name=hyfetch
version=1.99.0
revision=1
tarball_url="https://github.com/hykilpikonna/hyfetch/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="73e44d936124c993251b0d5f7261a1707136aee8fad8b1c660c0932223636db6cfbd1c6747bd16ee94370d6578e0220a96fb58c608ca26791957e855bc70deca"

package() {
    mkdir -p "${dest_dir}"/usr/bin
    cp -f "${source_dir}"/neofetch "${dest_dir}"/usr/bin/neofetch
}
