#! /bin/sh

name=icu
version=78.1
revision=1
tarball_url="https://github.com/unicode-org/icu/releases/download/release-${version}/icu4c-${version}-sources.tgz"
tarball_blake2b="382f57d25642aab2be8eea7713b205928d0a226b0ef5ff3ce2205be7a215a6dca2045617778643f62aa5d174b3f96ea9723c6c3847742dc5649686c131c511c7"
source_imagedeps="build-essential pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
    cp source/config/mh-linux source/config/mh-unknown

    mkdir -p cross-build
    cd cross-build

    ${source_dir}/source/configure \
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        --prefix=/usr/local

    make -j${parallelism}
    cd ..
}

configure() {
    config_data_packaging=library
    if [ "$JINX_ARCH" = riscv64 ]; then
        config_data_packaging=archive
    fi

        configure_script_path=${source_dir}/source/configure \
    autotools_configure \
        --with-cross-build=${source_dir}/cross-build \
        --with-data-packaging=${config_data_packaging}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
