#! /bin/sh

name=icu
version=78.3
revision=2
tarball_url="https://github.com/unicode-org/icu/releases/download/release-${version}/icu4c-${version}-sources.tgz"
tarball_blake2b="31cd41d900f7be20eafab42304e9369fa2074cd4e91c2808887db7013c639aa2e0e5c3c7a139d10e18d3300ea6094e10c2d9fc325678b6e986a11ed9181f4b0c"
source_imagedeps="build-essential pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
    cp source/config/mh-linux source/config/mh-unknown

    mkdir -p cross-build
    cd cross-build

    ${source_dir}/source/configure \
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        --prefix=/usr/local

    make -j${parallelism}
    cd ..
}

configure() {
    config_data_packaging=library
    if [ "$JINX_ARCH" = riscv64 ]; then
        config_data_packaging=archive
    fi

        configure_script_path=${source_dir}/source/configure \
    autotools_configure \
        --with-cross-build=${source_dir}/cross-build \
        --with-data-packaging=${config_data_packaging}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
