#! /bin/sh

name=iso-codes
version=4.19.0
revision=1
tarball_url="https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${version}/iso-codes-v${version}.tar.gz"
tarball_blake2b="18d2bce972108b92fcfada95274f784f2ab1f1c84921e0569d814c42f779598194562aa816d31596113aeee66789ea20d068ca8d47ed7bbe8c322ed93ad42f32"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
