#! /bin/sh

name=iso-codes
version=4.18.0
revision=1
tarball_url="https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${version}/iso-codes-v${version}.tar.gz"
tarball_blake2b="9d382682b1491d9470a536e3bd63e892c8901ab80f911c78cdcf33ed6f40a0f2da84464369f3ac82297ef72433124c9b486f658be351162f0ad5e730fb4ef897"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
