#! /bin/sh

name=jansson
version=2.15.0
revision=1
tarball_url="https://github.com/akheron/jansson/releases/download/v${version}/jansson-${version}.tar.gz"
tarball_blake2b="25134bd51458862f434ad73ca29c08f2c85da722a2b066e682ff237f493950edf649e69d7d3854bdb44a0f1e01f2f4bd53ad62889234177880e7403dbe8ccc79"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DJANSSON_BUILD_SHARED_LIBS=ON \
        -DJANSSON_BUILD_DOCS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
