#! /bin/sh

name=jwm
version=2.4.6
revision=4
tarball_url="https://github.com/joewing/jwm/releases/download/v${version}/jwm-${version}.tar.xz"
tarball_blake2b="2c43fd7faeb4faf9195e9647b9b0fd657b49d51f6e43651532afb4b66cfc1db142ec257d43d1be5e9f863ab8f88f31bf58b88e9b214eb4d72bb0393b5d815cde"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxft libxmu libjpeg-turbo libxpm libxinerama libpng"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

        configure_script_path=./configure \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    cp -v "${base_dir}"/build-support/jwm/system.jwmrc "${dest_dir}"/etc/
    post_package_strip
}
