#! /bin/sh

name=lcms
version=2.19
revision=1
tarball_url="https://github.com/mm2/Little-CMS/releases/download/lcms${version}/lcms2-${version}.tar.gz"
tarball_blake2b="e23091c7c2f4243d367c434d02f113ed833e0188c768b272a16d14766517f94a88a7f2402a40ec1a0747e9e1ad3fadad80590cc2db422a274b49d3f90b63e7ea"
hostdeps="gcc pkg-config"
deps="core-libs libjpeg-turbo libtiff"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
