#! /bin/sh

name=lcms
version=2.18
revision=1
tarball_url="https://github.com/mm2/Little-CMS/releases/download/lcms${version}/lcms2-${version}.tar.gz"
tarball_blake2b="16096647d5b6e91c7785159f841a90c94887497bd21117b539d7c5eac6a5f495efbc2cc06afc9a0cebb6af6d18e8ce7fafd346efad126f15110e663e2dc2d6ab"
hostdeps="gcc pkg-config"
deps="core-libs libjpeg-turbo libtiff"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
