#! /bin/sh

name=libarchive
version=3.7.9
revision=2
tarball_url="https://github.com/libarchive/libarchive/releases/download/v${version}/libarchive-${version}.tar.xz"
tarball_blake2b="7bcfb3fe8ffd9452f3d71cdc738144069594030278572ebba0bb247ad74fd68ec19822f281364878228ee311976e216614d4764e56c5fb7f98801695ab7aa7f4"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libexpat libxml2 xz zlib zstd"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    # Remove static libraries
    rm -v "${dest_dir}${prefix}/lib/libarchive.a"

    post_package_strip
}
