#! /bin/sh

name=libexpat
repology_id=expat
version=2.7.3
revision=3
git_url="https://github.com/libexpat/libexpat.git"
commit=4575e52f83e0d6d7bd24939eab8952bbc7bc358f
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
        cmake_source_dir="${source_dir}/expat" \
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
