#! /bin/sh

name=libexpat
repology_id=expat
version=2.7.4
fixed_version=$(echo ${version} | sed 's/\./_/g')
revision=1
tarball_url="https://github.com/libexpat/libexpat/releases/download/R_${fixed_version}/expat-${version}.tar.gz"
tarball_blake2b="e6cf9ad5b87b9d1f6525cb45ff7cae84495f61f386fdf0da9fc83ff7b49ce7217cd4d9611352998fff2b003e6b272ef8210bd1229f1d2a5ef850b7df22f624d5"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
