#! /bin/sh

name=libgcrypt
version=1.11.1
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${version}.tar.gz"
tarball_blake2b="3e8447599a504eb78b9ce18684d4905527becef39c63a5261ab6349043f98c639f9ee2d309017ad4f21a8ef10e4aeada7d240c8b2cea3202ab7e3c8a2b3e76ce"
imagedeps="build-essential libgpg-error-dev"
hostdeps="gcc pkg-config"
deps="core-libs libgpg-error"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-libgpg-error-prefix="${sysroot_dir}${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
