#! /bin/sh

name=libgtop
version=2.41.3
revision=1
tarball_url="https://download.gnome.org/sources/libgtop/2.41/libgtop-${version}.tar.xz"
tarball_blake2b="8a3d3a7d942d37eb532c889b14cc415324b975c136be28c985a3d047a174f5bfae3f862e3cdc8e0a49283c7be58dee9f38e8ceb260d848338d1000d58e8952e2"
# imagedeps="build-essential patchelf"
hostdeps="gcc pkg-config" # glib2 gobject-introspection"
deps="core-libs glib2 libxau"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-gtk-docdo \
        --disable-introspection
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
