#! /bin/sh

name=libgpg-error
version=1.56
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-${version}.tar.gz"
tarball_blake2b="767a5c3fb4b548374f1cf51c0e68026f76cbe0d727369eb64b74d2bb96dfbdedf15b7c660eac80771aee7c5beda181864a4dbdb7b5ac9c4c71ba5517f5706f02"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    cp -v src/syscfg/lock-obj-pub.${JINX_ARCH}-unknown-linux-gnu.h src/syscfg/lock-obj-pub.ironclad-mlibc.h

    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-threads \
        --enable-install-gpg-error-config
}

build() {
    make -j${parallelism} \
        CFLAGS_FOR_BUILD="$HOST_CFLAGS" \
        CXXFLAGS_FOR_BUILD="$HOST_CXXFLAGS" \
        LDFLAGS_FOR_BUILD="$HOST_LDFLAGS"
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
