#! /bin/sh

name=libjpeg-turbo
version=3.1.2
revision=2
git_url="https://github.com/libjpeg-turbo/libjpeg-turbo.git"
commit=4e151a4ad91001b3aa8c2ece2205c15f487ce320
imagedeps="nasm"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DWITH_JPEG8=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
