#! /bin/sh

name=libjpeg-turbo
version=3.1.3
revision=1
tarball_url="https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${version}/libjpeg-turbo-${version}.tar.gz"
tarball_blake2b="3c675aa56b3474ca8a27f355d14dd7411d90471564c5916884e87818b7165e73a6c6b416dc2800e31c10dd1390ae88353e81d80eceb2e22c00b6a81ac5cf3d65"
imagedeps="nasm"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DWITH_JPEG8=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
