#! /bin/sh

name=libnvmm
skip_pkg_check=yes
version=0.0git
revision=4
git_url="https://codeberg.org/Ironclad/libnvmm.git"
commit=18da3c125435124df2f33ce115f86aca855cc97c
hostdeps="gcc pkg-config"
deps="core-libs"

if [ "${JINX_ARCH}" = x86_64 ]; then

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}

fi
