#! /bin/sh

name=libnvmm
skip_pkg_check=yes
version=0.0git
revision=3
git_url="https://codeberg.org/Ironclad/libnvmm.git"
commit=d0b9860bcdf5a96486c2220614781e37b1d9985b
hostdeps="gcc pkg-config"
deps="core-libs"

if [ "${JINX_ARCH}" = x86_64 ]; then

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}

fi
