#! /bin/sh

name=libogg
version=1.3.5
revision=2
tarball_url="https://downloads.xiph.org/releases/ogg/libogg-${version}.tar.xz"
tarball_blake2b="464cf767902bd8bd463d3faaae01fecbe33d4cc87dabf38388ac961bfbe24e6d113f4ee88542e6bed6fd7eaaf0709c7f5cb7a306ee910527f79810054ccdbae7"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
