#! /bin/sh

name=libpng
version=1.6.50
revision=1
git_url="https://github.com/pnggroup/libpng.git"
commit=2b978915d82377df13fcbb1fb56660195ded868a
hostdeps="gcc pkg-config"
deps="core-libs zlib"

configure() {
    cmake_configure \
        -DPNG_STATIC=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
