#! /bin/sh

name=libpng
version=1.6.58
revision=1
tarball_url="https://prdownloads.sourceforge.net/libpng/libpng-${version}.tar.xz"
tarball_blake2b="51042e8f2b56d469b516db9cbde6d4b6813a62d1b7117898ba32a9a5ac5cd73832c627d7377745e5d5154aade6ec6928fc6b9cd9b96885f64b7ca7df19ca40ec"
hostdeps="gcc pkg-config"
deps="core-libs zlib"

configure() {
    cmake_configure \
        -DPNG_STATIC=OFF \
        -DPNG_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
