#! /bin/sh

name=libproxy
version=0.5.11
revision=1
git_url="https://github.com/libproxy/libproxy.git"
commit=3fd3a6e845c0386d91abc742453d0f29bf28c404
hostdeps="gcc pkg-config"
deps="core-libs glib2 gsettings-desktop-schemas"

configure() {
    meson_configure \
        -Ddocs=false \
        -Dpacrunner-duktape=false \
        -Dcurl=false \
        -Dvapi=false \
        -Dintrospection=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
