#! /bin/sh

name=libraw
version=0.22.0
revision=1
tarball_url="https://www.libraw.org/data/LibRaw-${version}.tar.gz"
tarball_blake2b="2063d4f89a1cd065bc4734ab99257f1b3e3b72e1d8c0ea7736dd703315e55f22a00ab336fa1455a9f694c4c1cbc78f7cd22a81d1e9ce9c07c1cd5c976de3f940"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}

