#! /bin/sh

name=libunistring
version=1.4
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/libunistring/libunistring-${version}.tar.xz"
tarball_blake2b="65dc91753ab8b1d6ca090dcbcaa9044c3e3cfe8e6b6cb0776138d6cee601b3e853a16e7a38beebed1f3dd715b3115b96fbc32a2def9f136ce675166ad605ae6d"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
