#! /bin/sh

name=libwnck
version=43.3
revision=1
git_url="https://gitlab.gnome.org/GNOME/libwnck.git"
commit=75e56cf1d7ef1edd61516bdf25bf7fdee8b935f3
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3"

configure() {
    meson_configure \
        -Dinstall_tools=true \
        -Dstartup_notification=disabled \
        -Dintrospection=disabled \
        -Dgtk_doc=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
