#! /bin/sh

name=libwebp
version=1.6.0
revision=1
git_url="https://github.com/webmproject/libwebp.git"
commit=4fa21912338357f89e4fd51cf2368325b59e9bd9
hostdeps="gcc pkg-config"
deps="core-libs libjpeg-turbo libpng freeglut sdl2-compat libtiff"

configure() {
    cmake_configure \
        -DWEBP_ENABLE_SWAP_16BIT_CSP=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
