#! /bin/sh

name=libxkbcommon
version=1.13.0
revision=1
git_url="https://github.com/xkbcommon/libxkbcommon.git"
commit=3049d310694fd70f1269bf48a1200aa4259e79b1
hostdeps="gcc pkg-config"
deps="core-libs libxcb libxml2 xkeyboard-config"

configure() {
    meson_configure \
        -Dxkb-config-root="$prefix"/share/X11/xkb \
        -Denable-x11=true \
        -Denable-wayland=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
