#! /bin/sh

name=libxkbcommon
version=1.12.3
revision=1
git_url="https://github.com/xkbcommon/libxkbcommon.git"
commit=f4f732790c35632427f857395f37c93e19729a2b
hostdeps="gcc pkg-config"
deps="core-libs libxcb libxml2 xkeyboard-config"

configure() {
    meson_configure \
        -Dxkb-config-root="$prefix"/share/X11/xkb \
        -Denable-x11=true \
        -Denable-wayland=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
