#! /bin/sh

name=libxml2
version=2.14.4
revision=1
git_url="https://gitlab.gnome.org/GNOME/libxml2.git"
commit=4c6b2c3096b1da0d0780fe0b4f147e837140468d
hostdeps="gcc pkg-config"
deps="core-libs icu readline zlib"

configure() {
    meson_configure \
        -Dpython=disabled \
        -Dhistory=enabled \
        -Dicu=enabled \
        -Dreadline=enabled \
        -Dzlib=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
