#! /bin/sh

name=libxau
version=1.0.12
revision=2
tarball_url="https://www.x.org/archive/individual/lib/libXau-${version}.tar.gz"
tarball_blake2b="f3f388352496eb2d18650bdf535e76dfe6dbdce8c20bdf0f3c99ee4fc72df469d7c4a44728d76a9102423e525cc7f52984ee03fdcbfd236cbfac8e7d8d17ba84"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
