#! /bin/sh

name=libxscrnsaver
version=1.2.5
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver.git"
commit=60c957ba8a727d01b376da0142aef7e18aa86fe1
hostdeps="gcc pkg-config"
deps="core-libs libxext libx11"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
