#! /bin/sh

name=libxfixes
version=6.0.2
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxfixes.git"
commit=70d5b0e37f8a759f3dbc218f22954347ceed094a
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
