#! /bin/sh

name=libxcrypt
version=4.5.1
revision=1
tarball_url="https://github.com/besser82/libxcrypt/releases/download/v${version}/libxcrypt-${version}.tar.xz"
tarball_blake2b="d21b2ed29b8fdc1ca99e64651e984c859a988064d1ca7e9c87e1c808b451307c56400dd802112bbe732c71f6468b55db5847cc5e4184771baf44f9c5cad0d1dc"
imagedeps="python3-passlib"
hostdeps="gcc pkg-config"
deps="mlibc libgcc libstdc++ libatomic"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-obsolete-api=yes \
        --disable-xcrypt-compat-files
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
