#! /bin/sh

name=libxpresent
version=1.0.2
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxpresent.git"
commit=4d92149372461bf575e8a09b1064a2884c38c3aa
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxext libxfixes libxrandr"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
