#! /bin/sh

name=libxml2
version=2.14.6
revision=1
git_url="https://gitlab.gnome.org/GNOME/libxml2.git"
commit=d23960a130c5bb82779c9405fbbf85e65fb3c57c
hostdeps="gcc pkg-config"
deps="core-libs icu readline zlib"

configure() {
    meson_configure \
        -Dpython=disabled \
        -Dhistory=enabled \
        -Dicu=enabled \
        -Dreadline=enabled \
        -Dzlib=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
