#! /bin/sh

name=libxkbcommon
version=1.12.2
revision=1
git_url="https://github.com/xkbcommon/libxkbcommon.git"
commit=bdf069f960dfdb5b44ae626d9ba7499142c2cb1e
hostdeps="gcc pkg-config"
deps="core-libs libxcb libxml2 xkeyboard-config"

configure() {
    meson_configure \
        -Dxkb-config-root="$prefix"/share/X11/xkb \
        -Denable-x11=true \
        -Denable-wayland=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
