#! /bin/sh

name=libxpm
version=3.5.18
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXpm-${version}.tar.gz"
tarball_blake2b="4391f06d8541249a3dc482c63f7577a4b668c46de446a4d717b77dd1560a0f9a042f909c010d7928dfb62ac5c8813657b6633006f2075a6c27e76693299ab9ca"
hostdeps="gcc pkg-config"
deps="core-libs libxext libxt"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
