#! /bin/sh

name=libxres
version=1.2.2
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXres-${version}.tar.gz"
tarball_blake2b="fd609d4aaa6bb4e26cf5df6261023789c170bd905d0f834a75dfdcbf3a7d545bfd7615d7122ba4344548e7feb190272d12bd237f6043e88907dcc38812ec0605"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxext"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
