#! /bin/sh

name=libxcrypt
version=4.5.2
revision=1
tarball_url="https://github.com/besser82/libxcrypt/releases/download/v${version}/libxcrypt-${version}.tar.xz"
tarball_blake2b="5954d3b77c5cc0f9e75e47a0f6c3dbbb6e09130875e9047b31cc069f835cf379f13995e16184e69d7b75f228e8d29bc98e4dffa77d95d70628f6847d652c07ea"
imagedeps="python3-passlib"
hostdeps="gcc pkg-config"
deps="mlibc libgcc libstdc++ libatomic"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-obsolete-api=yes \
        --disable-xcrypt-compat-files
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
