#! /bin/sh

name=libxres
version=1.2.3
revision=1
git_url="https://gitlab.freedesktop.org/xorg/lib/libxres.git"
commit=30c789e5065f7af7d6a03c09e3ceb073ed810bdd
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxext"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
