#! /bin/sh

name=libx11
version=1.8.13
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libX11-${version}.tar.xz"
tarball_blake2b="1ccb826184ed67d13e254d5cf20a40d2994837ffab6c05c647865927589e4aaa8933b57cc88226a6fb6ac836be88a57087e8f4d447b37b5327993c9f8834e8ea"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libxcb xtrans"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-keysymdefdir=${sysroot_dir}${prefix}/include/X11
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
