#! /bin/sh

name=limine
version=10.5.1
revision=1
tarball_url="https://codeberg.org/Limine/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="0538c91f9af3b37014fa3bf3880e9e9e727e40dea77621ca5c2d8b5f0deb9eda86deed198661ca57205ba4b8c3a22eea25980a5118695b16d7d7a7e8bbfee506"
imagedeps="mtools nasm llvm lld clang"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
