#! /bin/sh

name=limine
version=9.3.1
revision=1
tarball_url="https://github.com/limine-bootloader/limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="77f9119036eb7c0a04a176c7f42f38aec7b635e69c899f1e3a011b9f298e5189306ff594409e4daca480db72b79f61ec0b7b43bfcfdd335cea1e8ca4b1e0f790"
imagedeps="mtools nasm"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    if [ "$ARCHITECTURE" = "x86_64" ]; then
        X86_FLAGS="--enable-bios \
                   --enable-bios-cd \
                   --enable-bios-pxe \
                   --enable-uefi-ia32 \
        "
    fi

    autotools_configure \
        $X86_FLAGS \
        --enable-uefi-$ARCHITECTURE \
        --enable-uefi-cd \
        TOOLCHAIN_FOR_TARGET=${OS_TRIPLET}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
