#! /bin/sh

name=limine
version=9.5.2
revision=1
tarball_url="https://github.com/limine-bootloader/limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="3825c9436df92bff0c5c5d6884ed26a76be259cace165336f09402f3c235ff1c4a93e970e63cff8397c0d5637f9c8d3ea21dda6d99e0f923d9d5df89db8a647a"
imagedeps="mtools nasm"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    if [ "$ARCHITECTURE" = "x86_64" ]; then
        X86_FLAGS="--enable-bios \
                   --enable-bios-cd \
                   --enable-bios-pxe \
                   --enable-uefi-ia32 \
        "
    fi

    autotools_configure \
        $X86_FLAGS \
        --enable-uefi-$ARCHITECTURE \
        --enable-uefi-cd \
        TOOLCHAIN_FOR_TARGET=${OS_TRIPLET}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
