#! /bin/sh

name=llvm-libs
repology_id="llvm"
version=21.1.3
revision=2
tarball_url="https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/llvm-project-${version}.src.tar.xz"
tarball_blake2b="ad9ee083584cb72fea3722feb518f6c933c3a34ba91b1ca8b724f461aa744475a783512dd6f0ab60d533c73b37e42b32a06f905d4869f770a68180649656df44"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs ncurses zlib zstd libffi libxml2"

configure() {
        cmake_source_dir="${source_dir}/llvm" \
    cmake_configure \
        -UBUILD_SHARED_LIBS \
        -UENABLE_STATIC \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_EH=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_DEFAULT_TARGET_TRIPLE=${OS_TRIPLET} \
        -DLLVM_HOST_TRIPLE=${OS_TRIPLET} \
        -Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    rm -rf "${dest_dir}${prefix}"/lib/*.a
    rm -rf "${dest_dir}${prefix}"/bin

    post_package_strip
}
