#! /bin/sh

name=lua
version=5.4.8
revision=1
tarball_url="https://github.com/lua/lua/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="9fa35cbd372246a121cbd6e030a11f516ceb4f623b11b20f0cfef6502dc49cf3bf98508d1a1cb9a97318bcb17a32e871e3596874f72aa7b93a46a2cc94b72bd7"
imagedeps="nasm"
hostdeps="gcc pkg-config"
deps="core-libs readline"

build() {
    cp -rp "${source_dir}"/. ./
    sed -i 's|^#define LUA_ROOT "/usr/local/"$|#define LUA_ROOT "/usr/"|' luaconf.h

    make MYLIBS="-lreadline -lncursesw -ltinfow" CFLAGS="$TARGET_CFLAGS -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE" MYLDFLAGS="$TARGET_LDFLAGS" CC=${OS_TRIPLET}-gcc AR="${OS_TRIPLET}-ar rcu" RANLIB=${OS_TRIPLET}-ranlib -j${parallelism}
}

package() {
    mkdir -p "${dest_dir}${prefix}"/bin
    cp lua "${dest_dir}${prefix}"/bin/

    post_package_strip
}
