#! /bin/sh

name=mailutils
version=3.16
revision=1
tarball_url="https://ftp.gnu.org/gnu/mailutils/mailutils-${version}.tar.xz"
tarball_blake2b="dfef95ffd197bfc7279118472272c4c0d5b363cbe9d26499b6fb383638e9cb94da67832124dfd5948d718e170830c38a3d7eaf0cb77b0f1fde92eae808eb2930"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autoreconf -fvi
}

configure() {
    cp -rp ${source_dir}/. ./

        configure_script_path=./configure \
    autotools_configure \
        --disable-python \
        --disable-build-imap4d
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    ln -s mail "${dest_dir}${prefix}"/bin/mailx

    post_package_strip
}
