#! /bin/sh

name=mailutils
version=3.19
revision=1
tarball_url="https://ftp.gnu.org/gnu/mailutils/mailutils-${version}.tar.xz"
tarball_blake2b="a9d7147b5ed1a7614ae284b8655b467364ca521dd1efe275dda8c8b512399c3044447a5b00263a5e1f5e74cf7a7d1a805b6f4a2d4f27fb0962269de490050f02"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autoreconf -fvi
}

configure() {
    cp -rp ${source_dir}/. ./

        configure_script_path=./configure \
    autotools_configure \
        --disable-python \
        --disable-build-imap4d
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    ln -s mail "${dest_dir}${prefix}"/bin/mailx

    post_package_strip
}
