#! /bin/sh

name=marco
version=1.29.1
revision=1
git_url="https://github.com/mate-desktop/marco.git"
commit=87e3aadef2379c94ff6d47a6bc9c4d6006d334a9
imagedeps="libglib2.0-dev libgdk-pixbuf2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3 mate-desktop libcanberra libxres libxcomposite libxpresent libsm libice mate-settings-daemon"

configure() {
    meson_configure \
        -Dstartup-notification=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
