#! /bin/sh

name=mate-screensaver
version=1.28.0
revision=1
tarball_url="https://github.com/mate-desktop/mate-screensaver/releases/download/v${version}/mate-screensaver-${version}.tar.xz"
tarball_blake2b="5c78afb2f52fd264da8e62455f53e6a214997d62f604323bdf2149012d62ba14c0435135d6ca22105be5cd46b581799aafd91d18e5caeeacf2cf07c98cc67091"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs gtk3 dbus-glib dconf libmatekbd mate-desktop mate-menus libnotify mate-session-manager mate-panel libxscrnsaver"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-locking \
        --with-kbd-layout-indicator \
        --with-xf86gamma-ext \
        --with-xscreensaverdir=/usr/share/xscreensaver/config \
        --with-xscreensaverhackdir=/usr/lib/misc/xscreensaver \
        --without-console-kit \
        --with-x \
        --without-elogind \
        --with-libnotify \
        --with-libgl \
        --without-systemd \
        --disable-debug \
        --disable-pam
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    chmod +s "${dest_dir}${prefix}"/libexec/mate-screensaver-dialog

    post_package_strip
}
