#! /bin/sh

name=mate-panel
version=1.28.7
revision=2
tarball_url="https://github.com/mate-desktop/mate-panel/releases/download/v${version}/mate-panel-${version}.tar.xz"
tarball_blake2b="1649bc3d115ee37e70870d147f04036aaeea76a2319931ef5783ccd11fc1903efd9637ece54a0ca8255fefa728e40cc6b4b60a789d300515f715ae8dd3a4342c"
imagedeps="itstool libglib2.0-bin libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs gtk3 libmateweather dconf mate-desktop mate-menus dbus libice libsm libwnck"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir="${EPREFIX}"/usr/libexec/mate-applets \
        --disable-deprecation-flags \
        --enable-x11 \
        --disable-introspection \
        --disable-wayland
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
