#! /bin/sh

name=mate-applets
version=1.28.1
revision=1
tarball_url="https://github.com/mate-desktop/mate-applets/releases/download/v${version}/mate-applets-${version}.tar.xz"
tarball_blake2b="95b8773f9cf1a6156385d1f548c46eb915a9ce16e382a23aabac9c598daf217c124fdad5995d2e30e91e8c5a2f08ca94aadb8591e5d10a359249b63e8c25d588"
imagedeps="itstool libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
# libgtop not specified as it's stubbed
deps="core-libs gtk3 mate-panel libnotify dbus-glib gtksourceview4"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir=/usr/libexec/mate-applets \
        --with-x \
        --without-upower \
        --without-nl \
        --disable-polkit \
        --disable-cpufreq
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
