#! /bin/sh

name=mate-panel
version=1.28.4
revision=1
tarball_url="https://github.com/mate-desktop/mate-panel/releases/download/v${version}/mate-panel-${version}.tar.xz"
tarball_blake2b="2db3962071eca43e29b4687988819de5777d753abea3b6087d3ff588c7db6f0305986943abebd700bdc3d0d6ddc6c8531debbbafdad92fad8ece48e8d906e1a9"
imagedeps="itstool libglib2.0-bin libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs gtk3 libmateweather dconf mate-desktop mate-menus dbus libice libsm libwnck"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir="${EPREFIX}"/usr/libexec/mate-applets \
        --disable-deprecation-flags \
        --enable-x11 \
        --disable-introspection \
        --disable-wayland
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
