#! /bin/sh

name=mate-applets
version=1.28.0
revision=1
tarball_url="https://github.com/mate-desktop/mate-applets/releases/download/v${version}/mate-applets-${version}.tar.xz"
tarball_blake2b="ed2a13e8c79daeb88706ee4b6ad3146e2d3795e6a430bfc494672cf4a0de2ec088ba453368afdc530ca7fffff82893d4d3929e21e224a418bd4382cfe36e5812"
imagedeps="itstool libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
# libgtop not specified as it's stubbed
deps="core-libs gtk3 mate-panel libnotify dbus-glib gtksourceview4"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir=/usr/libexec/mate-applets \
        --with-x \
        --without-upower \
        --without-nl \
        --disable-polkit \
        --disable-cpufreq
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
