#! /bin/sh

name=mate-icon-theme
version=1.27.0
revision=1
tarball_url="https://pub.mate-desktop.org/releases/1.27/mate-icon-theme-${version}.tar.xz"
tarball_blake2b="d86603cad3ddb3df40fadcc752ac43bf1271cb2e860eb37906fbf12c6eb2e3dd19b6600769374910a22ad41fa72481efa52f13d2235fb3e9ea1fe773fb15de0d"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="gettext"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autoreconf -fvi -I/sysroot/usr/share/aclocal
}

configure() {
    autotools_configure \
      --disable-icon-mapping
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
