#! /bin/sh

name=mate-utils
version=1.28.0
revision=1
tarball_url="https://github.com/mate-desktop/mate-utils/releases/download/v${version}/mate-utils-${version}.tar.xz"
tarball_blake2b="dadcbeffb35cb31629fdc1f142c5734cd5f3c72eb38b37d699a99ab1d4cc13a0d018ba85a6de743a40fef2ef75fa5f6aad88893d3958e5a894dae9926ab13459"
imagedeps="itstool libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs libgtop gtk3 libcanberra libice libsm mate-panel"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-zlib \
        --enable-debug=minimum \
        --with-x \
        --enable-gdict-applet \
        --enable-nls \
        --disable-disk_image_mounter
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
