#! /bin/sh

name=mate-panel
version=1.28.6
revision=1
tarball_url="https://github.com/mate-desktop/mate-panel/releases/download/v${version}/mate-panel-${version}.tar.xz"
tarball_blake2b="6a8c14c6bf520aeb2d37f06a556dcc52a7c8c2ee5dd5a56e92f11731d45ea242b15d2dfb77e3c4e84304a38e449f292fa27a0a29ea1b18d048c26abd2f0c45e0"
imagedeps="itstool libglib2.0-bin libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs gtk3 libmateweather dconf mate-desktop mate-menus dbus libice libsm libwnck"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir="${EPREFIX}"/usr/libexec/mate-applets \
        --disable-deprecation-flags \
        --enable-x11 \
        --disable-introspection \
        --disable-wayland
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
