#! /bin/sh

name=mate-themes
version=3.22.26
revision=1
tarball_url="https://github.com/mate-desktop/mate-themes/releases/download/v${version}/mate-themes-${version}.tar.xz"
tarball_blake2b="e66d397be02df8f91b972e5073397019627508f90f8100e25601d93a77f72e368b57e1c664d72972f097f880c301c534c0cc06479637df39d16b8c9382b192d2"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
