#! /bin/sh

name=mate-terminal
version=1.28.1
revision=2
git_url="https://github.com/mate-desktop/mate-terminal.git"
commit=8634b87ff36933acf072393486a422670330f7e7
imagedeps="meson ninja-build libglib2.0-dev git itstool"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core glib2 dconf gdk-pixbuf libice libsm libx11 pango gtk3 vte mate-desktop"

early_prepare() {
    # Fix revision of mate-submodules
    sed -i 's/^revision=.*/revision = 4074560e3642a53ace07b31baaf3f04c060dcd0b/g' subprojects/mate-submodules.wrap

    meson subprojects download
}

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
