#! /bin/sh

name=mate-common
version=1.28.0
revision=1
tarball_url="https://github.com/mate-desktop/mate-common/releases/download/v${version}/mate-common-${version}.tar.xz"
tarball_blake2b="eb521c824b4f8875de40dee0acb75097a92fd4b64ca03c7759e671f9565e0155b6eb82287ec02ebe3e700621f62261b7f0912c7dab593401277b9eb83c5a01f1"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
