#! /bin/sh

name=mesa
version=25.3.1
revision=1
git_url="https://gitlab.freedesktop.org/mesa/mesa.git"
commit=5005a50879b11b953ade113fccd13a208f706ba0
imagedeps="python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm-libs libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dvulkan-drivers=swrast \
        -Dvideo-codecs=all_free
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
