#! /bin/sh

name=meson
version=1.10.1
revision=1
tarball_url="https://github.com/mesonbuild/meson/releases/download/${version}/meson-${version}.tar.gz"
tarball_blake2b="0d99736cdc1b3576026bce775a15c805c8178e2b21615829e028a05f5265cb5c72bd04a9ac5a45a9cf247d54f37f25a98f094efb5e1addb78e9a6ff863629642"
imagedeps="python3-build python3-installer"
hostdeps="pkg-config"
deps="core-libs python ninja"

build() {
    cp -rp "${source_dir}"/. ./

    python3 -m build \
        --wheel \
        --no-isolation
}

package() {
    DEB_PYTHON_INSTALL_LAYOUT=deb python3 -m installer \
        --destdir="${dest_dir}" \
        --prefix="${prefix}" \
        dist/*.whl

    post_package_strip
}
