#! /bin/sh

name=metalog
version=20230719
revision=1
tarball_url="https://github.com/hvisage/metalog/archive/refs/tags/metalog-${version}.tar.gz"
tarball_blake2b="6088c86fad90185fcb22a96ff88686647eac1fb4216884f43c07dff23274efc748c908f6f98162f743d2528437748f79809dfe6911d8d47e6cf7e58c8f3ca3b4"
source_deps="autoconf-archive"
source_hostdeps="autoconf automake pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs pcre2"

prepare() {
    autoreconf -fvi -I${sysroot_dir}/usr/share/aclocal
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
