#! /bin/sh

name=mlibc-headers
skip_pkg_check=yes
revision=18
from_source=mlibc
hostdeps="pkg-config"

configure() {
    meson_configure \
        -Dheaders_only=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
