#! /bin/sh

name=mlibc
version=1eef3c66f466454183acfc6b0a9766827ee7d494
revision=1
tarball_url="https://github.com/managarm/mlibc/archive/${version}.tar.gz"
tarball_blake2b="c0e50283b5dc59dacca413d70cff53cc0a3f5d62c29385eb6d214c4874567996216f908e89c9990c8d03c41426ee6d6daae6d1c4b48d858942f449c2549eacde"
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config libgcc-binaries"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg"
deps="mlibc-headers"

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,/usr/local/libgcc-binaries/libgcc-$ARCHITECTURE.a" \
    meson_configure_noflags \
        --buildtype=debugoptimized \
        -Dno_headers=true \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
