#! /bin/sh

name=nano
version=8.6
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/nano/nano-${version}.tar.xz"
tarball_blake2b="f7e17085d237ec3512b21bb732c2ebcf71a96991344acd0efc3592a650be856aed3ad958df59e27f332f750ac5e46ba7ed06b23093c8b68c4bf0a94aeecd2af0"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc
    cp -v "${base_dir}"/build-support/nano/nanorc "${dest_dir}"/etc/

    post_package_strip
}
