#! /bin/sh

name=nano
version=8.7
revision=1
tarball_url="https://ftp.gnu.org/gnu/nano/nano-${version}.tar.xz"
tarball_blake2b="4a7a67f854969960c96d1e3b2c7184f9d9c9fb305a14ff9764a39a8103ca5f5878f9e344b0dc522e27643f93e57582881ea8e664ac9c6eaa99c3b2d9632febdc"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc
    cp -v "${base_dir}"/build-support/nano/nanorc "${dest_dir}"/etc/

    post_package_strip
}
