#! /bin/sh

name=nasm
version=3.00
revision=1
tarball_url="https://www.nasm.us/pub/nasm/releasebuilds/${version}/nasm-${version}.tar.xz"
tarball_blake2b="9cfb8debdc4623cbd5dee2dbc8f4c52bedbf6bee6aa9165bf0abc31658e969ad54446e327ee3b65978396640dce5bb2dfe1ba2314afc0e5eb32b918d90d66a4e"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
