#! /bin/sh

name=ninja
version=1.13.2
revision=1
git_url="https://github.com/ninja-build/ninja.git"
commit=3441b633c2fe2c494e958780ba0f4227b1327634
hostdeps="gcc pkg-config"
deps="core-libs gtest"

configure() {
    cmake_configure \
        -DBUILD_TESTING=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
