#! /bin/sh

name=ninja
version=1.13.1
revision=3
git_url="https://github.com/ninja-build/ninja.git"
commit=79feac0f3e3bc9da9effc586cd5fea41e7550051
hostdeps="gcc pkg-config"
deps="core-libs gtest"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
