#! /bin/sh

name=noto-fonts
repology_id=fonts:noto
version=2026.04.01
revision=1
git_url="https://github.com/notofonts/notofonts.github.io"
commit=132db3be0104de9ca0aac3c7b1dd33a8fd29ff39

package() {
    cd "${source_dir}"
    install -Dm644 fonts/*/hinted/ttf/*.tt[fc] -t "${dest_dir}"/usr/share/fonts/noto

    install -Dm644 "${base_dir}"/build-support/noto-fonts/*.conf -t "${dest_dir}"/usr/share/fontconfig/conf.avail/
    install -d "${dest_dir}"/usr/share/fontconfig/conf.default
    ln -rs "${dest_dir}"/usr/share/fontconfig/conf.avail/* "${dest_dir}"/usr/share/fontconfig/conf.default
}
