#! /bin/sh

name=nspr
version=4.38
revision=1
tarball_url="https://archive.mozilla.org/pub/nspr/releases/v${version}/src/nspr-${version}.tar.gz"
tarball_blake2b="a81cfcf371479146abed18bf1f34dded3b793512e2d9c4a7d3e6981b7fc9e6941c6186ad0dce0b27cc95a1e70cfb9c6184baba0c1c2fd9651676c530799e7ab9"
imagedeps="build-essential gcc"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    # Disable two unneeded scripts
    sed -i '/^RELEASE/s|^|#|' ${source_dir}/nspr/pr/src/misc/Makefile.in
    # Disable static libraries
    sed -i 's|$(LIBRARY) ||'  ${source_dir}/nspr/config/rules.mk

    autotools_recursive_regen
}

configure() {
        CC="${OS_TRIPLET}-gcc" \
        CXX="${OS_TRIPLET}-g++" \
        HOST_CC="gcc" \
        HOST_CFLAGS="${HOST_CFLAGS}" \
        HOST_CXXFLAGS="${HOST_CXXFLAGS}" \
        HOST_CPPFLAGS="${HOST_CPPFLAGS}" \
        HOST_LDFLAGS="${HOST_LDFLAGS}" \
        CROSS_COMPILE=1 \
        configure_script_path="${source_dir}/nspr/configure" \
    autotools_configure \
        --enable-optimize \
        --with-mozilla \
        --with-pthreads \
        --enable-64bit
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
