#! /bin/sh

name=nss
version=3.116
revision=1
tarball_url="https://archive.mozilla.org/pub/security/nss/releases/NSS_$(echo ${version} | sed 's/\./_/g')_RTM/src/nss-${version}.tar.gz"
tarball_blake2b="2a9a43a4319447d087fa107b3a5d33e769212177a334660a92ee68b17eb0554d2194e1c3d1eb32c01b083e49b6707e8e3ed1628c407d7efc2bb3aea073249f19"
imagedeps="build-essential gcc libnspr4-dev"
hostdeps="gcc pkg-config"
deps="core-libs nspr p11-kit sqlite zlib"

configure() {
    cp -rpf "${source_dir}"/. ./
}

build() {
    mkdir -p dist

    cd nss

    # First, build a host version of nsinstall.
        CC=gcc \
        BUILD_OPT=1 \
        NSPR_INCLUDE_DIR=/usr/include/nspr \
        USE_SYSTEM_ZLIB=1 \
        ZLIB_LIBS=-lz \
        NSS_ENABLE_WERROR=0 \
        USE_64=1 \
        NSS_USE_SYSTEM_SQLITE=1 \
        NS_USE_GCC=1 \
        CC_IS_GCC=1 \
        NSDISTMODE=copy \
    make -C coreconf -j${parallelism}

    # Save the path to the nsinstall binary.
    nsinstall=$(realpath coreconf/nsinstall/*gcc_glibc*/nsinstall)

    (
        # Set up the environment for cross-compilation.
        export BUILD_OPT=1
        export NSPR_INCLUDE_DIR=${sysroot_dir}${prefix}/include/nspr
        export USE_SYSTEM_ZLIB=1
        export FREEBL_NO_DEPEND=1
        export FREEBL_LOWHASH=1
        export NSS_SEED_ONLY_DEV_URANDOM=1
        export ZLIB_LIBS=-lz
        export NSS_ENABLE_WERROR=0
        export USE_64=1
        export NSS_USE_SYSTEM_SQLITE=1
        export NS_USE_GCC=1
        export CC_IS_GCC=1
        export CROSS_COMPILE=1
        export NSDISTMODE=copy
        export NSS_DISABLE_GTESTS=1
        export SOURCE_PREFIX=${build_dir}/builds/${name}/nss/dist
        export CC=${OS_TRIPLET}-gcc
        export CXX=${OS_TRIPLET}-g++
        export XCFLAGS="${TARGET_CFLAGS}"
        export LDFLAGS="${TARGET_LDFLAGS}"

        # Then, build some configuration items courtesy of BLFS (see the patches).
        make V=1 -C config OS_TEST=${JINX_ARCH} NSINSTALL=${nsinstall} -j${parallelism}

        # Then build the main libraries and binaries.
        make V=1 OS_TEST=${JINX_ARCH} NSINSTALL=${nsinstall} -j${parallelism}
    )
}

package() {
    cd nss

    install -v -m755 -d "${dest_dir}${prefix}/bin"
    install -v -m755 dist/Linux*/bin/certutil "${dest_dir}${prefix}"/bin
    # install -v -m755 dist/Linux*/bin/nss-config "${dest_dir}${prefix}"/bin
    install -v -m755 dist/Linux*/bin/pk12util "${dest_dir}${prefix}"/bin

    install -v -m755 -d "${dest_dir}${prefix}/lib"
    install -v -m755 dist/Linux*/lib/*.so "${dest_dir}${prefix}"/lib

    install -v -m755 -d "${dest_dir}${prefix}/include/nss"
    install -v -m644 dist/public/nss/* "${dest_dir}${prefix}/include/nss"
    install -v -m644 dist/private/nss/* "${dest_dir}${prefix}/include/nss"

    install -v -m755 -d "${dest_dir}${prefix}/lib/pkgconfig"
    # install -v -m644 dist/Linux*/lib/pkgconfig/nss.pc "${dest_dir}${prefix}/lib/pkgconfig"

    # Install the certificate data
    install -v -m755 -d "${dest_dir}${prefix}/share/nss"
    install -v -m644 lib/ckfw/builtins/certdata.txt "${dest_dir}${prefix}/share/nss"

    post_package_strip
}
