#! /bin/sh

name=openssh
version=10.2p1
revision=1
tarball_url="https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${version}.tar.gz"
tarball_blake2b="8c031b10b1642e21b46f7d1db84ba42692e378a54af3d8e5b5c8706c3a0a06d442a02ed8803063121e7ff325ea275cad4432b9eaa6a7f47a4d7cfad504953ab6"
hostdeps="gcc pkg-config"
deps="core-libs zlib openssl"

prepare() {
    autotools_recursive_regen
}

configure() {
        ossh_cv_utmpx_h_has_ut_addr=no \
    autotools_configure \
        --sysconfdir=/etc/ssh \
        --disable-strip \
        --with-ssl-engine \
        --with-privsep-user=nobody \
        --with-privsep-path=${prefix}/share/empty.sshd \
        --with-default-path=${prefix}/local/sbin:${prefix}/local/bin:${prefix}/bin \
        --without-zlib-version-check \
        --with-xauth=/usr/bin/xauth \
        --with-pid-dir=/run
}

build() {
    make -j${parallelism}
}

package() {
    install -v -m700 -d "${dest_dir}${prefix}"/share/empty.sshd
    install -v -d "${dest_dir}"/run

    DESTDIR="${dest_dir}" make install

    post_package_strip
}
