#! /bin/sh

name=openssl
version=4.0.0
revision=1
tarball_url="https://github.com/openssl/openssl/releases/download/openssl-${version}/openssl-${version}.tar.gz"
tarball_blake2b="bea6e52456df3d6881dd9e800113886af64168eaa92a69cec95fb6e1cebfb675581fc75f0918aa6aa6654a36043444326da080db58781fe073ea0d0911e81982"
hostdeps="gcc pkg-config"
deps="core-libs zlib"

configure() {
        CC=${OS_TRIPLET}-gcc \
        CXX=${OS_TRIPLET}-g++ \
        AR=${OS_TRIPLET}-ar \
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ${source_dir}/Configure \
        --prefix=${prefix} \
        --openssldir=/etc/ssl \
        --libdir=lib \
        ${OS_TRIPLET} \
        shared \
        zlib-dynamic \
        no-afalgeng
}

build() {
    make -j${parallelism}
}

package() {
    # Disable installing static libraries.
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile

    DESTDIR="${dest_dir}" make DESTDIR="${dest_dir}" MANSUFFIX=ssl install

    post_package_strip
}
