#! /bin/sh

name=os-test
skip_pkg_check=yes
version=0.0git
revision=2
git_url="https://gitlab.com/sortix/os-test.git"
commit=e0aba6b11bd2f10884473a4597a04654ef3332c0
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cp -rp "${source_dir}/." ./
    rm -rf .git

    make all -j${parallelism} \
        OS=ironclad \
        CC=${OS_TRIPLET}-gcc \
        CC_FOR_BUILD=cc \
        CFLAGS_FOR_BUILD="-pthread"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/os-test"
    cp -rp . "${dest_dir}${prefix}/share/os-test/"
}
