#! /bin/sh

name=oss
version=4.2
revision=1
tarball_url="http://www.4front-tech.com/developer/sources/stable/gpl/oss-v${version}-build2020-src-gpl.tar.bz2"
tarball_sha512=6b0c5390e92f9c9466669600321140b54d1fde5eeaef2f9938d6bdbc7ae686f4a1ad0fa9669a1505962eb515d61d29d8a677911557a9b245ce039e1ab3b77d69
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
        IRONCLAD_CC=${OS_TRIPLET}-gcc \
        IRONCLAD_HOSTCC=cc \
        IRONCLAD_CPLUSPLUS=${OS_TRIPLET}-g++ \
        IRONCLAD_CFLAGS="${TARGET_CFLAGS}" \
        IRONCLAD_LDFLAGS="${TARGET_LDFLAGS}" \
        IRONCLAD_ENDIAN=LITTLE \
        IRONCLAD_OS=Ironclad \
        IRONCLAD_ARCH=${JINX_ARCH} \
    ${source_dir}/configure --enable-libsalsa=NO --only-drv= --target=ironclad-${JINX_ARCH}
}

build() {
        CC=${OS_TRIPLET}-gcc \
    make -j1
}

package() {
    make copy DESTDIR="${dest_dir}"
}
