#! /bin/sh

name=p11-kit
version=0.25.10
revision=1
tarball_url="https://github.com/p11-glue/p11-kit/releases/download/${version}/p11-kit-${version}.tar.xz"
tarball_blake2b="9f5a1be36a5b67ac35b294afdacf1b3a5c1c579b04e3407ea7bc6899cfe74330682653da50975a13e443b3a79379fdf6c6ed2a778933cf5dbba4fdf6dc52c99a"
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1"

prepare() {
    sed '20,$ d' -i ${source_dir}/trust/trust-extract-compat

    cat >> ${source_dir}/trust/trust-extract-compat << EOF
# Copy existing anchor modifications to /etc/ssl/local
${prefix}/libexec/make-ca/copy-trust-modifications

# Update trust stores
${prefix}/bin/make-ca -r
EOF
}

configure() {
    meson_configure \
        -Dtrust_paths=/etc/pki/anchors
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -svf "../libexec/p11-kit/trust-extract-compat" "${dest_dir}${prefix}/bin/update-ca-certificates"

    post_package_strip
}
