#! /bin/sh

name=p11-kit
version=0.25.8
revision=1
git_url="https://github.com/p11-glue/p11-kit.git"
commit=2ee61264fa004e65176adf601c0bacc355d8b63b
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1"

early_prepare() {
    git submodule update --init --recursive
}

prepare() {
    sed '20,$ d' -i ${source_dir}/trust/trust-extract-compat

    cat >> ${source_dir}/trust/trust-extract-compat << EOF
# Copy existing anchor modifications to /etc/ssl/local
${prefix}/libexec/make-ca/copy-trust-modifications

# Update trust stores
${prefix}/bin/make-ca -r
EOF
}

configure() {
    meson_configure \
        -Dtrust_paths=/etc/pki/anchors
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -svf "../libexec/p11-kit/trust-extract-compat" "${dest_dir}${prefix}/bin/update-ca-certificates"

    post_package_strip
}
