#! /bin/sh

name=p11-kit
version=0.26.1
revision=1
tarball_url="https://github.com/p11-glue/p11-kit/releases/download/${version}/p11-kit-${version}.tar.xz"
tarball_blake2b="a270c414c3bceac868b32c3fc004cc1cb00c53aa28e34c63eaf7124df29a3dd6c40aa9513e533169d4d0e87c6363a0c29338abc74885ade6610343d954976d2f"
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1 bash-completion"

prepare() {
    sed '20,$ d' -i ${source_dir}/trust/trust-extract-compat

    cat >> ${source_dir}/trust/trust-extract-compat << EOF
# Copy existing anchor modifications to /etc/ssl/local
${prefix}/libexec/make-ca/copy-trust-modifications

# Update trust stores
${prefix}/bin/make-ca -r
EOF
}

configure() {
    meson_configure \
        -Dtrust_paths=/etc/pki/anchors
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -svf "../libexec/p11-kit/trust-extract-compat" "${dest_dir}${prefix}/bin/update-ca-certificates"

    post_package_strip
}
