#! /bin/sh

name=pango
version=1.56.3
revision=2
tarball_url="https://download.gnome.org/sources/pango/1.56/pango-${version}.tar.xz"
tarball_blake2b="02b12409a0d16090ebde13e6d92b2053468e32b4b97eb0f758e05ea2ffc44141367b77cef7bb2b701785a4f9f9071d06e47a6d4974e2aa5839571fd0de19efc3"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 fontconfig freetype2 fribidi cairo libx11 harfbuzz libxft"

configure() {
    meson_configure \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
