#! /bin/sh

name=pass
repology_id=password-store
repology_srcname=password-store
version=1.7.4
revision=1
tarball_url="https://git.zx2c4.com/password-store/snapshot/password-store-${version}.tar.xz"
tarball_blake2b=db1a34b5900802731deaf09d3ade1d3f00022fd21eb0b21140dca3d399c89183dc901e5bce15d7bb6041e62017e2b8b6df61c6ec3eadb1df6c0278dbc6c2bc11
deps="core-libs git tree"

package() {
    cp -r "${source_dir}"/. ./
    make DESTDIR="${dest_dir}" PREFIX="${prefix}" install
    post_package_strip
}
