#! /bin/sh

name=pass
repology_id=password-store
repology_srcname=password-store
version=1.7.4
revision=1
git_url="https://git.zx2c4.com/password-store"
branch=${version}
deps="core-libs git tree"

package() {
    cp -r "${source_dir}"/. ./
    make DESTDIR="${dest_dir}" PREFIX="${prefix}" install
    post_package_strip
}
