#! /bin/sh

name=pcre2
version=10.46
revision=1
git_url="https://github.com/PCRE2Project/pcre2.git"
commit=b2bd4254b379b9d7dc9a3dda060a7e27009ccdff
hostdeps="gcc pkg-config"
deps="core-libs bzip2 readline zlib"

configure() {
    cmake_configure \
        -DPCRE2_BUILD_PCRE2_16=ON \
        -DPCRE2_BUILD_PCRE2_32=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
