#! /bin/sh

name=pcre2
version=10.45
revision=2
tarball_url="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${version}/pcre2-${version}.tar.gz"
tarball_blake2b="e871e052853fac51d92fbfb5a2bb7a15b2830582315cfed047df8147c04f30c5a5e1ddd7275f6f894c33e2e170afdb2611937592907a29a025d665341e93b46a"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 readline zlib"

configure() {
    cmake_configure \
        -DPCRE2_BUILD_PCRE2_16=ON \
        -DPCRE2_BUILD_PCRE2_32=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
