#! /bin/sh

name=pixman
version=0.46.2
revision=1
git_url="https://gitlab.freedesktop.org/pixman/pixman.git"
commit=195e9f88899d80ec75fdb0ff469206cd4adb129f
hostdeps="gcc pkg-config"
deps="core-libs libpng"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
