#! /bin/sh

name=pkg-config
repology_id=pkgconf
version=2.5.1
revision=1
tarball_url="https://distfiles.ariadne.space/pkgconf/pkgconf-${version}.tar.xz"
tarball_blake2b="0995c1d649876d27e9275a77b702c0c100979c7b83fb7b58c925ca287be5e1568dd7ae2781dac51beb9e84a41d4424428f0542e4de488c45d005d602e76e1277"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -s pkgconf "${dest_dir}${prefix}"/bin/pkg-config

    post_package_strip
}
