#! /bin/sh

name=pkg-config
repology_id=pkgconf
version=2.5.0
revision=1
tarball_url="https://distfiles.ariadne.space/pkgconf/pkgconf-${version}.tar.xz"
tarball_blake2b="f26e1b0f4d5bc22bfabc1a922859f83148c6995487b228973818260e1e2285b473eb572cd52e20e76ed7003e75d9c924f2cec28f6a379ce1db3312adbb91d087"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    ln -s pkgconf "${dest_dir}${prefix}"/bin/pkg-config

    post_package_strip
}
