#! /bin/sh

name=pluma
version=1.28.0
revision=1
tarball_url="https://github.com/mate-desktop/pluma/releases/download/v${version}/pluma-${version}.tar.xz"
tarball_blake2b="10813717b7d18a0836059a10deb67a61b00a73cf3d5b18f12a9e760b8b65053b3a82dc0ac9af898d9f2bb4d6998db536bcaef143024ae91f9035fe6e1ee72fea"
imagedeps="libglib2.0-dev-bin libglib2.0-bin itstool"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core glib2 libpeas libxml2 gtk3 cairo gdk-pixbuf gtksourceview4 libice libsm pango mate-desktop"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-introspection \
        --disable-spell
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
