#! /bin/sh

name=posixtest
skip_pkg_check=yes
version=4cf97b0d46c330edfb440ee2558bc8c49b4abe1a
revision=1
git_url="https://codeberg.org/Ironclad/posixtest"
commit=${version}
source_imagedeps="git"
source_hostdeps="automake autoconf libtool pkg-config"
source_allow_network="yes"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    ./bootstrap
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
}
