#! /bin/sh

name=posixtest
skip_pkg_check=yes
version=0.0git
revision=1
git_url="https://codeberg.org/Ironclad/posixtest"
commit=4cf97b0d46c330edfb440ee2558bc8c49b4abe1a
source_imagedeps="git"
source_hostdeps="automake autoconf pkg-config"
source_allow_network="yes"
hostdeps="gcc autoconf automake pkg-config"
deps="core-libs"

prepare() {
    ./bootstrap
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
