#! /bin/sh

name=pv
version=1.10.5
revision=1
tarball_url="https://www.ivarch.com/s/pv-${version}.tar.gz"
tarball_blake2b="c23bb4780401c223e5ca8340f54e4f3f2acdd5bd1645ee02ae44ccd1f0a16290ad37a66743e080b44c69471b7f2f0790ad6190bba7fe43c1c5cc4844563551b7"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
    post_package_strip
}
