#! /bin/sh

name=python
repology_srcname=python
version=3.13.5
revision=1
tarball_url="https://www.python.org/ftp/python/${version}/Python-${version}.tar.xz"
tarball_blake2b="9caacad8745dcd238b208022cb140a6655ae57ae0b7f5ac88efc84a96635c310102a5de20cbaa43ef3c329f454b142a0a019141279d49a4d657be5682a1d6521"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 xz zlib openssl ncurses readline gdbm libexpat libffi"

prepare() {
    autotools_recursive_regen
}

configure() {
        ac_cv_file__dev_ptmx=yes \
        ac_cv_file__dev_ptc=yes \
        ac_cv_func_sched_setscheduler=no \
        ac_cv_buggy_getaddrinfo=no \
    autotools_configure \
        --build=$ARCHITECTURE \
        --with-computed-gotos \
        --disable-optimizations \
        --enable-ipv6 \
        --with-system-expat \
        --enable-loadable-sqlite-extensions \
        --without-ensurepip \
        --with-tzpath=${prefix}/share/zoneinfo \
        --with-build-python=python3 \
        --without-static-libpython
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    ln -sfv python3 "${dest_dir}${prefix}"/bin/python
    ln -sfv python3-config "${dest_dir}${prefix}"/bin/python-config
    ln -sfv pydoc3 "${dest_dir}${prefix}"/bin/pydoc
    ln -sfv idle3 "${dest_dir}${prefix}"/bin/idle

    post_package_strip
}
