#! /bin/sh

name=python
repology_srcname=python
_major_version=3.13
version=${_major_version}.9
revision=1
tarball_url="https://www.python.org/ftp/python/${version}/Python-${version}.tar.xz"
tarball_blake2b="8fbf9b9e0dcc480a5bac82d5c18d6fdb630769364c6963d40a86f222a5b77b2b596a743c771e710f4ada9c5dada5b65fcbf2fdf3601179ad7aea4fddb61fbadd"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 xz zlib openssl ncurses readline gdbm libexpat libffi"

prepare() {
    autotools_recursive_regen
}

configure() {
        ac_cv_file__dev_ptmx=yes \
        ac_cv_file__dev_ptc=yes \
        ac_cv_func_sched_setscheduler=no \
        ac_cv_buggy_getaddrinfo=no \
    autotools_configure \
        --build=${JINX_ARCH} \
        --with-computed-gotos \
        --disable-optimizations \
        --enable-ipv6 \
        --with-system-expat \
        --enable-loadable-sqlite-extensions \
        --without-ensurepip \
        --with-tzpath=${prefix}/share/zoneinfo \
        --with-build-python=python3 \
        --without-static-libpython
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    ln -sfv python3 "${dest_dir}${prefix}"/bin/python
    ln -sfv python3-config "${dest_dir}${prefix}"/bin/python-config
    ln -sfv pydoc3 "${dest_dir}${prefix}"/bin/pydoc
    ln -sfv idle3 "${dest_dir}${prefix}"/bin/idle

    mv "${dest_dir}${prefix}"/lib/python${_major_version} "${dest_dir}${prefix}"/lib/python3

    ln -sfv python3 "${dest_dir}${prefix}"/lib/python${_major_version}

    post_package_strip
}
