#! /bin/sh

name=python
version=3.13.2
revision=1
tarball_url="https://www.python.org/ftp/python/${version}/Python-${version}.tar.xz"
tarball_blake2b="79c7dff8a15fd2487d62847a8e654c02433a89887aa4f93819020b60a30587e3ba92b101553d971b59e132677f9f74dfc41cd7c7901db78a7787607ec96c6664"
source_hostdeps="autoconf automake libtool pkg-config"
source_deps="autoconf-archive"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs bzip2 xz zlib openssl ncurses readline gdbm libexpat libffi"

prepare() {
    autotools_recursive_regen
}

configure() {
        ac_cv_file__dev_ptmx=yes \
        ac_cv_file__dev_ptc=yes \
        ac_cv_func_sched_setscheduler=no \
        ac_cv_buggy_getaddrinfo=no \
    autotools_configure \
        --build=$ARCHITECTURE \
        --with-computed-gotos \
        --disable-optimizations \
        --enable-ipv6 \
        --with-system-expat \
        --enable-loadable-sqlite-extensions \
        --without-ensurepip \
        --with-tzpath=/usr/share/zoneinfo \
        --with-build-python=python3 \
        --without-static-libpython
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    ln -sfv python3 "${dest_dir}${prefix}"/bin/python
    ln -sfv python3-config "${dest_dir}${prefix}"/bin/python-config
    ln -sfv pydoc3 "${dest_dir}${prefix}"/bin/pydoc
    ln -sfv idle3 "${dest_dir}${prefix}"/bin/idle

    post_package_strip
}
