#! /bin/sh

name=qemu
version=10.1.2
revision=1
tarball_url="https://download.qemu.org/qemu-${version}.tar.xz"
tarball_blake2b="6e6e27c5de4f70f928a19ef64c00adbcb9723882db3eabd6acd7543f6b3d886db2862cf75ddcec86012c103d6927be464f03e2a3e91873b87cbbcafa0be95671"
imagedeps="build-essential python3-venv"
hostdeps="gcc pkg-config"
deps="core-libs libnvmm sdl2-compat gtk3 glib2 ncurses pixman libjpeg-turbo bzip2 zstd vte gnutls libtasn1"

early_prepare() {
    meson subprojects download
}

configure() {
    cp -rp "${source_dir}"/* ./

    NVMM_FLAG=""
    case "${JINX_ARCH}" in
        x86_64)
            NVMM_FLAG="--enable-nvmm"
            ;;
    esac

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    ./configure \
        -Db_colorout=always \
        --cross-prefix=${OS_TRIPLET}- \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-coroutine=sigaltstack \
        --disable-tpm \
        $NVMM_FLAG
}

build() {
    cd build

    meson compile -j${parallelism}
}

package() {
    cd build

    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
