#! /bin/sh

name=qemu
version=10.1.0
revision=1
tarball_url="https://download.qemu.org/qemu-${version}.tar.xz"
tarball_sha512="20552a524b6b298181df1af7084b470ded3fe8d1505f05011dda3c33cbc3d91f518ce026b44ba1a8b7f34c64ae81afddceda383066f4772a3a2a6333a2638caf"
imagedeps="build-essential python3-venv"
hostdeps="gcc pkg-config"
deps="core-libs libnvmm sdl2-compat gtk3 glib2 ncurses pixman libjpeg-turbo bzip2 zstd vte gnutls libtasn1"

early_prepare() {
    meson subprojects download
}

configure() {
    cp -rp "${source_dir}"/* ./

    NVMM_FLAG=""
    case "${JINX_ARCH}" in
        x86_64)
            NVMM_FLAG="--enable-nvmm"
            ;;
    esac

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    ./configure \
        -Db_colorout=always \
        --cross-prefix=${OS_TRIPLET}- \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-coroutine=sigaltstack \
        --disable-tpm \
        $NVMM_FLAG
}

build() {
    cd build

    meson compile -j${parallelism}
}

package() {
    cd build

    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
