#! /bin/sh

name=readline
_version=8.3
_patch=1
version=${_version}.${_patch}
revision=2
tarball_url="https://ftpmirror.gnu.org/gnu/readline/readline-${_version}.tar.gz"
tarball_blake2b="45d6fe7e34c56d309102a94aa776a7f5284201e844450e14ff818df9fa84a72154bdca70f11828c94954b080cbbe4666fa0b00ffa8460118ec8f3ea551b73dad"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

_get_patch() {
    TMP_PATCH=$(mktemp)
    curl -Lo "${TMP_PATCH}" https://ftpmirror.gnu.org/gnu/readline/readline-${_version}-patches/readline$(echo "${_version}" | sed 's/\.//g')-$1
    if ! b2sum "${TMP_PATCH}" | grep -q $2; then
        die "b2sum checksum fail for readline patch $1
        expected $2
        got      $(b2sum "${TMP_PATCH}")"
    fi
    patch -p0 <"${TMP_PATCH}"
}

early_prepare() {
    _get_patch 001 b0953458a18b8b06b0086567abd3c9ca3efceb5e4c38271e62137e126c106b938945d956394de0e955ecea5d48f8b261a4f2f3db2ee1d2cbc3b4cfdcf213ca46
}

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-multibyte \
        --with-curses
}

build() {
    make SHLIB_LIBS="-lncursesw -ltinfow" -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    install -Dm644 "${base_dir}"/build-support/readline/inputrc "${dest_dir}"/etc/inputrc

    post_package_strip
}
