#! /bin/sh

name=rsync
version=3.4.2
revision=1
tarball_url="https://www.samba.org/ftp/rsync/src/rsync-${version}.tar.gz"
tarball_blake2b="bfc8aa3dc3b75de5e81519eab6d505ebd4d05ebc79c3336ebc925486fa6267cd13a37844d0817183cec68215788bc07e4a281f716bcd0bc7d93daa995df9122c"
hostdeps="gcc pkg-config"
deps="core-libs lz4 openssl xxhash zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-included-zlib=no
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
