#! /bin/sh

name=screen
version=5.0.1
revision=1
tarball_url="https://ftp.gnu.org/gnu/screen/screen-5.0.1.tar.gz"
tarball_blake2b="ce8478718903ea4f9f7d5de2c77008cee304fef1065f3d564844844cb3ba7acb88bfe2cda051cecee0f034b19ea4e52a0fcc1549f9339eac33e7748ab59cd0f5"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./
    autotools_configure --disable-pam        \
            --enable-socket-dir=/run/screen \
            --with-pty-group=5              \
            --with-system_screenrc=/etc/screenrc
    sed -i -e "s%/usr/local/etc/screenrc%/etc/screenrc%" {etc,doc}/*
}

build() {
    make -j${parallelism} CFLAGS="-g3"
}

package() {
    make install DESTDIR="${dest_dir}"
    mkdir -pv ${dest_dir}/etc/
    install -Dm 644 etc/etcscreenrc ${dest_dir}/etc/
    post_package_strip
}
