#! /bin/sh

name=sdl2-compat
version=2.32.58
revision=1
git_url="https://github.com/libsdl-org/sdl2-compat.git"
commit=7c830290c6325190147abb7aedf39ef0e914d71a
hostdeps="gcc pkg-config"
deps="sdl3"

configure() {
    cmake_configure \
        -DSDL2COMPAT_STATIC=OFF \
        -DSDL2COMPAT_TEST_LIBRARY=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
