#! /bin/sh

name=sed
version=4.10
revision=1
tarball_url="https://ftp.gnu.org/gnu/sed/sed-${version}.tar.xz"
tarball_blake2b="6decea38a3e6eb3b672af2380ec3f32759b60350dba528d28a57b74806db33208baed69a8497d423bc7626105930e3e9c9ea68f68b8bcd4a3270f2d8922a2487"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
