#! /bin/sh

name=sent
version=0.2
revision=1
tarball_url="https://dl.suckless.org/tools/sent-${version}.tar.gz"
tarball_blake2b="0641cf856450af5a451b5b122feaddc884512ad5e068f04121a740be057c2ebc215651d971a9f01f3387327074e300417c4a3c00756c093290a4be54ccb29365"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libx11 libxft freetype2"

build() {
    cp -rp ${source_dir}/. ./

    make \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="$TARGET_CFLAGS $(${OS_TRIPLET}-pkg-config --cflags freetype2)" \
        LDFLAGS="$TARGET_LDFLAGS $(${OS_TRIPLET}-pkg-config --libs freetype2 xft fontconfig x11 libpng)"
}

package() {
    DESTDIR="${dest_dir}" PREFIX="/usr/" make install
    post_package_strip
}
