#! /bin/sh

name=shadow
version=4.19.2
revision=4
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.gz"
tarball_blake2b="4b8ad78f51ce1dabc6d4511ac72e4cabf4ae2f37124998cca9a60e3889434ff6b71356e2d5886810cdc6408c1407f56eb9ef4a3e7daf880bc05bddf58a6c16d1"
hostdeps="gcc pkg-config"
deps="core-libs libbsd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-logind
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # I cannot get it to not install in sbin so we bring out the jackhammer.
    mv "${dest_dir}"/usr/sbin/* "${dest_dir}"/usr/bin/
    rm -rf "${dest_dir}"/usr/sbin

    post_package_strip
}
