#! /bin/sh

name=shadow
version=4.19.3
revision=1
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.gz"
tarball_blake2b="d84660a432ef0f6d1edea80dce0f1d3365b2383f48b54004cfa250c19c29d4bf169178bec7d459df3049e4f59700294e2cc9557cc52cf51f3fa0c51683781148"
hostdeps="gcc pkg-config"
deps="core-libs libbsd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-logind
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # I cannot get it to not install in sbin so we bring out the jackhammer.
    mv "${dest_dir}"/usr/sbin/* "${dest_dir}"/usr/bin/
    rm -rf "${dest_dir}"/usr/sbin

    post_package_strip
}
