#! /bin/sh

name=shared-mime-info
version=2.4
revision=1
tarball_url="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${version}/shared-mime-info-${version}.tar.gz"
tarball_blake2b="a018148bdb7570c4d6a5851186032c5c2aa127cb48ace9e085e6e7f8f64bb8ce5c930a6a24816b2917e7e5e776ffbc9bae1052b62a317ce0cc828d7ab08b53a5"
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libxml2"

configure() {
    meson_configure \
        -Dupdate-mimedb=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
