#! /bin/sh

name=sharutils
version=4.15.2
revision=1
tarball_url="https://ftp.gnu.org/gnu/sharutils/sharutils-${version}.tar.xz"
tarball_blake2b="e2acae027679ebdf723ecae6f243608f501f5c24685a19223dd27580ccf76bc7d38905a9d202b30cf2633e5580d727821398f1162b170233f03c17f3da683917"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
        CFLAGS="$TARGET_CFLAGS -fcommon" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    autotools_configure_noflags
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
