#! /bin/sh

name=simdutf
version=8.1.0
revision=1
git_url="https://github.com/simdutf/simdutf.git"
commit=24a06103ab5cc2235df9b8f07c77e07e440f0e12
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
