#! /bin/sh

name=simdutf
version=8.2.0
revision=1
git_url="https://github.com/simdutf/simdutf.git"
commit=fd476229424b40ae71a58dd5a205795c3d76b5f1
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
