#! /bin/sh

name=simdutf
version=7.7.1
revision=1
git_url="https://github.com/simdutf/simdutf.git"
commit=98218fc47232b57dda64191b0204c25c09984f03
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
