#! /bin/sh

name=sl
version=5.05
revision=1
tarball_url="https://github.com/eyJhb/sl/archive/refs/tags/${version}.tar.gz"
tarball_blake2b=91c8a428995733324c820412a027b61bc8dde35d875fc82ac96d5810d7fe267f817fdd57a94480f4277351d821cab93b959c0d28d39282407289f643c8e7a6e2
hostdeps="gcc"
deps="core-libs ncurses"

build() {
    cp -rp "${source_dir}"/. ./
    make \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="$TARGET_CFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
        -j${parallelism}
}

package() {
    mkdir -pv "${dest_dir}${prefix}"/bin/
    install -Dm 775 sl "${dest_dir}${prefix}"/bin/
    post_package_strip
}
