#! /bin/sh

name=slim
repology_id=slim-login-manager
version=1.4.0
revision=2
tarball_url="https://downloads.sourceforge.net/project/slim-fork/slim-${version}.tar.gz"
tarball_blake2b="507f22d09a3449b870bb5fd5a5f0ab1002ceee5372c82f702582809a5fc442088c17d79fedff6712e198cee672696388479604a194e5729c7bc12139770c833d"
hostdeps="gcc pkg-config"
deps="core-libs libjpeg-turbo libpng libx11 libxext libxft libxmu libxrandr fontconfig xorg-xauth"

configure() {
    cmake_configure \
        -DUSE_CONSOLEKIT=OFF \
        -DUSE_PAM=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    cp -v "${base_dir}"/build-support/slim/slim.conf "${dest_dir}"/etc/

    post_package_strip
}
