#! /bin/sh

name=sqlite
version=3.50.0
revision=1
tarball_url="https://sqlite.org/2025/sqlite-autoconf-3500000.tar.gz"
tarball_blake2b="11d904d09030a1f8641fa322100c65adff1ac9b1363003d953cc2ad1c79d6dd02cf3d4a02710808ca2f0e5a04cbb10e5df814a180d133804ccd7cc47a57c0182"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs readline zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    "${source_dir}/configure" \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --soname=legacy \
        --disable-static \
        --enable-shared \
        --enable-fts4 \
        --enable-fts5 \
        --enable-readline \
        --with-readline-header=${sysroot_dir}${prefix}/include/readline/readline.h \
        CFLAGS="$TARGET_CFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_SECURE_DELETE=1" \
        LDFLAGS="$TARGET_LDFLAGS"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
