#! /bin/sh

name=sqlite
version=3.49.2
revision=1
tarball_url="https://sqlite.org/2025/sqlite-autoconf-3490200.tar.gz"
tarball_blake2b="588e881e986c618d7321546a5b236fe68371898295d80ff54f8d7037e5ae28d5384808f85e395e3467aa3494f84234709a1e9310277d6f0866e4c750f04c2fbb"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs readline zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    "${source_dir}/configure" \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --soname=legacy \
        --disable-static \
        --enable-shared \
        --enable-fts4 \
        --enable-fts5 \
        --enable-readline \
        --with-readline-header=${sysroot_dir}${prefix}/include/readline/readline.h \
        CFLAGS="$TARGET_CFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_SECURE_DELETE=1" \
        LDFLAGS="$TARGET_LDFLAGS"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
