#! /bin/sh

name=texinfo
version=7.1.1
revision=1
tarball_url="https://ftp.gnu.org/pub/gnu/texinfo/texinfo-${version}.tar.xz"
tarball_blake2b="64dbd315e65d5b7cb0bb06c918e9924bb15a25a4bb26322db10b7ee98e9e6626b62592f8edd0ff016256f4a84837dabacb5278c3826e34fa3e080a5e8c0fb626"
source_imagedeps="build-essential"
source_hostdeps="automake autoconf libtool pkg-config"
imagedeps="build-essential help2man"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs ncurses bash gzip"

prepare() {
    autotools_recursive_regen

    ./configure \
        CFLAGS="$HOST_CFLAGS" \
        CPPFLAGS="$HOST_CPPFLAGS" \
        LDFLAGS="$HOST_LDFLAGS"

    make -j${parallelism}
    make -C info makedoc
}

configure() {
    cp -rp "${source_dir}"/. ./

        texinfo_cv_sys_iconv_converts_euc_cn=y \
        configure_script_path=./configure \
    autotools_configure \
        --disable-perl-xs

    mkdir -p tools/info
    cp -v "${source_dir}"/info/makedoc tools/info/
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
