#! /bin/sh

name=tree
repology_id=tree-steve-baker
version=2.3.1
revision=1
tarball_url="https://gitlab.com/OldManProgrammer/unix-tree/-/archive/${version}/unix-tree-${version}.tar.gz"
tarball_blake2b="735de5546b8d50fb1fadbff573768632d9bf9cda924f1d82634493a365cec25411d6fcd726aa620d7ac24a7b89c989e2144582daa75542fed6e661670f7b41a9"
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        -j${parallelism}
}

package() {
    make PREFIX="${dest_dir}${prefix}" install

    post_package_strip
}
