#! /bin/sh

name=ttf-liberation
version=2.1.5
revision=1
tarball_url="https://github.com/liberationfonts/liberation-fonts/files/7261482/liberation-fonts-ttf-${version}.tar.gz"
tarball_blake2b="d8614907887f20967fc7c75cb33b636a0eb5c682a076ccc7aef09f4ac243507afc005ef90d0b2aeee6a4a6a1ff3d5ce4fac0d1722a382525b3883ef53cdec26a"
deps="core-libs"

build() {
    cp -r ${source_dir}/. ./
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/fonts/truetype"
    cp -r * "${dest_dir}${prefix}/share/fonts/truetype/"
}
