#! /bin/sh

name=util-ironclad
skip_pkg_check=yes
version=c3c4449f8d6f1b3411be2dbaa58fefdad90f67a9
revision=1
git_url="https://codeberg.org/Ironclad/util-ironclad"
commit=${version}
source_hostdeps="automake autoconf libtool pkg-config"
source_imagedeps="git"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libxcrypt"

prepare() {
    ./bootstrap
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
