#! /bin/sh

name=vim
version=9.0.1908
revision=1
tarball_url="https://github.com/vim/vim/archive/refs/tags/v${version}.tar.gz"
tarball_sha512=020cd2a8482603f01f77eb6b23c2321911dc80b943b68823a300a5eae3dc58c418f3fcf514c69a756e22a0a9ed1aa98ad20baa70ba1e92c5747c713947b98a49
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

configure() {
	cp -rp ${source_dir}/* .

	vim_cv_toupper_broken="no" \
	ac_cv_small_wchar_t="no" \
	ac_cv_func_sigsetjmp="no" \
	vim_cv_terminfo="yes" \
	vim_cv_tgetent="zero" \
	vim_cv_tty_group="" \
	vim_cv_tty_mode="0620" \
	vim_cv_getcwd_broken="no" \
	vim_cv_timer_create="no" \
	vim_cv_timer_create_with_lrt="no" \
	vim_cv_stat_ignores_slash="no" \
	vim_cv_memmove_handles_overlap="yes" \
	vim_cv_bcopy_handles_overlap="yes" \
	vim_cv_memcpy_handles_overlap="yes" \
    autotools_configure \
        --with-tlib=tinfo \
        --with-features=huge \
        --with-wayland=no \
        --enable-gpm \
        --enable-acl \
        --with-x=no \
        --disable-gui \
        --enable-multibyte \
        --enable-cscope \
        --enable-netbeans \
        --enable-perlinterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-rubyinterp=dynamic \
        --enable-luainterp=dynamic \
        --enable-tclinterp=dynamic \
        --disable-canberra

}

build() {
	make -j ${parallelism}
}

package() {
	make install DESTDIR=${dest_dir} STRIP=/bin/true
    ln -sfv vim "${dest_dir}${prefix}"/bin/vi

    post_package_strip
}
