#! /bin/sh

name=vim
version=9.1.2077
revision=1
tarball_url="https://github.com/vim/vim/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="f970fd08f3cde13dc16668c9190fd1b840a7e8e5677dab46a5c49fe0e982cfc74a7884458f9f134e2c3fc6c33c2cbb0c71bec41ddb6e04b75c69defa7ec286c7"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

configure() {
    cp -rp ${source_dir}/* .

        vim_cv_toupper_broken="no" \
        ac_cv_small_wchar_t="no" \
        ac_cv_func_sigsetjmp="no" \
        vim_cv_terminfo="yes" \
        vim_cv_tgetent="zero" \
        vim_cv_tty_group="" \
        vim_cv_tty_mode="0620" \
        vim_cv_getcwd_broken="no" \
        vim_cv_timer_create="no" \
        vim_cv_timer_create_with_lrt="no" \
        vim_cv_stat_ignores_slash="no" \
        vim_cv_memmove_handles_overlap="yes" \
        vim_cv_bcopy_handles_overlap="yes" \
        vim_cv_memcpy_handles_overlap="yes" \
    autotools_configure \
        --with-tlib=tinfo \
        --with-features=huge \
        --with-wayland=no \
        --enable-gpm \
        --enable-acl \
        --with-x=no \
        --disable-gui \
        --enable-multibyte \
        --enable-cscope \
        --enable-netbeans \
        --enable-perlinterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-rubyinterp=dynamic \
        --enable-luainterp=dynamic \
        --enable-tclinterp=dynamic \
        --disable-canberra

}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR=${dest_dir} STRIP=/bin/true
    ln -sfv vim "${dest_dir}${prefix}"/bin/vi

    post_package_strip
}
