#! /bin/sh

name=vim
version=9.2.0437
revision=1
tarball_url="https://github.com/vim/vim/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="d7000460cc9b950c3d044c18da617ecd7cec202b8befd36b4f19ac83cfb21b43a8705b44dd60266c575bdbac548df9e63add9fd8793d66e9ab9226680b982abe"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

configure() {
    cp -rp ${source_dir}/* .

        vim_cv_toupper_broken="no" \
        ac_cv_small_wchar_t="no" \
        ac_cv_func_sigsetjmp="no" \
        vim_cv_terminfo="yes" \
        vim_cv_tgetent="zero" \
        vim_cv_tty_group="" \
        vim_cv_tty_mode="0620" \
        vim_cv_getcwd_broken="no" \
        vim_cv_timer_create="no" \
        vim_cv_timer_create_with_lrt="no" \
        vim_cv_stat_ignores_slash="no" \
        vim_cv_memmove_handles_overlap="yes" \
        vim_cv_bcopy_handles_overlap="yes" \
        vim_cv_memcpy_handles_overlap="yes" \
    autotools_configure \
        --with-tlib=tinfo \
        --with-features=huge \
        --with-wayland=no \
        --enable-gpm \
        --enable-acl \
        --with-x=no \
        --disable-gui \
        --enable-multibyte \
        --enable-cscope \
        --enable-netbeans \
        --enable-perlinterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-rubyinterp=dynamic \
        --enable-luainterp=dynamic \
        --enable-tclinterp=dynamic \
        --disable-canberra

}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR=${dest_dir} STRIP=/bin/true
    ln -sfv vim "${dest_dir}${prefix}"/bin/vi

    post_package_strip
}
