#! /bin/sh

name=xbps
version=0.60.5
revision=3
tarball_url="https://github.com/void-linux/xbps/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="91aad926f25e78c17b2646f2e478e9a4141d9d80ebb93bc821c91333c8f5b5cf72a08edb7f25aef486e0761f15da8322207474c3b6f546d6403dd424cc442525"
hostdeps="gcc pkg-config"
deps="core-libs libarchive openssl zlib"

configure() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="$TARGET_CFLAGS -Wno-error" \
        CPPFLAGS="$TARGET_CPPFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ./configure \
        --verbose \
        --host=${OS_TRIPLET} \
        --prefix="${prefix}" \
        --sysconfdir=/etc
}

build() {
    make -j${parallelism} \
        AR="${OS_TRIPLET}-ar" \
        RANLIB="${OS_TRIPLET}-ranlib"
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove static libraries
    rm "${dest_dir}${prefix}"/lib/*.a

    # Change architecture for the main repository as needed.
    sed -i "s/ARCH_HERE/${JINX_ARCH}/g" "${dest_dir}${prefix}"/share/xbps.d/00-repository-main.conf

    post_package_strip
}
