#! /bin/sh

name=xdg-user-dirs
version=0.19
revision=2
git_url="https://gitlab.freedesktop.org/xdg/xdg-user-dirs.git"
commit=0577968675b9d7d660b3715cf6b2e00c6d491d67
#imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
