#! /bin/sh

name=xfe
version=1.46.2
revision=1
tarball_url="https://downloads.sourceforge.net/sourceforge/xfe/xfe-${version}.tar.xz"
tarball_blake2b="0c4a49aaf1ff04d25a13349fa81be9d3e8400009c7d8c24f96a017850a156b116950e0ac5d471190defeceb236e0ed82a614a143a0cdddf10dd86a9b9c318cca"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs fox freetype2 xcb-util libxft"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

        configure_script_path=./configure \
    autotools_configure \
       --with-x
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
