#! /bin/sh

name=xfishtank
repology_id=xfishtank
version=3.2.3
revision=1
tarball_url="https://ratrabbit.nl/downloads/xfishtank/xfishtank-${version}.tar.gz"
tarball_sha512=297add843e8dab748f272f7630446f4b19d26280577199be61708812e0ed4c0af7e306873c49093d36b97329f05c55651213d106fac43932719d99cee29eb295
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxext libxpm libxinerama libxkbcommon libxtst gtk3"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make AR="${OS_TRIPLET}-ar" -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
