#! /bin/sh

name=xfishtank
version=2.5
revision=2
git_url="https://github.com/sydneyjd/xfishtank.git"
commit=098f67f39319067fc031fc1dbcba2c19a0320468
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxext libxpm libxinerama libxkbcommon libxtst imlib2"

build() {
    # the build system sucks, so we will directly call the compiler and ignore it!
    cp -rp "${source_dir}"/. ./

    set -x

    gcc ${HOST_CFLAGS} -std=gnu89 ${HOST_LDFLAGS} makeh.c -o makeh
    ./makeh > xfishy.h

    "${OS_TRIPLET}"-gcc ${TARGET_CFLAGS} -ansi -Dlinux -I./fishmaps ${TARGET_LDFLAGS} xfish.c medcut.c -lX11 -lImlib2 -lm -o xfishtank

    set +x
}

package() {
    install -D xfishtank "${dest_dir}/usr/bin/xfishtank"

    post_package_strip
}
