#! /bin/sh

name=xfishtank
repology_id=xfishtank
version=0.0git
revision=1
git_url="https://github.com/sydneyjd/xfishtank.git"
commit=63022c8877710cefa7e4815dda8bd6ae50557fb5
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxext libxpm libxinerama libxkbcommon libxtst imlib2"

build() {
	# the build system sucks, so we will directly call the compiler and ignore it!
	cp -rp ${source_dir}/* .

	gcc makeh.c -o makeh

	./makeh fishmaps/?*.h > xfishy.h
	"${OS_TRIPLET}"-gcc -ansi -Dlinux -I./fishmaps -lX11 -lImlib2 -lm xfish.c medcut.c -o xfishtank
}

package() {
	mkdir -p ${dest_dir}/usr/bin/
	cp -v xfishtank ${dest_dir}/usr/bin/xfishtank
    post_package_strip
}
