#! /bin/sh

name=xkeyboard-config
version=2.45
revision=1
git_url="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
commit=a8b1be93168cbd3246359c724f090e821079b313
hostdeps="gcc pkg-config"
deps="core-libs xorg-xkbcomp"

configure() {
    meson_configure \
        -Dxorg-rules-symlinks=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
