#! /bin/sh

name=xorg-xeyes
repology_id=xeyes
version=1.3.1
revision=1
git_url="https://gitlab.freedesktop.org/xorg/app/xeyes.git"
commit=7dc4f720f57471d2eccefd87cdca54494cf75eb5
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libxext libxmu libxrender libxi libxcb"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
