#! /bin/sh

name=xorg-server
version=21.1.18
revision=1
tarball_url="https://www.x.org/releases/individual/xserver/xorg-server-${version}.tar.xz"
tarball_blake2b="48c7b745c07a31d11d3a95f8eba056ff46bf69f2c70d499f677cbd706347e0c3c28a8197be5c0d65670c5b2f87f559ea10e7c21ee88bdc767c6a921d5fa8d3b2"
hostdeps="gcc pkg-config"
deps="core-libs xorg-util-macros xorg-proto xcb-proto xtrans libxinerama libxcvt libxshmfence libx11 libxaw libxxf86vm libxkbfile libxmu libxfont2 libepoxy libxi libxv libxdamage libxrender libxrandr libxcb libxfixes libxext nettle xorg-xkbcomp xkeyboard-config pixman"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS -Wno-error=array-bounds" \
        --with-xkb-bin-directory=/usr/bin \
        --with-xkb-path=/usr/share/X11/xkb \
        --with-xkb-output=/var/lib/xkb \
        --with-fontrootdir=/usr/share/fonts/X11 \
        --enable-xorg \
        --enable-xv \
        --enable-xvfb \
        --disable-xephyr \
        --disable-xnest \
        --disable-suid-wrapper \
        --disable-pciaccess \
        --disable-dpms \
        --enable-screensaver \
        --disable-xres \
        --disable-xvmc \
        --disable-systemd-logind \
        --disable-secure-rpc \
        --disable-config-udev \
        --disable-dri \
        --disable-dri2 \
        --disable-dri3 \
        --disable-int10-module \
        --disable-vgahw \
        --disable-libdrm \
        --disable-glamor \
        --disable-glx
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc/X11
    cp -v "${base_dir}"/build-support/xorg-server/xorg.conf "${dest_dir}"/etc/X11/

    post_package_strip
}
