#! /bin/sh

name=xterm
version=395
revision=1
tarball_url="https://invisible-mirror.net/archives/xterm/xterm-${version}.tgz"
tarball_blake2b="8183da30b491a0e43c34e2728586816e733a18aa8bf87d0ec60b43d47d625bc07395886b02afe08260cc527bc3efa67d04cb060254f0b9ffb7e5ff29b187f42f"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libxft libxaw ncurses xbitmaps libxkbfile"

prepare() {
    cp -v /usr/local/share/autoconf/build-aux/{config.guess,config.sub,install-sh} ./
}

configure() {
        LIBS="-ltinfow" \
    autotools_configure \
        --disable-tcap-fkeys \
        --disable-tcap-query \
        --enable-256-color
}

build() {
    make -j${parallelism}
}

package() {
    make DESTDIR="${dest_dir}" install

    post_package_strip
}
