#! /bin/sh

name=xterm
version=397
revision=1
tarball_url="https://invisible-mirror.net/archives/xterm/xterm-${version}.tgz"
tarball_blake2b="cce4054e83edb9b4203b53a34f7415d038202a10cb997d0c0fe53bb985399bd16626f3e2c5cfdfa8d9eea31d697e532fc858c74c0ba0649936814d5c91825c76"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libxft libxaw ncurses xbitmaps libxkbfile"

prepare() {
    cp -v /usr/local/share/autoconf/build-aux/{config.guess,config.sub,install-sh} ./
}

configure() {
        LIBS="-ltinfow" \
    autotools_configure \
        --disable-tcap-fkeys \
        --disable-tcap-query \
        --enable-256-color
}

build() {
    make -j${parallelism}
}

package() {
    make DESTDIR="${dest_dir}" install

    post_package_strip
}
