#! /bin/sh

name=xxhash
version=0.8.2
revision=1
tarball_url="https://github.com/Cyan4973/xxHash/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="735408256240760778fa516e01bed428f04837eb4e059c512e924f13e4a96db6cacbbefb04dea65a37b0f25b52cf13c4927a6e7870dc8c0d45b1b955d4ba3da1"
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

        CC="${OS_TRIPLET}-gcc" \
        AR="${OS_TRIPLET}-ar" \
        CFLAGS="${TARGET_CFLAGS}" \
        CXXFLAGS="${TARGET_CXXFLAGS}" \
        CPPFLAGS="${TARGET_CPPFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install

    rm -fv "${dest_dir}${prefix}"/lib/libxxhash.a

    post_package_strip
}
