#! /bin/sh

version=1.57.1
revision=1
tarball_url="https://gitlab.gnome.org/GNOME/pango/-/archive/${version}/pango-${version}.tar.gz"
tarball_blake2b="0901b2b237b235d6aa2e9581544d54f52ca90c479660dc78723bf23612f40097420616ae3c9de43340d3bd451cbe39a34d09946af127956a3c232575bdb8b579"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 fontconfig freetype2 fribidi cairo libx11 harfbuzz libxft"

configure() {
    meson_configure \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
