#! /bin/sh

imagedeps="$imagedeps gnat-14"

ada_symlink_gnat_14() {
    TMPPATH="$(mktemp -d)"

    export PATH="$TMPPATH:$PATH"

    for i in gnat gnatbind gnatchop gnatclean gnathtml gnatkr gnatlink gnatls gnatmake gnatname gnatprep; do
        ln -s /usr/bin/$i-14 "$TMPPATH/$i"
    done
}
