#! /bin/sh

imagedeps="$imagedeps gnat-16"

ada_symlink_gnat() {
    TMPPATH="$(mktemp -d)"

    export PATH="$TMPPATH:$PATH"

    for i in gnat gnatbind gnatchop gnatclean gnathtml gnatkr gnatlink gnatls gnatmake gnatname gnatprep; do
        ln -s /usr/bin/$i-16 "$TMPPATH/$i"
    done
}
