#! /bin/sh

version=1.13.2
revision=4
git_url="https://github.com/dunst-project/dunst.git"
commit=312ed56fbcdc84823c99f21008467561394a8eb1
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libxext libxmu libxrender libxi libxcb dbus pango gdk-pixbuf libxscrnsaver libxinerama libnotify"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
