#! /bin/sh

version=1.13.2
revision=8
git_url="https://github.com/dunst-project/dunst.git"
commit=312ed56fbcdc84823c99f21008467561394a8eb1
hostdeps="gcc pkg-config"
deps="core-libs cairo glib2 pango gdk-pixbuf libx11 libxext libxinerama libxrandr libxscrnsaver libnotify dbus"
conf_files="/etc/xdg/dunst/dunstrc"

configure() {
    meson_configure \
        -Dwayland=disabled \
        -Dsystemd=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
