#! /bin/sh

version=2.18.3
revision=2
git_url="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
commit=0f236723a3c26bd9745e32ba2b3ee21e5f809295
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libexpat libxml2"

configure() {
    meson_configure \
        -Dxml-backend=libxml2 \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
    post_package_strip
}
