#! /bin/sh

version=2.18.2
revision=1
git_url="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
commit=a4e25ec391d417e4bca052fbfa5cd7ce5f7fd39e
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libexpat libxml2"

configure() {
    meson_configure \
        -Dxml-backend=libxml2 \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
    post_package_strip
}
