#! /bin/sh

version=2.90.0
revision=1
tarball_url="https://download.gnome.org/sources/glib-networking/2.90/glib-networking-${version}.tar.xz"
tarball_blake2b="992b2b5015fab9b7e86ab830a30691b8b096cc235f5eb231e3b8c81e2e7281e24d9e2390b98cada5d1a9cca5857eee63530f4e4230083da56a1fac821a32ebee"
imagedeps="libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs gsettings-desktop-schemas glib2 gnutls libproxy"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    install_hook_add 'gio-querymodules /usr/lib/gio/modules/ >/dev/null'
}
