#! /bin/sh

version=1.28.3
revision=1
tarball_url="https://github.com/mate-desktop/mate-utils/releases/download/v${version}/mate-utils-${version}.tar.xz"
tarball_blake2b="fbbbbac24c9a77f49572790385db91ac021ad626a7d945327a1214632eb8e3ffdcac3c64cb8f8b7bc877adf57a507c12f0013754571f0fbc780db770c97f723e"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo gdk-pixbuf glib2 gtk3 libcanberra libgtop libice libsm libx11 libxext mate-desktop mate-panel pango zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-disk_image_mounter
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    sed -i 's|/base_dir/sources/mate-utils/||g' \
        "${dest_dir}${prefix}"/include/mate-dict/gdict/gdict-enum-types.h

    post_package_strip

    generate_glib_schemas_hook
}
