#! /bin/sh

version=1.28.3
revision=8
git_url="https://github.com/mate-desktop/atril.git"
commit=64bcc359e333135e72af2cc410373d8523b73c09
imagedeps="libglib2.0-dev-bin itstool libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core poppler glib2 libxml2 mate-desktop zlib gdk-pixbuf gtk3 libice libsm libx11 cairo pango caja libtiff libarchive"

early_prepare() {
    # Fix revision of mate-submodules
    sed -i 's/^revision=.*/revision = 4074560e3642a53ace07b31baaf3f04c060dcd0b/g' subprojects/mate-submodules.wrap

    meson subprojects download
}

configure() {
    meson_configure \
        -Dcomics=enabled \
        -Ddjvu=disabled \
        -Ddvi=disabled \
        -Dt1lib=disabled \
        -Depub=disabled \
        -Dpdf=enabled \
        -Dpixbuf=enabled \
        -Dps=disabled \
        -Dtiff=enabled \
        -Dxps=disabled \
        -Dkeyring=false \
        -Dpreviewer=true \
        -Dthumbnailer=true \
        -Dintrospection=false \
        -Denable_dbus=true \
        -Denable_debug=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
    generate_glib_schemas_hook
}
