#! /bin/sh

version=1.28.7
revision=1
tarball_url="https://github.com/mate-desktop/atril/releases/download/v${version}/atril-${version}.tar.xz"
tarball_blake2b="da2dfad5794a3ead4a23762135cc8e23e008c61baab22815f39e1dd489562fa1ced76fe127c648df9cb5480169a87f466cc522d96f1eaff4b9221d211cdb4d6e"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core poppler glib2 libxml2 mate-desktop zlib gdk-pixbuf gtk3 libice libsm libx11 cairo pango caja libtiff libarchive"

early_prepare() {
    # Fix revision of mate-submodules
    sed -i 's/^revision=.*/revision = 4074560e3642a53ace07b31baaf3f04c060dcd0b/g' subprojects/mate-submodules.wrap

    meson subprojects download
}

configure() {
    meson_configure \
        -Dcomics=enabled \
        -Ddjvu=disabled \
        -Ddvi=disabled \
        -Dt1lib=disabled \
        -Depub=disabled \
        -Dpdf=enabled \
        -Dpixbuf=enabled \
        -Dps=disabled \
        -Dtiff=enabled \
        -Dxps=disabled \
        -Dkeyring=false \
        -Dpreviewer=true \
        -Dthumbnailer=true \
        -Dintrospection=false \
        -Denable_dbus=true \
        -Denable_debug=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    sed -i 's|/build_dir/builds/atril/\.\./\.\./\.\./base_dir/sources/atril/||g' \
        "${dest_dir}${prefix}"/include/atril/*/libdocument/ev-document-type-builtins.h \
        "${dest_dir}${prefix}"/include/atril/*/libview/ev-view-type-builtins.h

    post_package_strip

    generate_glib_schemas_hook
}
