#! /bin/sh

version=1.6.0
revision=9
tarball_url="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${version}.tar.gz"
tarball_blake2b="cbdfa8616edce14bf3f8621d9d0d925884d0f40e8775c7d8810575c8bec88f10ed912029cc0a4bccf9bb9eb98824e4b1a89ec61ee53d7ef20a150450d8513168"
hostdeps="gcc pkg-config"
deps="core-libs giflib libjpeg-turbo libpng freeglut mesa libtiff-bootstrap"
binpkgdeps="libtiff"

configure() {
    cmake_configure \
        -DWEBP_BUILD_EXTRAS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
