#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/host-recipes/gcc/recipe" && echo ${version})"
revision=1
hostdeps="gcc pkg-config"
imagedeps="build-essential"
deps="glibc libgcc"

. "${base_dir}"/build-support/gcc-ada-helpers

package() {
    ada_symlink_gnat

    cd "${build_dir}"/host-builds/gcc/build

    rm -rf tmp_libstdc++_dir
    mkdir tmp_libstdc++_dir

    DESTDIR="$(realpath tmp_libstdc++_dir)" make install-target-libstdc++-v3

    # For some reason this also installs libgcc even though it shouldn't...
    # Remove it.
    rm -fv tmp_libstdc++_dir/usr/local/${OS_TRIPLET}/lib/libgcc*

    mkdir -p "${dest_dir}${prefix}"

    cp -r tmp_libstdc++_dir/usr/local/share "${dest_dir}${prefix}"/
    cp -r tmp_libstdc++_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
