#! /bin/sh

version=1.3.15
revision=2
tarball_url="https://github.com/silnrsi/graphite/releases/download/${version}/graphite2-${version}.tgz"
tarball_blake2b="61edefe1afcae05fc30f576d8b2817496d2a7702011398d3bac3044475573f20fa5d2e1ea138fca004dfe48852955f6240458bcef5e285d38d30bf9ffdb428ad"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure -DCMAKE_POLICY_VERSION_MINIMUM=3.5
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
