#! /bin/sh

repology_id=nghttp2
version=1.70.0
revision=5
tarball_url="https://github.com/nghttp2/nghttp2/releases/download/v${version}/nghttp2-${version}.tar.xz"
tarball_blake2b="3ecc4170b86dc45cfc33e78caa3eb3d7efa9ef35b4494f5c14e6a71b8dfee6ac47144cafc1e7a2962c8836d95d4f6553467600e6af44d64642c7d998a3582b10"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DENABLE_LIB_ONLY=ON \
        -DENABLE_DOC=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
