#! /bin/sh

version=1.0.10
revision=3
tarball_url="https://downloads.sourceforge.net/project/gptfdisk/gptfdisk/${version}/gptfdisk-${version}.tar.gz"
tarball_blake2b="9047bf68a2c5c254bda9b2815488963dc19a9415c90fbf4a127268a37fe8a545b7d45a333e356bd9da22e37ef649d9f60896ffedfdc35b60c7642a48e4ed2e5a"
hostdeps="gcc pkg-config"
deps="core-libs popt ncurses e2fsprogs"

build() {
    cp -rp "${source_dir}"/. ./

        CXXFLAGS="${TARGET_CXXFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        CXX=${OS_TRIPLET}-g++ \
        DETECTED_OS=Ironclad \
        TARGET=ironclad \
        -j${parallelism}
}

package() {
    install -d "${dest_dir}${prefix}"/bin
    install -t "${dest_dir}${prefix}"/bin cgdisk gdisk sgdisk fixparts

    install -d "${dest_dir}${prefix}"/share/man/man8
    install -m644 -t "${dest_dir}${prefix}"/share/man/man8 \
        cgdisk.8 gdisk.8 sgdisk.8 fixparts.8

    post_package_strip
}
