#! /bin/sh

repology_id=gtk
repology_srcname=gtk3
version=3.24.52
revision=10
tarball_url="https://download.gnome.org/sources/gtk/3.24/gtk-${version}.tar.xz"
tarball_blake2b="55085be4ca67b116099bd3bb277d6671b77246098ae6c3d2195f860304b4df72423237c26c12adf19a57272adfeac7d1e1178e27089c1fb342dea21809287283"
imagedeps="python3-packaging libglib2.0-dev-bin libglib2.0-bin libgdk-pixbuf2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo glib2 gdk-pixbuf librsvg libx11 libxext libxinerama libxrender libxrandr libxfixes libxdamage pango fribidi libepoxy libxkbcommon fontconfig freetype2 libxi harfbuzz libxcursor hicolor-icon-theme"
conf_files="/etc/gtk-3.0/im-multipress.conf"

configure() {
    meson_configure \
        -Dtests=false \
        -Dman=true \
        -Dtracker=false \
        -Dprint_backends=file \
        -Dintrospection=false \
        -Dx11_backend=true \
        -Dbroadway_backend=true \
        -Dwayland_backend=false \
        -Dcolord=no
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    generate_glib_schemas_hook
    install_hook_add 'gtk-query-immodules-3.0 --update-cache >/dev/null'
}
