#! /bin/sh

version=2.18.0
revision=4
tarball_url="https://github.com/scop/bash-completion/releases/download/${version}/bash-completion-${version}.tar.xz"
tarball_blake2b="e1e9db61441ff77cf0799f61408d634dba589347f0a1cb91dcce119bd4c313ee042ef8756a69d057d93672a6518e21fbb6a8ed90935b6f288486fc3522531112"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
