#! /bin/sh

version=51.0
revision=1
tarball_url="https://download.gnome.org/sources/adwaita-icon-theme/51/adwaita-icon-theme-${version}.tar.xz"
tarball_blake2b="86e5614c1582b25160a092195f91870223b51f704dba80a5286e70bc209d6d4c55385c4e58a10d8fcd78706869100e4ee31711043db9b7bc8e6b20aa89bb5fc2"
imagedeps="gtk-update-icon-cache"
hostdeps="gcc pkg-config"
deps="core-libs hicolor-icon-theme"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
