#! /bin/sh

skip_pkg_check=yes
version=0.0
revision=27
source_dir="base-files"
deps="core-libs"
conf_files="/etc/group /etc/locale.conf /etc/locale.gen /etc/nsswitch.conf /etc/passwd"
conf_files="${conf_files} /etc/profile /etc/resolv.conf /etc/shadow"
conf_files="${conf_files} /home/user/.bash_profile /home/user/.bashrc"

package() {
    cp -r ${source_dir}/. "${dest_dir}"/

    install_hook_add 'chown -R 1000:1000 home/user' \
                     'chmod 750 root' \
                     'chmod 777 tmp' \
                     'chmod 777 run' \
                     'chmod 710 home/user'
}
