#! /bin/sh

version=1.28.0
revision=4
tarball_url="https://pub.mate-desktop.org/releases/1.28/mate-icon-theme-${version}.tar.xz"
tarball_blake2b="18b7f43c5a1a0c8f9a45feb0d4941d659d67d98918227615d12acd176cc3cf96a8eb48c9d9bfebe4710417b3fffabc89d433d51c44b42df16bf62332a743b6ae"
hostdeps="gcc pkg-config"
imagedeps="icon-naming-utils"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-icon-mapping
}

build() {
    make -j${parallelism}
}

package() {
    iconmap=/usr/lib/icon-naming-utils/icon-name-mapping
    [ -x "${iconmap}" ] || die "*** ${iconmap} is missing: the icon-naming-utils imagedep has moved, and without it mate-icon-theme silently ships half its icons"

    DESTDIR="${dest_dir}" make install \
        ICONMAP="${iconmap}"

    post_package_strip
}
