#! /bin/sh

version=5.05
revision=4
git_url="https://github.com/eyJhb/sl.git"
commit=085764117c72ed7d9387fb09a27d96003d36090f
hostdeps="gcc"
deps="core-libs ncurses"

build() {
    cp -rp "${source_dir}"/. ./
        LDFLAGS="${TARGET_LDFLAGS}" \
    make -j${parallelism} \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}"
}

package() {
    mkdir -pv "${dest_dir}${prefix}"/bin/
    install -Dm 775 sl "${dest_dir}${prefix}"/bin/

    install -Dm 644 sl.1 "${dest_dir}${prefix}"/share/man/man1/sl.1

    post_package_strip
}
