#! /bin/sh

version=9.0.0
revision=9
tarball_url="https://archive.mesa3d.org/demos/mesa-demos-${version}.tar.xz"
tarball_blake2b="426211886344e88616670f0da8c71385e0ab86fd7dab60c7a477b165f33d2f7bd5fd9297f1f67c78e60fed5c98ab8851c1bd4ae92a6b0b486fd158196b109eb0"
hostdeps="gcc pkg-config"
deps="core-libs mesa glu freeglut libx11 libxext"

configure() {
        TARGET_CFLAGS="${TARGET_CFLAGS} -D_XOPEN_SOURCE -D_GNU_SOURCE" \
    meson_configure \
        -Degl=disabled \
        -Dgles1=disabled \
        -Dgles2=disabled \
        -Dglut=enabled \
        -Dosmesa=disabled \
        -Dlibdrm=disabled \
        -Dvulkan=disabled \
        -Dwayland=disabled \
        -Dx11=enabled \
        -Dwith-system-data-files=true
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
