#! /bin/sh

version=16.2.0
tarball_url="https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
tarball_blake2b="ab3ffe16e042da767f3f1eac170da518d6d7de3b0f92e068f79e3bf25fdc0bdf56eea0cd586bd4b9b6e9baebadd110c2ebd77b75c99c45853814f4bea5a98ef0"
revision=4
hostdeps="gcc pkg-config"
deps="core-libs binutils gmp mpc mpfr zlib zstd texinfo"
builddeps="gettext"
imagedeps="build-essential"
_glibc_version="$(. "${base_dir}/recipes/glibc/recipe" && echo "${version}")"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        CFLAGS_FOR_BUILD="$HOST_CFLAGS" \
        CXXFLAGS_FOR_BUILD="$HOST_CXXFLAGS" \
        LDFLAGS_FOR_BUILD="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
        LDFLAGS_FOR_TARGET="$TARGET_LDFLAGS" \
        --target=${OS_TRIPLET} \
        --with-sysroot= \
        --with-build-sysroot=${sysroot} \
        --with-glibc-version=${_glibc_version} \
        --enable-__cxa_atexit \
        --enable-cet=auto \
        --enable-checking=release \
        --enable-clocale=gnu \
        --with-linker-hash-style=gnu \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-gnu-indirect-function \
        --enable-gnu-unique-object \
        --enable-libstdcxx-backtrace \
        --enable-link-serialization=1 \
        --enable-linker-build-id \
        --enable-languages=c,c++,fortran,lto \
        --enable-lto \
        --disable-fixincludes \
        --with-gcc-major-version-only \
        --disable-multilib \
        --enable-plugin \
        --enable-host-shared \
        --enable-threads=posix \
        --disable-libssp \
        --disable-libstdcxx-pch \
        --disable-werror \
        --with-system-zlib
}

build() {
    make -j${parallelism} all-gcc
}

package() {
    DESTDIR="${dest_dir}" make install-gcc
    DESTDIR="${dest_dir}" make -C gcc fortran.install-common
    DESTDIR="${dest_dir}" make -C gcc fortran.install-man
    DESTDIR="${dest_dir}" make -C gcc fortran.install-info

    ln -s gcc "${dest_dir}${prefix}"/bin/cc
    ln -s gfortran "${dest_dir}${prefix}"/bin/f95
    cp -v "${recipe_dir}"/c89 "${dest_dir}${prefix}"/bin/
    cp -v "${recipe_dir}"/c99 "${dest_dir}${prefix}"/bin/
    cp -v "${recipe_dir}"/f77 "${dest_dir}${prefix}"/bin/
    chmod +x "${dest_dir}${prefix}"/bin/c89
    chmod +x "${dest_dir}${prefix}"/bin/c99
    chmod +x "${dest_dir}${prefix}"/bin/f77

    post_package_strip

    generate_info_hooks
}
