#! /bin/sh

version=16.1.0
tarball_url="https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
tarball_blake2b="ceb07866b6b17eb4c69a6b51241b275bc5ec506603a7c1a4c1e2585091a09fc647be945beeff76700bffd9018bda81b072d84f909fd7998baa0cfe3f0eb550b4"
revision=2
hostdeps="gcc pkg-config"
deps="core-libs binutils zlib gmp mpfr mpc gettext"
imagedeps="build-essential"

prepare() {
    for i in "${base_dir}"/host-recipes/gcc/patches/*; do
        patch -p1 < "$i"
    done

    autotools_recursive_regen
}

configure() {
    autotools_configure \
        CFLAGS_FOR_BUILD="$HOST_CFLAGS" \
        CXXFLAGS_FOR_BUILD="$HOST_CXXFLAGS" \
        LDFLAGS_FOR_BUILD="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
        LDFLAGS_FOR_TARGET="$TARGET_LDFLAGS" \
        --target=${OS_TRIPLET} \
        --with-sysroot=/ \
        --with-build-sysroot=${sysroot} \
        --with-glibc-version=2.42 \
        --enable-__cxa_atexit \
        --enable-cet=auto \
        --enable-checking=release \
        --enable-clocale=gnu \
        --with-linker-hash-style=gnu \
        --enable-linker-build-id \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-gnu-indirect-function \
        --enable-gnu-unique-object \
        --enable-libstdcxx-backtrace \
        --enable-link-serialization=1 \
        --enable-linker-build-id \
        --enable-languages=c,c++,fortran,lto \
        --enable-lto \
        --disable-multilib \
        --enable-plugin \
        --enable-shared \
        --enable-host-shared \
        --enable-threads=posix \
        --disable-libssp \
        --disable-libstdcxx-pch \
        --disable-werror \
        --with-system-zlib
}

build() {
    make -j${parallelism} all-gcc
}

package() {
    DESTDIR="${dest_dir}" make install-gcc
    DESTDIR="${dest_dir}" make -C gcc fortran.install-common
    DESTDIR="${dest_dir}" make -C gcc fortran.install-man
    DESTDIR="${dest_dir}" make -C gcc fortran.install-info

    ln -s gcc "${dest_dir}${prefix}"/bin/cc
    ln -s gfortran "${dest_dir}${prefix}"/bin/f95
    cp -v "${recipe_dir}"/c89 "${dest_dir}${prefix}"/bin/
    cp -v "${recipe_dir}"/c99 "${dest_dir}${prefix}"/bin/
    cp -v "${recipe_dir}"/f77 "${dest_dir}${prefix}"/bin/
    chmod +x "${dest_dir}${prefix}"/bin/c89
    chmod +x "${dest_dir}${prefix}"/bin/c99
    chmod +x "${dest_dir}${prefix}"/bin/f77

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
