#! /bin/sh

repology_id=xsetroot
version=1.1.4
revision=2
tarball_url="https://www.x.org/archive/individual/app/xsetroot-${version}.tar.gz"
tarball_blake2b="03f61c26dc9d6e9459d89fcaf5c982d9c9d4960aea298e2f2e77464ab6082f912e1bd6b9d2f118c544f378ceb39e3dfb9a2a9fe626759bf501114ee07c7ee85b"
hostdeps="gcc pkg-config"
builddeps="xbitmaps"
deps="core-libs libx11 libxmu libxcursor"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
