#! /bin/sh

repology_id=glib
version=2.88.1
revision=1
tarball_url="https://download.gnome.org/sources/glib/2.88/glib-${version}.tar.xz"
tarball_blake2b="d9a0e54d2c1b5128aee76f1743cbeea84a24af5a2252ba1c649943bbca3fbc5f08896249542526560c92dd0e60cbd8a72498c3cfe1535d1f0bf85316ce37dba1"
imagedeps="python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 libffi zlib"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled \
        -Dxattr=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
    generate_glib_schemas_hook
}
