#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=6
git_url="https://codeberg.org/Ironclad/libnvmm.git"
commit=a7cd5f5c9b9388550f5025d00000406cf287caa7
hostdeps="gcc pkg-config"
deps="core-libs"

if [ "${JINX_ARCH}" = x86_64 ]; then

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}

fi
