#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=9
git_url="https://codeberg.org/Ironclad/libnvmm.git"
commit=a527177f569416f898f4eb46a3c5a6ba919d5f4b
hostdeps="gcc pkg-config"
deps="core-libs"

if [ "${JINX_ARCH}" = x86_64 ]; then

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}

fi
