#! /bin/sh

version=3.8.0
revision=8
tarball_url="https://github.com/freeglut/freeglut/releases/download/v${version}/freeglut-${version}.tar.gz"
tarball_blake2b="a1b31f53de54deb1803f1b307074bd97e21aef79aca996ca779b22bcbd27f80b0376a4da86fe68929c34e0ed351f5bb5aa10677d21f1a434aaeeb202355795da"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxi libxrandr libxxf86vm mesa glu"

configure() {
    cmake_configure \
        -DFREEGLUT_BUILD_DEMOS=OFF \
        -DFREEGLUT_BUILD_STATIC_LIBS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    sed -Ei "s|/sysroot(/)?|/|g" "${dest_dir}${prefix}"/lib/cmake/FreeGLUT/*.cmake

    ln -s glut.pc "${dest_dir}${prefix}"/lib/pkgconfig/freeglut.pc

    post_package_strip
}
