#! /bin/sh

version=1.2.5
revision=4
tarball_url="https://www.x.org/archive/individual/lib/libXScrnSaver-${version}.tar.xz"
tarball_blake2b="a57683c7af842dccc9eda77d9b3e0887aad4e93aec95e1537a3886bd8646af9f1fe64bb59de2d6c4c13fff04842daabc7fd86caff3c6d92ddd090291ce489707"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxext"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
