#! /bin/sh

repology_id=cairo-graphics-library
version=1.18.6
revision=1
tarball_url="https://cairographics.org/releases/cairo-${version}.tar.xz"
tarball_blake2b="5283fae2d77187b2f0342e86d7ff3383b90a98f29afa2e71cc0f33d1e709056d64822db50dee336651639dab17bdb6fe73fba140ecba791a666d021e6bb7d87b"
hostdeps="gcc pkg-config"
deps="core-libs fontconfig freetype2 glib2 libpng libx11 libxcb libxext libxrender pixman zlib"

configure() {
    # cauro handles fortify internally.
    # Remove any -D_FORTIFY_SOURCE from TARGET_CFLAGS to avoid conflicts.
    TARGET_CFLAGS="${TARGET_CFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"

    meson_configure \
        -Dlzo=disabled \
        -Ddwrite=disabled \
        -Dspectre=disabled \
        -Dsymbol-lookup=disabled \
        -Dtests=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
