#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/host-recipes/gcc/recipe" && echo ${version})"
revision=3
hostdeps="gcc pkg-config"
imagedeps="build-essential"
deps="glibc libgcc libstdc++"

package() {
    cd "${build_dir}"/host-builds/gcc/build

    rm -rf tmp_libatomic_dir
    mkdir tmp_libatomic_dir

    DESTDIR="$(realpath tmp_libatomic_dir)" make install-target-libatomic

    mkdir -p "${dest_dir}${prefix}"
    cp -r tmp_libatomic_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
