#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=9
git_url="https://gitlab.com/sortix/os-test.git"
commit=ec05ef048b20caf61afe5b7c0ff5212c6dd2a505
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs make sed"

configure() {
    cp -rp "${source_dir}/." ./
    rm -rf .git
}

build() {
    make all -j${parallelism} \
        OS=ironclad \
        CC=${OS_TRIPLET}-gcc \
        CC_FOR_BUILD=cc \
        CFLAGS_FOR_BUILD="-pthread"
    make misc/html -j${parallelism} \
        OS=ironclad \
        CC=${OS_TRIPLET}-gcc \
        CC_FOR_BUILD=${OS_TRIPLET}-gcc \
        CFLAGS_FOR_BUILD="-pthread"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/os-test"
    cp -rp . "${dest_dir}${prefix}/share/os-test/"
}
