#! /bin/sh

repology_id=xclock
version=1.2.1
revision=1
tarball_url="https://xorg.freedesktop.org/archive/individual/app/xclock-${version}.tar.gz"
tarball_blake2b="280543acac24c0e20346072e56c7d9087cf72455b5a38383de1af44e667080c131426384abf6d219c30e56e53bc95d825053d460582143003837be3b9c08e3f8"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxmu libxaw libxrender libxft libxkbfile"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
