#! /bin/sh

version=0.8.3
revision=4
git_url="https://github.com/Cyan4973/xxHash.git"
commit=e626a72bc2321cd320e953a0ccf1584cad60f363
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        CC="${OS_TRIPLET}-gcc" \
        AR="${OS_TRIPLET}-ar" \
        UNAME=Ironclad \
        -j${parallelism}
}

package() {
    make install \
        DESTDIR="${dest_dir}" \
        PREFIX="${prefix}" \
        UNAME=Ironclad \
        CC="${OS_TRIPLET}-gcc"

    rm -fv "${dest_dir}${prefix}"/lib/libxxhash.a

    post_package_strip
}
