#! /bin/sh

version=0.8.4
revision=1
git_url="https://github.com/Cyan4973/xxHash.git"
commit=c87183a77d67f7d37e3d2d1b7eaac5e7c695e4f0
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make \
        CC="${OS_TRIPLET}-gcc" \
        AR="${OS_TRIPLET}-ar" \
        UNAME=Ironclad \
        -j${parallelism}
}

package() {
    make install \
        DESTDIR="${dest_dir}" \
        PREFIX="${prefix}" \
        UNAME=Ironclad \
        CC="${OS_TRIPLET}-gcc" \
        AR="${OS_TRIPLET}-ar"

    rm -fv "${dest_dir}${prefix}"/lib/libxxhash.a

    post_package_strip
}
