#! /bin/sh

skip_pkg_check=yes
version=0.0
revision=12

deps="core-libs
caja marco mate-control-center mate-desktop mate-icon-theme mate-menus
mate-panel mate-session-manager mate-settings-daemon mate-themes
atril eom mate-calc mate-screensaver mate-terminal mate-utils pluma"
