#! /bin/sh

version=5.48
revision=1
tarball_url="https://astron.com/pub/file/file-${version}.tar.gz"
tarball_blake2b="d8ca86ec79db28c59d7c5da9282fb5fa03a0775147856cb4d35528f12d2eb4293aca3336cb0e5108ce56c2f6a255e5b36957ba826b185575531508176f2af06a"
hostdeps="gcc pkg-config file"
deps="core-libs bzip2 xz zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
