#! /bin/sh

version=1.28.0
revision=6
tarball_url="https://github.com/mate-desktop/mate-settings-daemon/releases/download/v${version}/mate-settings-daemon-${version}.tar.xz"
tarball_blake2b="fab6b5ffb28039474976b1ad3f82e8096c568186df8a7f796e95ce8b7dbed72e35feee30b5f6cff14de8df4d1048d697543ec9f29e59d37171e708b8a12556c9"
imagedeps="libglib2.0-dev-bin libglib2.0-bin libdbus-glib-1-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo dconf fontconfig gdk-pixbuf glib2 gtk3 libmatekbd libnotify libx11 libxi libxklavier mate-desktop"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-x \
        --with-libnotify \
        --without-libmatemixer \
        --disable-polkit \
        --disable-pulse \
        --disable-rfkill \
        --disable-smartcard-support
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    rm -f "${dest_dir}${prefix}"/share/man/man1/msd-datetime-mechanism.1

    post_package_strip

    generate_glib_schemas_hook
}
