#! /bin/sh

version=1.1.7
revision=4
tarball_url="https://www.x.org/archive/individual/lib/libXxf86vm-${version}.tar.gz"
tarball_blake2b="15fe81eb71deddf5d688ce452e447abcfeee6eac09452249a23a8e69186dd5efe25f26a4c7b5954ca2f26a48e92eb9d7726d1bb8744021ab4dd0c6ceb7ffe8af"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxext"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
