#! /bin/sh

version=0.4.7
revision=4
tarball_url="https://www.x.org/archive/individual/lib/libXcomposite-${version}.tar.gz"
tarball_blake2b="bc9c4dec74000b353e9763c2b7ed04d3ebd95a0bbf48564f1366f714b7a5b191784a91fa6b90579d6c3907a7142e50af52231f2ced3644139cbc171ba242cec8"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxfixes xorg-proto"


configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
