#! /bin/sh

version=1.12.0
revision=5
tarball_url="https://github.com/mesonbuild/meson/releases/download/${version}/meson-${version}.tar.gz"
tarball_blake2b="41d06e300bd549958179e81c0ba3c494912652f8851ef34214de05db42e32fe793cd42f09ef08a8f44e4340649508ed9dc5071daba9dda81df0efa9669022251"
imagedeps="python3-build python3-installer"
hostdeps="pkg-config"
deps="core-libs python ninja"

build() {
    cp -rp "${source_dir}"/. ./

    python3 -m build \
        --wheel \
        --no-isolation
}

package() {
    DEB_PYTHON_INSTALL_LAYOUT=deb python3 -m installer \
        --destdir="${dest_dir}" \
        --prefix="${prefix}" \
        dist/*.whl

    mv "${dest_dir}${prefix}"/lib/python3/dist-packages \
       "${dest_dir}${prefix}"/lib/python3/site-packages

    post_package_strip
}
