#! /bin/sh

version=1.11.2
revision=1
tarball_url="https://github.com/mesonbuild/meson/releases/download/${version}/meson-${version}.tar.gz"
tarball_blake2b="c4ad77fe543b555d23f511dd2de43f6ee259384b6a753ecfe6142793fc0a9d7bc3cdd2d1e48d2b8dae35b96870e55c5d33df40c4b0284ea1bedef5f76b3a0214"
imagedeps="python3-build python3-installer"
hostdeps="pkg-config"
deps="core-libs python ninja"

build() {
    cp -rp "${source_dir}"/. ./

    python3 -m build \
        --wheel \
        --no-isolation
}

package() {
    DEB_PYTHON_INSTALL_LAYOUT=deb python3 -m installer \
        --destdir="${dest_dir}" \
        --prefix="${prefix}" \
        dist/*.whl

    post_package_strip
}
