#! /bin/sh

version=1.11.1
revision=1
tarball_url="https://github.com/mesonbuild/meson/releases/download/${version}/meson-${version}.tar.gz"
tarball_blake2b="3fcedb28ae3646e1c6bc1b9596ec3f04af1752bef7de9a0a1086aa103d8e0e91b22c66b85f66751447571d2d8815cf3582aacb1e252ea4af59aa18ae1bbede13"
imagedeps="python3-build python3-installer"
hostdeps="pkg-config"
deps="core-libs python ninja"

build() {
    cp -rp "${source_dir}"/. ./

    python3 -m build \
        --wheel \
        --no-isolation
}

package() {
    DEB_PYTHON_INSTALL_LAYOUT=deb python3 -m installer \
        --destdir="${dest_dir}" \
        --prefix="${prefix}" \
        dist/*.whl

    post_package_strip
}
