#! /bin/sh

version=2.44
revision=3
git_url="https://codeberg.org/Ironclad/glibc.git"
commit=1cec94f3227feae56fae252614e43b0f10ca53b7
hostdeps="bootstrap-gcc pkg-config"

prepare() {
    autotools_recursive_regen
}

configure() {
    # glibc handles fortify internally via --enable-fortify-source.
    TARGET_CFLAGS="${TARGET_CFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"
    TARGET_CXXFLAGS="${TARGET_CXXFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"

    TARGET_CFLAGS="${TARGET_CFLAGS} -g"
    TARGET_CXXFLAGS="${TARGET_CXXFLAGS} -g"

    for _m in /base_dir=/usr/src /build_dir=/usr/src /sysroot= /usr/local/lib/gcc=/usr/lib/gcc; do
        TARGET_CFLAGS="${TARGET_CFLAGS} -fdebug-prefix-map=${_m}"
        TARGET_CXXFLAGS="${TARGET_CXXFLAGS} -fdebug-prefix-map=${_m}"
    done

    echo "slibdir=${prefix}/lib" >> configparms
    echo "rtlddir=${prefix}/lib" >> configparms
    echo "sbindir=${prefix}/bin" >> configparms
    echo "rootsbindir=${prefix}/bin" >> configparms

    autotools_configure \
        --with-headers=${sysroot}${prefix}/include \
        --with-bugurl=https://codeberg.org/Ironclad/Gloire/issues \
        --enable-bind-now \
        --enable-cet \
        --enable-fortify-source \
        --enable-stack-protector=strong \
        --disable-nscd \
        --disable-profile \
        --disable-timezone-tools \
        --disable-werror
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    install_hook_add 'locale-gen'
    generate_info_hooks
}
