#! /bin/sh

version=10.48
revision=1
tarball_url="https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${version}/pcre2-${version}.tar.bz2"
tarball_blake2b="7c500b4271e13c8a965a85c2aac4a72d5f29b7a3318b6077fa9de391512669ad26a5a774eee322c966ed38127ca9dfc139e4dacc1c1b23578d0674d882b3d84c"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 zlib"

configure() {
    cmake_configure \
        -DPCRE2_BUILD_PCRE2_16=ON \
        -DPCRE2_BUILD_PCRE2_32=ON \
        -DPCRE2_SUPPORT_JIT=ON \
        -DPCRE2_BUILD_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
