#! /bin/sh

version=2.0.6
revision=5
git_url="https://gitlab.com/jobol/tr7.git"
commit=d36db5704e276d7288ea173e90a225ed34203e60
imagedeps="build-essential"
hostdeps="gcc"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
        CC="${OS_TRIPLET}-gcc" \
    make -j${parallelism} \
        DFLAGS= \
        PREFIX="${prefix}"

    mkdir -p host-doc
    cp -rp "${source_dir}"/. host-doc/
        CFLAGS="${HOST_CFLAGS}" \
        LDFLAGS="${HOST_LDFLAGS}" \
    make -C host-doc -j${parallelism} \
        DFLAGS= \
        tr7.html
    cp -p host-doc/tr7.html .
    touch tr7.html
    rm -rf host-doc
}

package() {
    make \
        DESTDIR="${dest_dir}" \
        PREFIX="${prefix}" \
        install-bin install-dyn install-doc

    post_package_strip
}
