#! /bin/sh

version=2.60.5
revision=1
tarball_url="https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/${version}/at-spi2-core-${version}.tar.gz"
tarball_blake2b="8c9a2fb50671af84919c86d988d73e865e1f27cecd17acf63bf625fd54bf515e05524529e5128ff2b1c4b3daa33f3bf0482487cfd1643449daa0930ec0e87a7c"
imagedeps="libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs bash dbus glib2 gsettings-desktop-schemas libx11 libxi libxkbcommon libxml2 libxtst"

configure() {
    meson_configure \
        -Dsystemd_user_dir=/remove_later \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -rv "${dest_dir}"/remove_later

    post_package_strip
}
