#! /bin/sh

version=2.62.0.1
revision=1
tarball_url="https://download.gnome.org/sources/at-spi2-core/2.62/at-spi2-core-${version}.tar.xz"
tarball_blake2b="446afa1375f9f9aa26cada456fefa378ba4ac85a2c42bb746e8bc4d84f935df6c1ed8ea0962042f97249700740a6c394efd889bb20d6f153ef696fc835c792c0"
imagedeps="libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs dbus glib2 gsettings-desktop-schemas libx11 libxi libxtst"
builddeps="libxml2"

configure() {
    meson_configure \
        -Dpython.platlibdir="${prefix}/lib/python3/site-packages" \
        -Dpython.purelibdir="${prefix}/lib/python3/site-packages" \
        -Ddefault_bus=dbus-daemon \
        -Duse_systemd=false \
        -Dgtk2_atk_adaptor=false \
        -Dintrospection=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
