#! /bin/sh

version=1.12.2
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${version}.tar.gz"
tarball_blake2b="6fca78f709dc15ba7c1b017954434f75f8445a144e7417cd02b11b12d1078569eda892020939e6be3090c76fcf4dc6a9b2648d86c4f5497b5b7cbbf24695f1bc"
imagedeps="build-essential libgpg-error-dev"
hostdeps="gcc pkg-config"
deps="core-libs libgpg-error"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-libgpg-error-prefix="${sysroot}${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
