#! /bin/sh

version=1.12.4
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-${version}.tar.gz"
tarball_blake2b="9bda6697c0705e2aca193179e4f43f87b1a6c35572445b7d7283bef5451d7fdf59417a51906c6032d89edb01d238f573f5a0f42984bd9ef3dab5ea7cba249aa9"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs libgpg-error texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
        GPGRT_CONFIG="${sysroot}${prefix}/bin/gpgrt-config" \
        GPG_ERROR_CONFIG=no \
    autotools_configure \
        --with-libgpg-error-prefix="${sysroot}${prefix}" \
        --disable-padlock-support
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    post_package_strip
    generate_info_hooks
}
