#! /bin/sh

version=1.11.0
revision=3
tarball_url="https://www.ivarch.com/s/pv-${version}.tar.gz"
tarball_blake2b="4fa75bad5389b823c113573457397e44cf9e0c3a24f58503f47d55d0eee937fabe0fc5cf360930e3bd0c81337747f73ebbf0fdb0aca4057cde22ffa2f22c9be5"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
