#! /bin/sh

version=1.12.0
revision=1
tarball_url="https://www.ivarch.com/s/pv-${version}.tar.gz"
tarball_blake2b="1afad5f98256aff785b916a8cd800f8771dd08fbc3a4fb2da0049c708aa11d1f504b4cebfdca364fb94fa107e9fd150a696fae5ba9553bce870ee3fea4b15b0b"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
