#! /bin/sh

version=1.3.2
revision=5
tarball_url="https://zlib.net/zlib-${version}.tar.xz"
tarball_blake2b="fd3a6e4c275a925f4814de487075c136e28421ea34ca7f93141781e7a414b392cd849fbf96cfcb24e825441df5f3c64be54276c0f617dc2d5c865d4ab260e83c"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DCMAKE_INSTALL_DOCDIR=share/doc \
        -DZLIB_BUILD_STATIC=OFF \
        -DZLIB_BUILD_TESTING=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
