#! /bin/sh

version=6.6
revision=4
tarball_url="https://invisible-mirror.net/archives/ncurses/ncurses-${version}.tar.gz"
tarball_blake2b="8863ce3091fc72f23d12fe5913ea07c783e907cd8454b1c2b782f3e6bb91110cbfc4c52b8f0404eabd0d2041211183614e9d7f125ef8deeb23237b031f61fca0"
imagedeps="build-essential ncurses-bin patchelf"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
        cf_cv_func_nanosleep=yes \
    autotools_configure \
        --disable-root-access \
        --disable-root-environ \
        --disable-setuid-environ \
        --enable-widec \
        --enable-pc-files \
        --with-shared \
        --with-cxx-shared \
        --with-cxx-binding \
        --without-normal \
        --without-debug \
        --with-manpage-format=normal \
        --without-manpage-renames \
        --with-pkg-config-libdir=${prefix}/lib/pkgconfig \
        --with-versioned-syms \
        --with-xterm-kbs=del \
        --without-ada
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    for lib in ncurses ncurses++ form panel menu; do
       rm -vf                    "${dest_dir}${prefix}"/lib/lib${lib}.so
       echo "INPUT(-l${lib}w)" > "${dest_dir}${prefix}"/lib/lib${lib}.so
       ln -sfv ${lib}w.pc        "${dest_dir}${prefix}"/lib/pkgconfig/${lib}.pc
       # Set library soname
       patchelf --set-soname lib${lib}w.so.${version%%.*} "${dest_dir}${prefix}"/lib/lib${lib}w.so
    done
    rm -vf                     "${dest_dir}${prefix}"/lib/libcursesw.so
    echo "INPUT(-lncursesw)" > "${dest_dir}${prefix}"/lib/libcursesw.so
    ln -sfv libncurses.so      "${dest_dir}${prefix}"/lib/libcurses.so

    for lib in tic tinfo; do
       ln -sfv libncursesw.so                "${dest_dir}${prefix}"/lib/lib${lib}.so
       ln -sfv libncursesw.so.${version%%.*} "${dest_dir}${prefix}"/lib/lib${lib}.so.${version%%.*}
       ln -sfv ncursesw.pc                   "${dest_dir}${prefix}"/lib/pkgconfig/${lib}.pc
    done

    sed -i 's|/base_dir/sources/ncurses/||g' \
        "${dest_dir}${prefix}"/include/curses.h \
        "${dest_dir}${prefix}"/share/man/man5/terminfo.5

    post_package_strip
}
