#! /bin/sh

version=1.3.6
revision=5
tarball_url="https://downloads.xiph.org/releases/ogg/libogg-${version}.tar.xz"
tarball_blake2b="18b5563775b0569db1c41358a8c2de9a64b14754ca0da8a154e692e6cb26fbd5dc73ac7fa61697304bca2847db5b5f256be8361840b3e0df270a0701f1468814"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
