#! /bin/sh

set -eu

dialog --clear \
    --backtitle "gloire-install" \
    --title "Welcome to gloire-install!" \
    --msgbox "\nThis script will help you install Gloire into a physical device in an interactive manner" 0 0

if [ "$(id -u)" -ne 0 ]; then
    dialog --clear \
        --backtitle "gloire-install" \
        --title "Running as non root" \
        --msgbox "\nThis script requires to be ran as the root user (UID 0), please rerun it as such" 0 0
    exit 1
fi

available_lsblk="$(lsblk -n | awk 'NF==3 && !/.*p[0-9]+/ { print $1 }')"
if [ -z "$available_lsblk" ]; then
    dialog --clear \
        --backtitle "gloire-install" \
        --title "Could not find suitable devices" \
        --msgbox "\nThis script did not find a suitable unmounted drive for installation, is your drive supported and attached?" 0 0
    exit 1
fi

dialog_out=$(mktemp)
if ! dialog --clear \
    --backtitle "gloire-install" \
    --title "Device selection" \
    --menu "Choose one(1) device to install Gloire" 0 0 0 \
    $(i=0; for d in $available_lsblk; do echo $((++i)) $d; done) 2> $dialog_out
then
    clear
    exit
fi
option_device=$(cat $dialog_out)
device=$(f() { n=$1; shift 1; shift $n; echo $1; }; f $(($option_device-1)) $available_lsblk)
rm $dialog_out

dialog_out=$(mktemp)
if ! dialog --clear \
    --backtitle "gloire-install" \
    --title "Hostname selection" \
    --inputbox "Type the hostname the new machine will have" 0 0 2> $dialog_out
then
    clear
    exit
fi
hostname=$(cat $dialog_out)
rm $dialog_out

dialog_out=$(mktemp)
if ! dialog --clear \
    --backtitle "gloire-install" \
    --title "Desktop environment" \
    --radiolist "Would you like a desktop environment to be installed?" 0 0 0 \
    1 "Minimal terminal-only install" on \
    2 "MATE Desktop Environment (X11)" off \
    3 "Joe's Window Manager (JWM/X11)" off 2> $dialog_out
then
    clear
    exit
fi
option_desktop=$(cat $dialog_out)
rm $dialog_out

if ! dialog --clear \
    --backtitle "gloire-install" \
    --title "Confirm actions" \
    --yesno "All data in '$device' will be deleted, do you wish to proceed?" 0 0;
then
   clear
   exit
fi

set -x

# Make 3 partitions: BIOS Boot for limine, ESP, and the main partition.
sgdisk --zap-all "/dev/$device"
sgdisk -n 1:0:+2M "/dev/$device"
sgdisk -n 2:0:+2G "/dev/$device"
sgdisk -n 3:0:0 "/dev/$device"
bios_partition="${device}p1"
esp_partition="${device}p2"
root_partition="${device}p3"

# Set flags and UUID.
root_uuid=$(uuidgen)
sgdisk "/dev/$device" -t 1:ef02 -c 1:"Gloire BIOS+Limine"
sgdisk "/dev/$device" -t 2:ef00 -c 2:"Gloire EFI System Partition"
sgdisk "/dev/$device" -t 3:8300 -c 3:"Gloire Root Partition" -u 3:"$root_uuid"

# Format devices.
mkfs.fat "/dev/$esp_partition"
mkfs.ext2 -F "/dev/$root_partition"

# Mount devices.
mkdir newroot
path_newroot=$(realpath newroot)
mount "/dev/$root_partition" "$path_newroot"
mkdir -p "$path_newroot/boot"
mount "/dev/$esp_partition" "$path_newroot/boot"

# Install in the root system and other package options.
yes | xbps-install -R https://gloire-repo.ironclad-os.org/xbps-pkgs/x86_64 -Syu base -r "$path_newroot"
case $option_desktop in
    2) xbps-install -R https://gloire-repo.ironclad-os.org/xbps-pkgs/x86_64 -Syu xorg-server xf86-input-keyboard xf86-input-mouse xf86-video-fbdev xorg-xinit mate -r "$path_newroot" ;;
    3) xbps-install -R https://gloire-repo.ironclad-os.org/xbps-pkgs/x86_64 -Syu xorg-server xf86-input-keyboard xf86-input-mouse xf86-video-fbdev xorg-xinit jwm -r "$path_newroot" ;;
    *) ;;
esac

# Add essential files, like the init system files, and hostname
mkdir -p "$path_newroot"/etc/epoch
cat << 'EOF' >> "$path_newroot"/etc/epoch/epoch.conf
# https://universe2.us/epochconfig.html

Hostname=FILE /etc/hostname
DefaultRunlevel=graphical-multiuser
DisableCAD=false
EnableLogging=true
BlankLogOnBoot=true

ObjectID=mounting
   ObjectDescription=Mounting /etc/fstab partitions
   ObjectStartCommand=mount -a
   ObjectStopCommand=NONE
   ObjectStartPriority=1
   ObjectStopPriority=0
   ObjectEnabled=true
   ObjectRunlevels=graphical-multiuser console-multiuser
   ObjectOptions=RAWDESCRIPTION

ObjectID=clear_tmp
   ObjectDescription=Clearing /tmp and /run
   ObjectStartCommand=rm -rvf /tmp/* &>/dev/null && rm -rvf /run/* &>/dev/null
   ObjectStopCommand=NULL
   ObjectStartPriority=2
   ObjectStopPriority=0
   ObjectEnabled=true
   ObjectRunlevels=graphical-multiuser console-multiuser
   ObjectOptions=RAWDESCRIPTION

ObjectID=xbps_reconf
   ObjectDescription=Running first boot configuration (if needed)
   ObjectStartCommand=gloire-first-boot
   ObjectStopCommand=NONE
   ObjectStartPriority=3
   ObjectStopPriority=0
   ObjectEnabled=true
   ObjectRunlevels=graphical-multiuser console-multiuser
   ObjectOptions=RAWDESCRIPTION

ObjectID=powerd
   ObjectDescription=power management daemon
   ObjectStartCommand=/usr/bin/powerd
   ObjectStopCommand=PID
   ObjectStartPriority=4
   ObjectStopPriority=4
   ObjectEnabled=true
   ObjectRunlevels=graphical-multiuser console-multiuser
   ObjectOptions=SERVICE

ObjectID=gcon
   ObjectDescription=gcon
   ObjectStartCommand=/usr/bin/gcon
   ObjectStopCommand=PID
   ObjectStartPriority=5
   ObjectStopPriority=5
   ObjectEnabled=true
   ObjectRunlevels=console-multiuser
   ObjectOptions=FORK

ObjectID=killall5_soft
   ObjectDescription=Terminating all processes
   ObjectStopCommand=killall5 -15 && sleep 5
   ObjectStartPriority=0
   ObjectStopPriority=6
   ObjectEnabled=true
   ObjectOptions=HALTONLY RAWDESCRIPTION

ObjectID=killall5
   ObjectDescription=Killing all processes
   ObjectStopCommand=killall5 -9 && sleep 5
   ObjectStartPriority=0
   ObjectStopPriority=7
   ObjectEnabled=true
   ObjectOptions=HALTONLY RAWDESCRIPTION
EOF

echo $hostname > "$path_newroot"/etc/hostname

# Cleanup after moving files over.
umount "$path_newroot/boot"
umount "$path_newroot"

# Install limine.
limine bios-install "/dev/$device"

sync

set +x

dialog --clear \
    --backtitle "gloire-install" \
    --title "Installation done" \
    --msgbox "Gloire has been installed on '$device'. The system will now poweroff, if you installed Gloire from an external drive, remove it before powering the machine again if you desire to boot into your new system." 0 0

poweroff
