#! /bin/sh

repology_id=fonts:noto-emoji
version=2.051
revision=3
git_url="https://github.com/googlefonts/noto-emoji.git"
commit=8998f5dd683424a73e2314a8c1f1e359c19e8742
deps="core-libs fontconfig"

package() {
    cd "${source_dir}"
    install -Dm644 fonts/NotoColorEmoji.ttf -t "${dest_dir}"/usr/share/fonts/noto

    generate_font_cache_hook
}
