#! /bin/sh

repology_srcname=gettext
version=1.0
revision=3
tarball_url="https://ftp.gnu.org/gnu/gettext/gettext-${version}.tar.xz"
tarball_blake2b="052bd847c8cdb963437613583256e430b52e27e5ebe29a04df6ac549552ab0f85a1e637b991ebb57e82805fb6d2d23f37c4b70d7f711dc086f57a3a32ba3f00e"
hostdeps="gcc pkg-config"
deps="core-libs libunistring libxml2 ncurses texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-nls \
        --with-xz \
        --without-included-gettext \
        --without-included-libunistring \
        --with-libunistring-prefix="${sysroot}${prefix}" \
        --with-libxml2-prefix="${sysroot}${prefix}" \
        --with-libncurses-prefix="${sysroot}${prefix}" \
        --without-emacs
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove conflicting libintl files
    rm -f "${dest_dir}${prefix}"/include/libintl.h
    rm -f "${dest_dir}${prefix}"/lib/libintl.so*
    rm -f "${dest_dir}${prefix}"/share/locale/locale.alias

    post_package_strip

    generate_info_hooks
}
