#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=66
git_url="https://codeberg.org/Ironclad/Ironclad.git"
commit=f7a550d71abd7fe4946da7f7bdaaaf7938c0a9c4
source_hostdeps="autoconf automake pkg-config"
imagedeps="gprbuild"
hostdeps="gcc pkg-config"
deps="core-libs texinfo"

early_prepare() {
    ./bootstrap
}

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure_noflags
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    generate_info_hooks
}
