#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=63
git_url="https://codeberg.org/Ironclad/Ironclad.git"
commit=fa1ad5f4afd4b338695b140a6f7a61f741e09d35
source_hostdeps="autoconf automake pkg-config"
imagedeps="gprbuild"
hostdeps="gcc pkg-config"
deps="core-libs texinfo"

early_prepare() {
    ./bootstrap
}

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure_noflags
}

build() {
    make -j${parallelism} GPRBUILD="gprbuild -v"
}

package() {
    DESTDIR="${dest_dir}" make install

    generate_info_hooks
}
