#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=68
git_url="https://codeberg.org/Ironclad/Ironclad.git"
commit=9b8b765f330aa0073e455b9c8c3e8aa43c05286b
source_imagedeps="autoconf automake pkg-config"
imagedeps="gprbuild"
hostdeps="gcc pkg-config"
deps="core-libs texinfo"

early_prepare() {
    ./bootstrap
}

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure_noflags
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    generate_info_hooks
}
