#! /bin/sh

version=2.5.4
revision=3
git_url="https://github.com/uclouvain/openjpeg.git"
commit=6c4a29b00211eb0430fa0e5e890f1ce5c80f409f
hostdeps="gcc pkg-config"
deps="core-libs lcms2 libpng libtiff zlib"

configure() {
    cmake_configure \
        -DBUILD_DOC=on
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
