#! /bin/sh

version=1.28.7
revision=13
tarball_url="https://github.com/mate-desktop/mate-panel/releases/download/v${version}/mate-panel-${version}.tar.xz"
tarball_blake2b="1649bc3d115ee37e70870d147f04036aaeea76a2319931ef5783ccd11fc1903efd9637ece54a0ca8255fefa728e40cc6b4b60a789d300515f715ae8dd3a4342c"
imagedeps="libglib2.0-bin libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo dbus gdk-pixbuf glib2 gtk3 libice libmateweather libsm libwnck libx11 libxrandr mate-desktop mate-menus pango"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --libexecdir="${prefix}/libexec/mate-panel" \
        --disable-introspection
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    sed -i 's|/base_dir/sources/mate-panel/||g' \
        "${dest_dir}${prefix}"/include/mate-panel-4.0/libmate-panel-applet/mate-panel-applet-enums.h

    post_package_strip

    generate_glib_schemas_hook
}
