#! /bin/sh

version=4.0
revision=3
tarball_url="https://ftp.gnu.org/gnu/nettle/nettle-${version}.tar.gz"
tarball_blake2b="7391fe45917ad394973a9069305c415779182ca9c7640105c47bbf23ef74301099ca8ab1bc18cc331297ec43c848b34b1c1549ae1111dadea17c35032a5ffcdc"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs gmp texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
}
