#! /bin/sh

version=1.0.9
revision=1
tarball_url="https://www.x.org/pub/individual/app/xlsfonts-${version}.tar.xz"
tarball_blake2b="0502168372442d173cef38beb6782db794acafb3d6a3ed84761c00085a46cbf7890543b9980d710a3cea9d37367ade424dc999957960afb988f67fcd74bd13d5"
hostdeps="gcc pkg-config"
deps="core-libs libx11"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
