#! /bin/sh

repology_id=gtksourceview
repology_srcname=gtksourceview4
version=4.8.4
revision=5
tarball_url="https://download.gnome.org/sources/gtksourceview/4.8/gtksourceview-${version}.tar.xz"
tarball_blake2b="0fb649522ff904993b7673c380b8ffb6458c0727b6af906e5328d972fb5385a2a668c2ca45b7dd3533f9f00b2ed9eaade55ee7b20a0b75fb1c031b917c27af2d"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gtk3 cairo pango gdk-pixbuf at-spi2-core fribidi libxml2"

configure() {
    meson_configure \
        -Dglade_catalog=false \
        -Dgir=false \
        -Dvapi=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
