#! /bin/sh

version=1.3.1
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXmu-${version}.tar.gz"
tarball_blake2b="5457c31f936850b634444ffd6f0c1e3115149ce99937c2a3c1b236fa7cf2d57f2ec36c85dac074f7da4f1c6498023618180438fcd89ef933002f3f11aeeb63f1"
hostdeps="gcc pkg-config"
deps="core-libs libxext libxt"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
