#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/recipes/nss/recipe" && echo "${version}")"
revision=5
make_ca_version=1.16.1
tarball_url="https://github.com/lfs-book/make-ca/archive/v${make_ca_version}/make-ca-${make_ca_version}.tar.gz"
tarball_blake2b="f054fe6e96b74bfc02038e9dc4dd09628a22b75711f692a346c4952a6fa07456b63cff7863d3c11feddeb1ef37b1b786934e2713008b808570da8443e978ece3"
imagedeps="p11-kit"
hostdeps="gcc pkg-config"
deps="core-libs nss openssl p11-kit"

build() {
    cp -rp "${source_dir}"/. ./
}

package() {
    chmod +x ./make-ca
    ./make-ca -f -C "${sysroot}${prefix}/share/nss/certdata.txt" -D "${dest_dir}"

    # Compatibility link for utilities that expect historically certain paths:
    # - OpenSSL using /etc/ssl as CAdir: cert.pem
    # - Compatibility link for legacy bundle (Debian): ca-certificates.crt
    # - Compatibility link for legacy bundle (RHEL/Fedora): ca-bundle.crt
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/cert.pem"
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/certs/ca-certificates.crt"
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/certs/ca-bundle.crt"

    # Remove unneeded systemd timers
    rm -rvf ${dest_dir}${prefix}/lib

    post_package_strip
}
