#! /bin/sh

skip_pkg_check=yes
version="$(. "${base_dir}/recipes/nss/recipe" && echo "${version}")"
revision=9
git_url="https://github.com/lfs-book/make-ca.git"
commit=c52f1373f5d91d8d7078fe129ac28664d3bbd941
imagedeps="p11-kit openssl"
hostdeps="gcc pkg-config"
deps="core-libs p11-kit"
builddeps="nss"

build() {
    cp -rp "${source_dir}"/. ./
}

package() {
    chmod +x ./make-ca
    ./make-ca -f -C "${sysroot}${prefix}/share/nss/certdata.txt" -D "${dest_dir}"

    # Compatibility link for utilities that expect historically certain paths:
    # - OpenSSL using /etc/ssl as CAdir: cert.pem
    # - Compatibility link for legacy bundle (Debian): ca-certificates.crt
    # - Compatibility link for legacy bundle (RHEL/Fedora): ca-bundle.crt
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/cert.pem"
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/certs/ca-certificates.crt"
    ln -s "/etc/pki/tls/certs/ca-bundle.crt" "${dest_dir}/etc/ssl/certs/ca-bundle.crt"

    sed -i "s|${dest_dir}||g" "${dest_dir}"/etc/pki/anchors.md5sums

    # Remove unneeded systemd timers
    rm -rvf ${dest_dir}${prefix}/lib

    post_package_strip
}
