#! /bin/sh

version=51.0
revision=1
tarball_url="https://download.gnome.org/sources/gsettings-desktop-schemas/51/gsettings-desktop-schemas-${version}.tar.xz"
tarball_blake2b="4f4cc0075524e6728d02cf7dd3cdcb57530073cbb1ec68633851824d2804a029a38bde2445689eb18bdc8702ddcb7ec40e890c8acfcc201539d66579788b53c2"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs glib2"

prepare() {
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
}

configure() {
    meson_configure \
        -Dintrospection=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    glib-compile-schemas "${dest_dir}${prefix}"/share/glib-2.0/schemas
    rm "${dest_dir}${prefix}"/share/glib-2.0/schemas/gschemas.compiled

    post_package_strip

    generate_glib_schemas_hook
}
