#! /bin/sh

repology_id=expat
version=2.8.4
fixed_version=$(echo ${version} | sed 's/\./_/g')
revision=1
tarball_url="https://github.com/libexpat/libexpat/releases/download/R_${fixed_version}/expat-${version}.tar.gz"
tarball_blake2b="db5dcc9e5360d285ff6fbb6d15cefdc680371451c20a5d7787917847b8678a2b37c93158b81877f0c4ea64bc631d4322ccd70d5d6ae51ea822b12c37d5c3a304"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
