#! /bin/sh

version=0.26.5
revision=4
tarball_url="https://github.com/p11-glue/p11-kit/releases/download/${version}/p11-kit-${version}.tar.xz"
tarball_blake2b="3588e4abeca13450c8228b4e104942b459c86fa5bf07fd391b895ff99694e37a20562462fd3e5290dce79a45a16cc821da4ed86d9d4446beb1305d4638421589"
imagedeps="libtasn1-bin"
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1"

configure() {
    meson_configure \
        -Dsystemd=disabled \
        -Dtest=false \
        -Dman=true \
        -Dtrust_paths=/etc/pki/anchors \
        -Dbashcompdir=${prefix}/share/bash-completion/completions
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
