#! /bin/sh

version=0.26.2
revision=2
tarball_url="https://github.com/p11-glue/p11-kit/releases/download/${version}/p11-kit-${version}.tar.xz"
tarball_blake2b="a10eab0fe405ea1f99aaac823bdb48d09caa09decd6bfe134aa702430ed5c09af2416db503ea8954467179c30ab754cc2811b4d8e28ac02cf3847fa021e1a2e2"
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1 bash-completion"

configure() {
    meson_configure \
        -Dtrust_paths=/etc/pki/anchors \
        -Dbashcompdir=${prefix}/share/bash-completion/completions
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

#    sed '20,$ d' -i "${dest_dir}${prefix}/libexec/p11-kit/trust-extract-compat"
#
#    cat >>"${dest_dir}${prefix}/libexec/p11-kit/trust-extract-compat" <<EOF
## Copy existing anchor modifications to /etc/ssl/local
#${prefix}/libexec/make-ca/copy-trust-modifications
#
## Update trust stores
#${prefix}/bin/make-ca -r
#EOF
#
#    ln -svf "../libexec/p11-kit/trust-extract-compat" "${dest_dir}${prefix}/bin/update-ca-certificates"

    post_package_strip
}
