#! /bin/sh

version=1.3.0
revision=1
tarball_url="https://archive.hadrons.org/software/libmd/libmd-${version}.tar.xz"
tarball_blake2b="1b45d47355024f7b298cfe431760c4c583212594ba53c61d3f1ba2dea0087cf6be45feb23548b567b991864ede244efe31a8aa704fe088ac3dc1dacefd9f2f8f"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
