#! /bin/sh

_version=1.3-20260107
version=${_version//-/.}
revision=1
tarball_url="https://invisible-mirror.net/archives/dialog/dialog-${_version}.tgz"
tarball_blake2b="6047d566b820da45093cd9ac48d31c50b338ad8e8c408d42347885bd021843daedcdb50a7d85e2c3e61345a2ca848c727882c807f359455592c00755f3ce722c"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
      --with-ncursesw
}

build() {
    make -j${parallelism}
}

package() {
    make DESTDIR="${dest_dir}" install
    post_package_strip
}
