#! /bin/sh

_version=1.3-20260721
version=${_version//-/.}
revision=1
tarball_url="https://invisible-mirror.net/archives/dialog/dialog-${_version}.tgz"
tarball_blake2b="39810f45337bb7b5df297f58cd5a13f3350d32d73ca2192624ea22203afb837c0777484af6f400ee7ee36291163f1e5a14cd777281249878577580badd3cfd19"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
      --with-ncursesw
}

build() {
    make -j${parallelism}
}

package() {
    make DESTDIR="${dest_dir}" install
    post_package_strip
}
