#! /bin/sh

version=4.20.2
revision=1
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.gz"
tarball_blake2b="9340fed5854a7499b2019b96908445fa1422bd25181278d772bbdb1cede7f73ca03056a91ef60dcbf55d94472e422cd214768a3ed02856e1eac36a63e6b8ca63"
hostdeps="gcc pkg-config"
deps="core-libs libbsd"
conf_files="/etc/login.defs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-man \
        --with-yescrypt \
        --disable-logind
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install usbindir="${prefix}/bin"

    post_package_strip
}
