#! /bin/sh

version=4.20.0
revision=2
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.gz"
tarball_blake2b="655aa005401ba0215a8556fe88ed9ed3a070debd2092fd9e7c37582b41ecb2e4abfd34a8fea48bd33d0dcf9b948ff888b29e4301a62c74d823eae93fa2b4d2a7"
hostdeps="gcc pkg-config"
deps="core-libs libbsd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-logind
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # I cannot get it to not install in sbin so we bring out the jackhammer.
    mv "${dest_dir}"/usr/sbin/* "${dest_dir}"/usr/bin/
    rm -rf "${dest_dir}"/usr/sbin

    post_package_strip
}
