#! /bin/sh

from_source=file
revision=3
imagedeps="build-essential"

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    "${source_dir}"/configure \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-static \
        --disable-silent-rules
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
