#! /bin/sh

version=4.39
revision=1
tarball_url="https://archive.mozilla.org/pub/nspr/releases/v${version}/src/nspr-${version}.tar.gz"
tarball_blake2b="dfb8a050ee29974d5226c4140901ba1704af9ddf6939053e495cf698b23c2eb2aff4fec968cb321648ea4cb373cd85cb81283693b11d2b761e3dcc85294dfa57"
imagedeps="build-essential gcc"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    # Disable two unneeded scripts
    sed -i '/^RELEASE/s|^|#|' ${source_dir}/nspr/pr/src/misc/Makefile.in
    # Disable static libraries
    sed -i 's|$(LIBRARY) ||'  ${source_dir}/nspr/config/rules.mk

    autotools_recursive_regen
}

configure() {
        CC="${OS_TRIPLET}-gcc" \
        CXX="${OS_TRIPLET}-g++" \
        HOST_CC="gcc" \
        HOST_CFLAGS="${HOST_CFLAGS}" \
        HOST_CXXFLAGS="${HOST_CXXFLAGS}" \
        HOST_CPPFLAGS="${HOST_CPPFLAGS}" \
        HOST_LDFLAGS="${HOST_LDFLAGS}" \
        CROSS_COMPILE=1 \
        configure_script_path="${source_dir}/nspr/configure" \
    autotools_configure \
        --enable-optimize \
        --with-mozilla \
        --with-pthreads \
        --enable-64bit
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
