#! /bin/sh

repology_id=fonts:noto
version=2026.09.01
revision=1
git_url="https://github.com/notofonts/notofonts.github.io"
commit=76fff9eee60dcef8381bfcae8d0b4311e2186e67
deps="core-libs fontconfig"

package() {
    cd "${source_dir}"
    install -Dm644 fonts/*/hinted/ttf/*.tt[fc] -t "${dest_dir}"/usr/share/fonts/noto
    install -Dm644 "${recipe_dir}"/*.conf -t "${dest_dir}"/usr/share/fontconfig/conf.avail/
    install -d "${dest_dir}"/usr/share/fontconfig/conf.default
    ln -rs "${dest_dir}"/usr/share/fontconfig/conf.avail/* "${dest_dir}"/usr/share/fontconfig/conf.default

    generate_font_cache_hook
}
