#! /bin/sh

repology_id=fonts:noto
version=2026.08.01
revision=1
git_url="https://github.com/notofonts/notofonts.github.io"
commit=113d8e66a13a47d514be6c07e616842258982f42

package() {
    cd "${source_dir}"
    install -Dm644 fonts/*/hinted/ttf/*.tt[fc] -t "${dest_dir}"/usr/share/fonts/noto
    install -Dm644 "${recipe_dir}"/*.conf -t "${dest_dir}"/usr/share/fontconfig/conf.avail/
    install -d "${dest_dir}"/usr/share/fontconfig/conf.default
    ln -rs "${dest_dir}"/usr/share/fontconfig/conf.avail/* "${dest_dir}"/usr/share/fontconfig/conf.default
}
