#! /bin/sh

repology_id=fonts:noto
version=2026.07.01
revision=1
git_url="https://github.com/notofonts/notofonts.github.io"
commit=7baf6d8e43c5d2613dcbcaacdeb114f633b86069

package() {
    cd "${source_dir}"
    install -Dm644 fonts/*/hinted/ttf/*.tt[fc] -t "${dest_dir}"/usr/share/fonts/noto
    install -Dm644 "${recipe_dir}"/*.conf -t "${dest_dir}"/usr/share/fontconfig/conf.avail/
    install -d "${dest_dir}"/usr/share/fontconfig/conf.default
    ln -rs "${dest_dir}"/usr/share/fontconfig/conf.avail/* "${dest_dir}"/usr/share/fontconfig/conf.default
}
