#! /bin/sh

version=1.1.7
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXdamage-${version}.tar.gz"
tarball_blake2b="d2e62a0c01fd20cf9a1930b937a90147d6eeaba1c02a9d22d4284ae96a8d43624b712f6bcb70d703f5d5fa940c1fd93feae0b8788d9dfcc09d1e562adc8302a9"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libx11 libxfixes"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
