#! /bin/sh

version=1.3.0
revision=11
git_url="https://github.com/Subsentient/epoch.git"
commit=209bce15a58e388a7c2267fccbbb95a1c7ea018e
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make -j${parallelism} \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}"
}

package() {
    mkdir -p "${dest_dir}${prefix}"/bin
    cp -r built/sbin/* "${dest_dir}${prefix}"/bin/
    cp -r built/bin/*  "${dest_dir}${prefix}"/bin/

    mkdir -pv "${dest_dir}"/etc/epoch
    touch "${dest_dir}"/etc/epoch/.keep

    post_package_strip
}
