#! /bin/sh

version=12.2.0
revision=1
tarball_url="https://github.com/fmtlib/fmt/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="5dfb2eb6087a7442477a64c6d0ec5de8b27ca5768cb3330b51980085547553eed9a736ac2983d7d249f41655a8183aa45ead3f9289cd157f76f6fbe33c7920de"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DFMT_TEST=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
