#! /bin/sh

version=12.2.0
revision=3
zip_url="https://github.com/fmtlib/fmt/releases/download/${version}/fmt-${version}.zip"
zip_blake2b="63911dfad81be0447b192971e159eaef71f2cb3a9f56aed1a65bd9a248442bc57e60389ff228ceb4ae7faa2353707f306fac87ec174f00499e07ee759290a6ee"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DFMT_TEST=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
