#! /bin/sh

version=26.1.6
revision=1
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="1bb16b0982b81518d8a0dcfc9b78c487167b7832e21861d829c055939acca1f5aaf3e51680a1a39680d5ed89cfec233f1beea3261acd171585837f06b1e89937"
imagedeps="python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm-libs libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dvulkan-drivers=swrast \
        -Dvideo-codecs=all_free
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
