#! /bin/sh

version=26.2.0
revision=1
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="a87c8edcf47157dc57ad0ce12438cbdbf6e81b2fd93ba9a47581ba7c49a6be32364adfa214d0ef1785a782f37f0a8d9af9a2481fea884e9a6f7980a1af794aa8"
imagedeps="python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm-libs libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dvulkan-drivers=swrast \
        -Dvideo-codecs=all_free
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
