#! /bin/sh

version=26.2.1
revision=4
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="f5ec3451d18da9336d775259dd0d3f0c73c81d0857ba7da32dd296aba258ad5b8424fb8781582a838375e99710451d2aaeda94def604ad006e5a5a378b44d30a"
imagedeps="python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm-libs libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dvulkan-drivers=swrast \
        -Dgbm=disabled \
        -Degl=disabled \
        -Dglvnd=disabled \
        -Dxlib-lease=disabled \
        -Dallow-kcmp=disabled \
        -Dandroid-libbacktrace=disabled \
        -Dandroid-libperfetto=disabled \
        -Dgallium-va=disabled \
        -Dgallium-mediafoundation=disabled \
        -Dgallium-d3d12-video=disabled \
        -Dgallium-d3d12-graphics=disabled \
        -Dmicrosoft-clc=disabled \
        -Dintel-rt=disabled \
        -Dpower8=disabled \
        -Ddisplay-info=disabled \
        -Dspirv-tools=disabled \
        -Dlmsensors=disabled \
        -Dlibunwind=disabled \
        -Dvalgrind=disabled \
        -Dvideo-codecs=all_free \
        -Denable-glcpp-tests=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
