#! /bin/sh

version=3.8.2
revision=4
tarball_url="https://ftp.gnu.org/gnu/bison/bison-${version}.tar.xz"
tarball_blake2b="e211b61494c911f55b72a8b70b5a48cdf4000ce9e675a1f1f52735bb8f57d93a3f8075341451263af9c9c531004907ae2b62b1873e7e4664c2cd26fa3b12271c"
hostdeps="gcc pkg-config"
deps="core-libs m4 texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
}
