#! /bin/sh

repology_id=password-store
repology_srcname=password-store
version=1.7.4
revision=8
git_url="https://git.zx2c4.com/password-store"
commit=1078f2514d579178d5df7042c6a790e9c9b731ad
deps="core-libs gnupg git tree"

package() {
    cp -r "${source_dir}"/. ./
    make DESTDIR="${dest_dir}" PREFIX="${prefix}" WITH_ALLCOMP=yes \
        PLATFORMFILE=src/platform/ironclad.sh install

    post_package_strip
}
