#! /bin/sh

repology_id=password-store
repology_srcname=password-store
version=1.7.4
revision=1
tarball_url="https://git.zx2c4.com/password-store/snapshot/password-store-${version}.tar.xz"
tarball_blake2b=3fe332e52915e0c463938d963a17e1fb9d2be898c383641b7a586b28258f684a68e5e24212f8adf5beca8b14c5f3f343d693c516d570394dd791fd640c7a7950
deps="core-libs git tree"

package() {
    cp -r "${source_dir}"/. ./
    make DESTDIR="${dest_dir}" PREFIX="${prefix}" install
    post_package_strip
}
