#! /bin/sh

version=1.28.1
revision=8
tarball_url="https://github.com/mate-desktop/mate-control-center/releases/download/v${version}/mate-control-center-${version}.tar.xz"
tarball_blake2b="85983cb57e32fe4dd2315683b18b0227cd028d17d206fbbc5718ea0b9e9f1020bca63d5a76c616210fbe7398d5e559b271dd9e18c6aeab714264b61d185852b0"
imagedeps="libglib2.0-dev-bin libglib2.0-bin gtk-update-icon-cache"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core cairo dconf fontconfig freetype2 gdk-pixbuf glib2 gtk3 libmatekbd libx11 libxcursor libxi libxklavier libxml2 marco mate-desktop mate-menus pango shared-mime-info"
builddeps="libxscrnsaver"

configure() {
    meson_configure \
        -Daccountsservice=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    generate_glib_schemas_hook
    generate_mime_database_hook
}
