#! /bin/sh

skip_pkg_check=yes
version=0.0git
revision=18
git_url="https://codeberg.org/Ironclad/gcon.git"
commit=478d3286e4c75d6c3031512766fbb8cf3df83fbc
hostdeps="gcc pkg-config"
deps="core-libs"

early_prepare() {
    meson subprojects download
}

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
