#! /bin/sh

repology_id="llvm"
version=22.1.4
revision=1
tarball_url="https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/llvm-project-${version}.src.tar.xz"
tarball_blake2b="cd867371fecc8b4771c919a4d966cec25539dbaff5398e9c62ab5fe2f82b97bcc097f2319194cb796f6ee874b83c001ece5dc2d2e41c8807f88d91e67b71cf61"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs ncurses zlib zstd libffi libxml2"

configure() {
        cmake_source_dir="${source_dir}/llvm" \
    cmake_configure \
        -UBUILD_SHARED_LIBS \
        -UENABLE_STATIC \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_EH=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_DEFAULT_TARGET_TRIPLE=${OS_TRIPLET} \
        -DLLVM_HOST_TRIPLE=${OS_TRIPLET} \
        -Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    rm -rf "${dest_dir}${prefix}"/lib/*.a
    rm -rf "${dest_dir}${prefix}"/bin

    post_package_strip
}
