#! /bin/sh

version=9.0
revision=1
tarball_url="https://ftp.gnu.org/gnu/nano/nano-${version}.tar.xz"
tarball_blake2b="6df92e9f1b0ba8c2ec3dfdd8b4605a34c08f33c747746d8d3b4145894f0cc64b705c59f2b5aee120050eb32292adf78bf267c568a266c17e2f99e48026d38106"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc
    cp -v "${recipe_dir}"/nanorc "${dest_dir}"/etc/

    post_package_strip
}
