#! /bin/sh

version=9.2
revision=3
tarball_url="https://ftp.gnu.org/gnu/nano/nano-${version}.tar.xz"
tarball_blake2b="b8f5aedbb296654817eac82723a6ae6323b2710d225152ee6356fefe5e692958236a00ab4c7fd5abff71b84c3c023afc06854e4e216b80879c48ce94486c4b89"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file texinfo"
conf_files="/etc/nanorc"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure \
        --enable-color \
        --enable-multibuffer \
        --enable-nanorc
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc
    cp -v "${recipe_dir}"/nanorc "${dest_dir}"/etc/

    post_package_strip

    generate_info_hooks
}
