#! /bin/sh

version=9.1
revision=1
tarball_url="https://ftp.gnu.org/gnu/nano/nano-${version}.tar.xz"
tarball_blake2b="d762076463b0c683d13cd4c47cc05db573a1890c9ea0629c2aa37d36305197242eb724229afc59468aa47c515dbfb8378d9fa6fafa88d8b90a2af6d1ed467b14"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc
    cp -v "${recipe_dir}"/nanorc "${dest_dir}"/etc/

    post_package_strip
}
