#! /bin/sh

version=1.28.3
revision=3
tarball_url="https://github.com/mate-desktop/mate-terminal/releases/download/v${version}/mate-terminal-${version}.tar.xz"
tarball_blake2b="8d2b07f950a2cfcaaf84f98896286deac81c20f970e7e082f18f66ed325d9e778fa7888b649b458ceec3c4e53ab304d5988f9fd58697bbdc2b64a61d5ced470b"
imagedeps="libglib2.0-dev itstool"
hostdeps="gcc pkg-config"
deps="core-libs at-spi2-core glib2 dconf gdk-pixbuf libice libsm libx11 pango gtk3 vte mate-desktop ttf-liberation"

early_prepare() {
    # Fix revision of mate-submodules
    sed -i 's/^revision=.*/revision = 4074560e3642a53ace07b31baaf3f04c060dcd0b/g' subprojects/mate-submodules.wrap

    meson subprojects download
}

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
    generate_glib_schemas_hook
}
