#! /bin/sh

version=3.4.4
revision=1
tarball_url="https://www.samba.org/ftp/rsync/src/rsync-${version}.tar.gz"
tarball_blake2b="f4eec8d1077e1cc7eec8cd39dcac4643f7608231f5aa6390cb53104efa1602873a333d9e6cba5d1bb2aeff6c3bf9bccd80370a2105a9cc982b49aae9f39f3bde"
hostdeps="gcc pkg-config"
deps="core-libs lz4 openssl xxhash zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-included-zlib=no
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
