#! /bin/sh

version=3.5.0
revision=5
tarball_url="https://www.samba.org/ftp/rsync/src/rsync-${version}.tar.gz"
tarball_blake2b="1a0aaddd9555c14e2b026f4ac9aff0c0b7760a5809fc80c7872b382a0b9b4719dcc0d382c0e43439955efd855ffa2dff101c10a86529b88fd380205cc9506179"
hostdeps="gcc pkg-config"
deps="core-libs lz4 openssl popt xxhash zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-included-zlib=no \
        --with-included-popt=no \
        --with-rrsync \
        --enable-ipv6
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
