#! /bin/sh

version=3.5.1
revision=1
tarball_url="https://www.samba.org/ftp/rsync/src/rsync-${version}.tar.gz"
tarball_blake2b="513d03ddadf484424c90755f8d3a947993fdbac3fd7e7b2cdc675e25096f376d7086318be904efd32071d4ba27a06bdaf2875a2086e94f7bd5a7cc9fbdf065ef"
hostdeps="gcc pkg-config"
deps="core-libs lz4 openssl popt xxhash zlib zstd libidn2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-included-zlib=no \
        --with-included-popt=no \
        --with-rrsync \
        --enable-ipv6
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
