#! /bin/sh

repology_id="fast-float"
version=8.2.10
revision=1
git_url="https://github.com/fastfloat/fast_float.git"
commit=34164f547b7df3f5d794ff67e9f885c36819ebfc
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
