#! /bin/sh

version=1.4.6
revision=7
tarball_url="https://github.com/taisei-project/taisei/releases/download/v${version}/taisei-${version}.tar.xz"
tarball_blake2b="f183a220c2282ddca763643ce0c9715b0a88ed2bfc7832552656ce551aace001180beb3592bb3258448d89b12aa969bf7dc5b371df084f262c789dbf371a9820"
imagedeps="build-essential python3-docutils python3-pygments"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libpng sdl3 libwebp zlib zstd openssl opusfile libunibreak shared-mime-info"
builddeps="cglm"

configure() {
    meson_configure \
        -Dkoishi:default_library=static \
        -Db_lto=false \
        -Ddocs=enabled \
        -Dtests=disabled \
        -Dpackage_data=disabled \
        -Dgamemode=disabled \
        -Dinstall_relocatable=disabled \
        -Dinstall_macos_bundle=disabled \
        -Dshader_transpiler=disabled \
        -Dshader_transpiler_dxbc=disabled \
        -Dvalidate_glsl=disabled \
        -Dr_gles30=disabled \
        -Dr_sdlgpu=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    generate_mime_database_hook
}
