#! /bin/sh

version=1.4.6
revision=1
tarball_url="https://github.com/taisei-project/taisei/releases/download/v${version}/taisei-${version}.tar.xz"
tarball_blake2b="f183a220c2282ddca763643ce0c9715b0a88ed2bfc7832552656ce551aace001180beb3592bb3258448d89b12aa969bf7dc5b371df084f262c789dbf371a9820"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libpng sdl2-compat libwebp zlib cglm openssl libunibreak opusfile"

configure() {
    meson_configure \
        -Ddocs=disabled \
        -Db_lto=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
    post_package_strip
}
