#! /bin/sh

version=3.13
revision=3
tarball_url="https://feh.finalrewind.org/feh-${version}.tar.bz2"
tarball_blake2b="bbbcddc5a7d9d162866765a2a2ba5a8d8d57017fb2bbab5b88b47428fc15790326abb229cf62e831b9d2c1b9bbda11a52cde4e2612ad13b5e2dd0204138f8f1a"
hostdeps="gcc pkg-config"
deps="core-libs curl file hicolor-icon-theme imlib2 libexif libpng libx11 libxinerama"
builddeps="libxt"

build() {
    cp -rp "${source_dir}"/. ./

        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make PREFIX="${prefix}" -j${parallelism} \
        exif=1 \
        help=1 \
        magic=1 \
        stat64=1
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install

    post_package_strip
}
