#! /bin/sh

version=3.12.2
revision=7
tarball_url="https://feh.finalrewind.org/feh-${version}.tar.bz2"
tarball_blake2b="5ffb5bd57340523ec12f4f900f92704fc67570438638b48ce15b034bc36ce9b02fbccad600da785a5d4e3660dd7f46e0e48d09dfbaec0d347439fc041949ca10"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxt libpng imlib2 curl libxinerama"

build() {
    cp -rp "${source_dir}"/. ./

        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make PREFIX="${prefix}" -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install

    post_package_strip
}
