#! /bin/sh

version=2.25
revision=1
tarball_url="https://ftp.gnu.org/gnu/which/which-${version}.tar.gz"
tarball_blake2b="9c9b0e197e0f35845fee8a050aeccb3407ea27f82955be028ee3f148d74bf5d2c844814657ccf16adf03176f94b40bb4ae8817f27ffc7b2196b8d2e1e77f82c8"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
