#! /bin/sh

version=4.1
revision=5
tarball_url="https://deb.debian.org/debian/pool/main/c/cal/cal_${version}.orig.tar.xz"
tarball_blake2b="a0e5171898331a70a4e22a828b6c184718249c1f339c8d5f571a0025b5568e3d3a267c594e1f2616461b5300ff776bc29d67df92fba9e96702782e567839711d"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    make -C src -f makefile.unx -j${parallelism} \
        CC=${OS_TRIPLET}-gcc
}

package() {
    install -Dm755 src/cal "${dest_dir}${prefix}"/bin/cal
    install -Dm644 src/cal.1 "${dest_dir}${prefix}"/share/man/man1/cal.1

    post_package_strip
}
