#! /bin/sh

version=51.0
revision=1
tarball_url="https://download.gnome.org/sources/dconf/51/dconf-${version}.tar.xz"
tarball_blake2b="ac5000b6f2a1f9934d7645066ffb7eb8ab1ba81917f48f9315976eaae2de17d7529b7aa2696aaa6443bfde13e4cb9ccdd129ba108990b00a9846047d47f219b0"
imagedeps="libglib2.0-dev-bin libglib2.0-bin"
hostdeps="gcc pkg-config"
deps="core-libs dbus glib2"
builddeps="bash-completion"

configure() {
    meson_configure \
        -Dvapi=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    install_hook_add 'gio-querymodules /usr/lib/gio/modules/ >/dev/null'
}
