#! /bin/sh

version=2.32.72
revision=2
tarball_url="https://github.com/libsdl-org/sdl2-compat/releases/download/release-${version}/sdl2-compat-${version}.tar.gz"
tarball_blake2b="1068200843565c498f498e364bfd1ee72b479e190981da81b5c655cc4f59326098fa24f38441e7a5b54acd6dda318b379648cd456303c4595dcf7708103b40f6"
hostdeps="gcc pkg-config"
deps="core-libs sdl3 libx11 xorg-proto mesa"

configure() {
    cmake_configure \
        -DSDL2COMPAT_STATIC=OFF \
        -DSDL2COMPAT_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    ln -s sdl2-compat.pc "${dest_dir}${prefix}"/lib/pkgconfig/sdl2.pc

    post_package_strip
}
