#! /bin/sh

version=9.2.0850
revision=1
tarball_url="https://github.com/vim/vim/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="ce22ea783be2bc60b90a8d384863db9bbde04e13cfaf758dfd4ae70ec127e6d2ee4ff0e497dfda539cd0242198dfd0401dc0157e09bb7780e03700d6da47400a"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

configure() {
    cp -rp ${source_dir}/* .

        vim_cv_toupper_broken="no" \
        ac_cv_small_wchar_t="no" \
        ac_cv_func_sigsetjmp="no" \
        vim_cv_terminfo="yes" \
        vim_cv_tgetent="zero" \
        vim_cv_tty_group="" \
        vim_cv_tty_mode="0620" \
        vim_cv_getcwd_broken="no" \
        vim_cv_timer_create="no" \
        vim_cv_timer_create_with_lrt="no" \
        vim_cv_stat_ignores_slash="no" \
        vim_cv_memmove_handles_overlap="yes" \
        vim_cv_bcopy_handles_overlap="yes" \
        vim_cv_memcpy_handles_overlap="yes" \
    autotools_configure \
        --with-tlib=tinfo \
        --with-features=huge \
        --with-wayland=no \
        --enable-gpm \
        --enable-acl \
        --with-x=no \
        --disable-gui \
        --enable-multibyte \
        --enable-cscope \
        --enable-netbeans \
        --enable-perlinterp=dynamic \
        --enable-python3interp=dynamic \
        --enable-rubyinterp=dynamic \
        --enable-luainterp=dynamic \
        --enable-tclinterp=dynamic \
        --disable-canberra

}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR=${dest_dir} STRIP=/bin/true
    ln -sfv vim "${dest_dir}${prefix}"/bin/vi

    post_package_strip
}
