#! /bin/sh

version=7.20
revision=3
git_url="https://github.com/memtest86plus/memtest86plus.git"
commit=52c6c64d57b0cf3edc0aa963bbe9a4e0e6f51883
hostdeps="gcc"
imagedeps="nasm build-essential mtools dosfstools xorriso"

build() {
    if [ "${JINX_ARCH}" != "x86_64" ]; then
        return
    fi

    cp -rp ${source_dir}/. ./

    cd build64
    make -j${parallelism}
}

package() {
    if [ "${JINX_ARCH}" != "x86_64" ]; then
        return
    fi

    cd build64
    mkdir -p "${dest_dir}"/boot
    cp memtest.bin "${dest_dir}"/boot/
    cp memtest.efi "${dest_dir}"/boot/

        strip_command=strip \
    post_package_strip
}
