#! /bin/sh

version=12.3.3
revision=1
tarball_url="https://github.com/Limine-Bootloader/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="43c8dba8c1cf4efaa79a950cf8fc75b20b085221f2c934587eb11b91d06d0d3745ce624c180b20ab32ee09c7221aeb6cd2337e53778575bd8b96b9133211ef94"
imagedeps="build-essential mtools nasm llvm lld clang"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
