#! /bin/sh

version=12.9.3
revision=1
tarball_url="https://github.com/Limine-Bootloader/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="3f577655d2ad959ebb4213550c3db268efb666b6ad068fa34c1e6a811322729f535f8daba0252c6fc6f0ab84ec6b3f358559ef0f3509f676c4718898dd0014e8"
imagedeps="build-essential mtools nasm llvm lld clang"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
