#! /bin/sh

version=9.1.2
revision=1
git_url="https://github.com/simdutf/simdutf.git"
commit=be33cbe34b2d222566fd88f1084f86771ed8ae4a
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
