#! /bin/sh

version=9.1.1
revision=1
git_url="https://github.com/simdutf/simdutf.git"
commit=9dd35adc5f2c87a53c5a0e6e5b43af6fffe7187e
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
