#! /bin/sh

version=9.1.0
revision=4
git_url="https://github.com/simdutf/simdutf.git"
commit=2d4e249dcfd978b39dd567b156f20a43db97377b
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure \
        -DSIMDUTF_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
