#! /bin/sh

version=2.6.2
revision=4
tarball_url="https://ftp.gnu.org/gnu/libtool/libtool-${version}.tar.xz"
tarball_blake2b="c9d806815748b8b2ad9fc01a4bc38fedc3feda76eb8ef36707477a94b82ac413ceb8c9f3ea376b568d7a9ffc31ff292905579341741029babaea082637ec5144"
hostdeps="gcc pkg-config"
deps="core-libs texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    sed -Ei "/^LTCFLAGS=/! {s|/sysroot(/)?|/|g;s|/${prefix}|/|g}" "${dest_dir}${prefix}"/bin/libtool

    _lt="${dest_dir}${prefix}"/bin/libtool
    sed -Ei "/^LTCFLAGS=/! {s|/usr/local/${OS_TRIPLET}/bin/||g; s|/usr/local/bin/||g}" "${_lt}"
    sed -Ei "/^LTCFLAGS=/! s#${OS_TRIPLET}-(ar|as|ld|nm|objdump|ranlib|strip)([\" ])#\1\2#g" "${_lt}"
    sed -Ei "/^LTCFLAGS=/! {s|/usr/local/lib/gcc/|${prefix}/lib/gcc/|g; s|/usr/local/${OS_TRIPLET}/lib|${prefix}/lib|g}" "${_lt}"
    sed -Ei "/^sys_lib_(dl)?search_path_spec=/ s| [^ \"]*-linux-gnu[^ \"]*||g" "${_lt}"

    _lt_bad="$(grep -nE "/usr/local/(bin|${OS_TRIPLET})|/usr/local/lib/gcc|${OS_TRIPLET}-(ar|as|ld|nm|objdump|ranlib|strip)[\" ]" "${_lt}" | grep -v "^[0-9]*:LTCFLAGS=" || true)"
    _lt_bad="${_lt_bad}$(grep -nE "^sys_lib_(dl)?search_path_spec=.*-linux-gnu" "${_lt}" || true)"
    if [ -n "${_lt_bad}" ]; then
        die "*** libtool sanitisation left a build-host reference behind:
${_lt_bad}"
    fi

    post_package_strip

    generate_info_hooks
}
