#! /bin/sh

version=3.4.14
revision=1
tarball_url="https://github.com/libsdl-org/SDL/releases/download/release-${version}/SDL3-${version}.tar.gz"
tarball_blake2b="34467023af7f178c57bc13e2c9c3522e9c4edb15acf9dbef91f52c1deb5bc2223b63ccf5f87f402541be2dacc1f3fdc008713ac9c94b44be05b1ddcccbc87902"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxext libxcursor libxi libxfixes libxkbcommon libxrandr libxrender libxxf86vm mesa"

configure() {
    cmake_configure \
        -DSDL_ALTIVEC=OFF \
        -DSDL_X11_XSCRNSAVER=OFF \
        -DSDL_X11_XTEST=OFF \
        -DSDL_DISKAUDIO=OFF \
        -DSDL_OPENGL=ON \
        -DSDL_OPENGLES=ON \
        -DSDL_PTHREADS=ON \
        -DSDL_PTHREADS_SEM=OFF \
        -DSDL_OSS=OFF \
        -DSDL_ALSA=OFF \
        -DSDL_JACK=OFF \
        -DSDL_PULSEAUDIO=OFF \
        -DSDL_SNDIO=OFF \
        -DSDL_RPATH=OFF \
        -DSDL_X11=ON \
        -DSDL_WAYLAND=OFF \
        -DSDL_RPI=OFF \
        -DSDL_COCOA=OFF \
        -DSDL_DIRECTX=OFF \
        -DSDL_WASAPI=OFF \
        -DSDL_RENDER_D3D=OFF \
        -DSDL_VIVANTE=OFF \
        -DSDL_VULKAN=OFF \
        -DSDL_KMSDRM=OFF \
        -DSDL_HIDAPI=ON \
        -DSDL_SHARED=ON \
        -DSDL_STATIC=OFF \
        -DSDL_TEST_LIBRARY=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
