#! /bin/sh

version=2.47
revision=1
git_url="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
commit=a79055334104d382bd511760b67acf9a5a161361
hostdeps="gcc pkg-config"
deps="core-libs xorg-xkbcomp"

configure() {
    meson_configure \
        -Dxorg-rules-symlinks=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
