#! /bin/sh

version=2.48
revision=1
git_url="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
commit=cf8d1151bb4c9ef5b895828d0e6dd7860c0833e0
hostdeps="gcc pkg-config"
deps="core-libs xorg-xkbcomp"

configure() {
    meson_configure \
        -Dxorg-rules-symlinks=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
