#! /bin/sh

repology_id=xrandr
version=1.5.4
revision=1
tarball_url="https://www.x.org/pub/individual/app/xrandr-${version}.tar.xz"
tarball_blake2b="c83fe2aa6bb7277ae9bba04bf0584c8558bd55cbff4142ac84c39933a520c4fbdda90272983fdecff8e96526bdb44ad73414d7b1e0b5ce0a1a9990896d056f3f"
hostdeps="gcc pkg-config"
deps="core-libs libxmu libxaw libxt libx11 libxrandr"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
