#! /bin/sh

repology_id=gnumpc
version=1.4.1
revision=3
tarball_url="https://ftp.gnu.org/gnu/mpc/mpc-${version}.tar.xz"
tarball_blake2b="793b4cf37e7e805dcbf24bc39903d5d778702e80cf5eac60b840834f09868656856a008cff6b45e7a5a312c3ed21a593d84f45765e9ac456ab3dd38a083acff1"
hostdeps="gcc pkg-config"
deps="core-libs gmp mpfr texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
}
