#! /bin/sh

repology_id=tiff
version=4.7.2
revision=2
tarball_url="http://download.osgeo.org/libtiff/tiff-${version}.tar.gz"
tarball_blake2b="01d6c593fa0403472bfb7db4beb046d8da6014ce8670b2d81f38744f87df3d519d75a515006c98c878a02eee8f80d7b6bc006470ebc9433f5681562a3adba45a"
hostdeps="gcc pkg-config"
deps="core-libs freeglut libjpeg-turbo zlib zstd xz"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
