#! /bin/sh

version=20260221
revision=2
tarball_url="https://github.com/hvisage/metalog/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="b5394cf88768411aaa303b2c8ce49d6340d71d4b3f7ee934b6caf792d5a279361c545e1dd98df30d82c6e3efd9ff313c9208bdcd5184d54d44c79c8a4dbbab19"
source_deps="autoconf-archive"
source_hostdeps="autoconf automake pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs pcre2"

prepare() {
    autoreconf -fvi -I${sysroot}/usr/share/aclocal
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
