#! /bin/sh

version=20260221
revision=3
git_url="https://github.com/hvisage/metalog.git"
commit=38ec41762ed8ec457780700d07f318966634f716
source_deps="autoconf-archive"
source_hostdeps="autoconf automake pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 zlib"
conf_files="/etc/metalog.conf"

prepare() {
    autoreconf -fvi -I${sysroot}/usr/share/aclocal
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
