#! /bin/sh

version=14.2.0
revision=1
tarball_url="https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz"
tarball_blake2b="bc0df1fad40bbd2f7348d16e1d17927285a1e64eae02bf27f5921691cb77cbe8646a5f51e14c97953416b9e08f326c824646d2f114b59e37579657727cf706f4"
hostdeps="gcc pkg-config"
deps="core-libs graphite2 glib2 zlib freetype2 cairo icu"

configure() {
    meson_configure \
        -Dgraphite2=enabled \
        -Dglib=enabled \
        -Dgobject=disabled \
        -Dicu=enabled \
        -Dfreetype=enabled \
        -Dcairo=enabled \
        -Dintrospection=disabled \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
