#! /bin/sh

version=14.6.0
revision=1
tarball_url="https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz"
tarball_blake2b="d65745c89cdbc10cc6a521b467ef90eabd93a63285de15345b8d41f51cd9229882234c10fcfd2045ccab3aad6144c9f1e5dd47e7a2b1086bedea3cfb8b7e8c5a"
imagedeps="libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs graphite2 glib2 zlib freetype2 libpng cairo icu"

configure() {
    meson_configure \
        -Dchafa=disabled \
        -Dgpu_demo=disabled \
        -Ddocs=disabled \
        -Dgraphite2=enabled \
        -Dintrospection=disabled \
        -Dtests=disabled
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
