#! /bin/sh

version=2.0.8
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXfont2-${version}.tar.gz"
tarball_blake2b="8bafeadd5405dfea82fb379e20cd2a018e152dc415ee9a1a94f60a2fc1d30473f55e666bf2d5df2c0d74a9240653c3c010fd4f035ee3ae5819cc55ca6a9cfd60"
hostdeps="gcc pkg-config"
deps="core-libs xorg-util-macros xorg-proto libx11 xtrans freetype2 fontconfig bzip2 libfontenc zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-bzip2 \
        --disable-devel-docs \
        --disable-selective-werror
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
