#! /bin/sh

version=0.22.2
revision=4
tarball_url="https://www.libraw.org/data/LibRaw-${version}.tar.gz"
tarball_blake2b="31982303e92dbd45dbfd50c0902ef67716aa0f6443e1e8cc1b31c02676cff1a2d0f3e2d6d74215ddbf161d31dc5272f85a7beeb9235de8b4cfb6b6a879281b88"
hostdeps="gcc pkg-config"
deps="core-libs lcms2 libjpeg-turbo zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
