#! /bin/sh

version=11.1.0
revision=2
tarball_url="https://download.qemu.org/qemu-${version}.tar.xz"
tarball_blake2b="bdcbd99067718c13186ed5f63bf6a7434e5f3acd455410ec029a0bbed45eb0fdcc9f9a3474af33e4e159137f2cf66b704998eda2c386297d73957fe26fba9722"
imagedeps="build-essential python3-venv python3-sphinx python3-sphinx-rtd-theme"
hostdeps="gcc pkg-config"
deps="core-libs libnvmm sdl2-compat gtk3 glib2 ncurses pixman libjpeg-turbo libpng zlib bzip2 zstd vte cairo gdk-pixbuf libx11 libxkbcommon gnutls libtasn1 curl"

early_prepare() {
    meson subprojects download
}

configure() {
    cp -rp "${source_dir}"/* ./

    NVMM_FLAG=""
    case "${JINX_ARCH}" in
        x86_64)
            NVMM_FLAG="--enable-nvmm"
            ;;
    esac

        CFLAGS="${TARGET_CFLAGS}" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    ./configure \
        -Db_colorout=always \
        -Ddtc:werror=false \
        --enable-docs \
        --cross-prefix=${OS_TRIPLET}- \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-coroutine=sigaltstack \
        --enable-slirp \
        --disable-tpm \
        $NVMM_FLAG
}

build() {
    cd build

    meson compile --verbose -j${parallelism}
}

package() {
    cd build

    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -f "${dest_dir}${prefix}"/share/man/man8/qemu-pr-helper.8

    post_package_strip
}
