#! /bin/sh

version=11.1.0
revision=1
tarball_url="https://download.qemu.org/qemu-${version}.tar.xz"
tarball_blake2b="bdcbd99067718c13186ed5f63bf6a7434e5f3acd455410ec029a0bbed45eb0fdcc9f9a3474af33e4e159137f2cf66b704998eda2c386297d73957fe26fba9722"
imagedeps="build-essential python3-venv python3-qemu-qmp python3-wheel python3-pip libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs libnvmm sdl2-compat gtk3 glib2 ncurses pixman libjpeg-turbo bzip2 zstd vte gnutls libtasn1"

early_prepare() {
    meson subprojects download
}

configure() {
    cp -rp "${source_dir}"/* ./

    NVMM_FLAG=""
    case "${JINX_ARCH}" in
        x86_64)
            NVMM_FLAG="--enable-nvmm"
            ;;
    esac

        CFLAGS="${TARGET_CFLAGS} -Wno-error" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    ./configure \
        -Db_colorout=always \
        --cross-prefix=${OS_TRIPLET}- \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-coroutine=sigaltstack \
        --disable-tpm \
        $NVMM_FLAG
}

build() {
    cd build

    meson compile -j${parallelism}
}

package() {
    cd build

    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
