#! /bin/sh

version=10.2.2
revision=2
tarball_url="https://download.qemu.org/qemu-${version}.tar.xz"
tarball_blake2b="810efae886e5ba56900882455cc8714923378e34995dceaec8177ba5cc7f922547b7cbf68f7ac3804e498b3b4b3895165646c81ff9ad50b09c8286e8b2293a72"
imagedeps="build-essential python3-venv"
hostdeps="gcc pkg-config"
deps="core-libs libnvmm sdl2-compat gtk3 glib2 ncurses pixman libjpeg-turbo bzip2 zstd vte gnutls libtasn1"

early_prepare() {
    meson subprojects download
}

configure() {
    cp -rp "${source_dir}"/* ./

    NVMM_FLAG=""
    case "${JINX_ARCH}" in
        x86_64)
            NVMM_FLAG="--enable-nvmm"
            ;;
    esac

        CFLAGS="${TARGET_CFLAGS} -Wno-error" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    ./configure \
        -Db_colorout=always \
        --cross-prefix=${OS_TRIPLET}- \
        --host=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-coroutine=sigaltstack \
        --disable-tpm \
        $NVMM_FLAG
}

build() {
    cd build

    meson compile -j${parallelism}
}

package() {
    cd build

    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
