#! /bin/sh

version=1.5.4
revision=1
tarball_url="https://github.com/iczelia/bzip3/releases/download/${version}/bzip3-${version}.tar.xz"
tarball_blake2b="20ed080a0af52693762de9991fe35396a5039f28371a38056f90edc181aae9ce2f3e9daa5d80914b32ffb71850b4931df126770d947dc6f336ecb92ddba659b2"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
