#! /bin/sh

name=bootstrap-gcc
from_source=gcc-host
revision=1
imagedeps="build-essential"
hostdeps="pkg-config"
hostrundeps="binutils"

configure() {
    cp -rp "${source_dir}"/. ./

    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ../configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot_dir}" \
        --with-glibc-version=2.42 \
        --with-newlib \
        --without-headers \
        --enable-checking=release \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-gnu-indirect-function \
        --enable-gnu-unique-object \
        --enable-link-serialization=1 \
        --enable-linker-build-id \
        --enable-languages=c,c++,lto \
        --enable-lto \
        --disable-multilib \
        --disable-libstdcxx-pch \
        --disable-werror \
        --disable-libatomic \
        --disable-libgomp \
        --disable-libquadmath \
        --disable-libssp \
        --disable-libstdcxx \
        --disable-libvtv \
        --disable-multilib \
        --disable-nls \
        --disable-shared \
        --disable-threads
}

build() {
    cd build

    make -j${parallelism} all-gcc
    make -j${parallelism} all-target-libgcc
}

package() {
    cd build

    DESTDIR="${dest_dir}" make install-gcc
    DESTDIR="${dest_dir}" make install-target-libgcc

        strip_command=strip \
    post_package_strip
}
