#! /bin/sh

name=gcc
from_source=gcc-host
revision=1
imagedeps="experimental:build-essential"
hostdeps="pkg-config"
hostrundeps="binutils"
deps="mlibc-headers"

. "${base_dir}"/build-support/gcc-ada-helpers

configure() {
    ada_symlink_gnat

    cp -rp "${source_dir}"/. ./
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ../configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot_dir}" \
        --disable-nls \
        --with-linker-hash-style=gnu \
        --enable-linker-build-id \
        --disable-libada \
        --enable-languages=c,c++,lto,ada \
        --enable-default-pie \
        --enable-default-ssp \
        --disable-multilib \
        --enable-initfini-array \
        --enable-shared \
        --enable-host-shared
}

build() {
    ada_symlink_gnat

    cd build
    make -j${parallelism} all-gcc
    make -j${parallelism} -C gcc cross-gnattools ada.all.cross
}

package() {
    ada_symlink_gnat

    cd build
    DESTDIR="${dest_dir}" make install-gcc

    ln -s x86_64-ironclad-mlibc-gnatbind "${dest_dir}${prefix}"/bin/x86_64-ironclad-mlibc-gnatbind-15

        strip_command=strip \
    post_package_strip
}
