#! /bin/sh

name=glib
from_source=glib2
imagedeps="meson ninja-build python3-setuptools build-essential libpcre2-dev pkg-config libffi-dev zlib1g-dev"
# hostdeps="gcc pkg-config"
# deps="core-libs pcre2 libffi zlib"

configure() {
    meson setup "${source_dir}" --prefix="${prefix}"
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
