#! /bin/sh

name=intltool
from_source=intltool
revision=1
hostdeps="autoconf automake libtool pkg-config"
imagedeps="build-essential libxml-parser-perl"

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    ${source_dir}/configure \
        --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
