#! /bin/sh

name=mate-common
from_source=mate-common
# imagedeps="meson ninja-build libglib2.0-dev"
hostdeps="gcc pkg-config autoconf automake"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    "${source_dir}"/configure \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-nls \
        --disable-static
    # autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
