#! /bin/sh

version=2.2.5
revision=6
tarball_url="ftp://ftp.figlet.org/pub/figlet/program/unix/figlet-${version}.tar.gz"
tarball_blake2b="9d7a8b518ee91bd937d7fb81d782c894bc2a1738b696b03d948c1319e68aadde9ff1ea291ee77f9e79bdd950c68fe98c9e4539e7e76ef5f9e758c16b968966e1"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="${TARGET_CFLAGS}" \
        LD=${OS_TRIPLET}-gcc \
        LDFLAGS="${TARGET_CFLAGS} ${TARGET_LDFLAGS}" \
        prefix="${prefix}" \
        MANDIR="${prefix}"/share/man \
        -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install prefix="${prefix}" MANDIR="${prefix}"/share/man

    post_package_strip
}
