#! /bin/sh

version=1.13.2
revision=2
git_url="https://github.com/xkbcommon/libxkbcommon.git"
commit=1e11d3afe458ad2efe1d081b3185e42d32c80f56
hostdeps="gcc pkg-config"
deps="core-libs libxcb libxml2 xkeyboard-config"

configure() {
    meson_configure \
        -Dxkb-config-root="$prefix"/share/X11/xkb \
        -Denable-x11=true \
        -Denable-wayland=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
