#! /bin/sh

version=1.5.2
revision=3
git_url="https://github.com/klange/nyancat.git"
commit=19f7dcac57bee416f714035947b41df3a76c73a4
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make \
        CC=${OS_TRIPLET}-gcc \
        CFLAGS="$TARGET_CFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
        -j${parallelism}
}

package() {
    install -d "${dest_dir}${prefix}"/bin
    install src/nyancat "${dest_dir}${prefix}"/bin/
    install -d "${dest_dir}${prefix}"/share/man/man1
    install -m 644 nyancat.1 "${dest_dir}${prefix}"/share/man/man1/

    post_package_strip
}
