#! /bin/sh

version=18.6
revision=5
tarball_url="https://ftp.postgresql.org/pub/source/v${version}/postgresql-${version}.tar.bz2"
tarball_blake2b="657fd161eb581608cf73f6f649b6a35dbf034ff64c578c17f94d49c72ac9cd8ea7280425dd24ba4d7550c044bfebe78f0ebc534a1df4cfe2b634a6e4f765aa51"
imagedeps="binutils"
hostdeps="gcc pkg-config"
deps="core-libs icu readline zlib openssl zstd libxml2 libxslt lz4 e2fsprogs"

configure() {
    meson_configure \
        -Duuid=e2fs \
        -Drpath=false \
        -Dsystem_tzdata="${prefix}"/share/zoneinfo \
        -Dtap_tests=disabled \
        -Dbonjour=disabled \
        -Dbsd_auth=disabled \
        -Ddocs_pdf=disabled \
        -Dgssapi=disabled \
        -Dlibcurl=disabled \
        -Dldap=disabled \
        -Dlibnuma=disabled \
        -Dliburing=disabled \
        -Dpam=disabled \
        -Dplperl=disabled \
        -Dplpython=disabled \
        -Dpltcl=disabled \
        -Dselinux=disabled \
        -Dsystemd=disabled
}

build() {
    meson compile --verbose -j${parallelism}

    meson compile --verbose -j${parallelism} docs
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    DESTDIR="${dest_dir}" meson compile --verbose install-docs

    rm -f "${dest_dir}${prefix}"/lib/libpq.a \
          "${dest_dir}${prefix}"/lib/libecpg.a \
          "${dest_dir}${prefix}"/lib/libecpg_compat.a \
          "${dest_dir}${prefix}"/lib/libpgtypes.a

    post_package_strip
}
