#! /bin/sh

version=19beta2
revision=4
tarball_url="https://ftp.postgresql.org/pub/source/v${version}/postgresql-${version}.tar.bz2"
tarball_blake2b="28753aef951e3bd1ecf36808d7f0b669ef1cccbc5a35c9ce78289945639dfc2f9d781c661919d70782b620757ccfcd66b37c33d95423f882fc39c1053ab2fe3b"
imagedeps="binutils"
hostdeps="gcc pkg-config"
deps="core-libs icu readline zlib openssl zstd libxml2 lz4 llvm-libs curl"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
