#! /bin/sh

version=3.8.13
revision=2
tarball_url="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-${version}.tar.xz"
tarball_blake2b="80677a45a7c6f892287020e3e6b0add2432f2c64a4c9a649ce889921ac65b44931504ad0682ccc12e4b6d8f94c1a72e35c50673c9d04bd4e327063b812339380"
hostdeps="gcc pkg-config"
deps="core-libs libffi libunistring libtasn1 nettle p11-kit zlib brotli zstd libidn2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-default-trust-store-pkcs11="pkcs11:" \
        --enable-openssl-compatibility
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
