#! /bin/sh

version=4.0.3
revision=1
tarball_url="https://github.com/openssl/openssl/releases/download/openssl-${version}/openssl-${version}.tar.gz"
tarball_blake2b="9fc00a2aa35f86078c5bfb21418fc2df6c277a5cf70f9b9f7b45ef612e9879cb69a90580df6f743a152ddea09440e5bb2d944ac0c2860b5cab44d0dc6b991817"
hostdeps="gcc pkg-config"
deps="core-libs zlib brotli zstd"
conf_files="/etc/ssl/openssl.cnf"

configure() {
        CC=${OS_TRIPLET}-gcc \
        CXX=${OS_TRIPLET}-g++ \
        AR=${OS_TRIPLET}-ar \
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ${source_dir}/Configure \
        --prefix=${prefix} \
        --openssldir=/etc/ssl \
        --libdir=lib \
        ${OS_TRIPLET} \
        shared \
        enable-zlib \
        enable-brotli \
        enable-zstd \
        enable-ec_nistp_64_gcc_128 \
        no-afalgeng
}

build() {
    make -j${parallelism}
}

package() {
    # Disable installing static libraries.
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile

    make DESTDIR="${dest_dir}" MANSUFFIX=ssl install

    grep -rl '\.\./\.\./\.\./base_dir/sources/openssl/' "${dest_dir}" \
        | xargs -r sed -i 's|\.\./\.\./\.\./base_dir/sources/openssl/||g'

    post_package_strip
}
