#! /bin/sh

version=4.0.1
revision=1
tarball_url="https://github.com/openssl/openssl/releases/download/openssl-${version}/openssl-${version}.tar.gz"
tarball_blake2b="8c5e1d97165d8e74f6ab41adf75c8f1a60a38b511163d0cdd054b27280538681d308385ce9a6fe2230aed7e412436419f864876e57538738e13eed77d520d5cd"
hostdeps="gcc pkg-config"
deps="core-libs zlib"

configure() {
        CC=${OS_TRIPLET}-gcc \
        CXX=${OS_TRIPLET}-g++ \
        AR=${OS_TRIPLET}-ar \
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ${source_dir}/Configure \
        --prefix=${prefix} \
        --openssldir=/etc/ssl \
        --libdir=lib \
        ${OS_TRIPLET} \
        shared \
        zlib-dynamic \
        no-afalgeng
}

build() {
    make -j${parallelism}
}

package() {
    # Disable installing static libraries.
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile

    DESTDIR="${dest_dir}" make DESTDIR="${dest_dir}" MANSUFFIX=ssl install

    post_package_strip
}
