#! /bin/sh

version=2.47
revision=2
tarball_url="https://ftp.gnu.org/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="329cae8792c500c71d8cce03aab127e8d77f1d409f74872082e64df5163e5c730fe585f8f9c21905cb6227cae18e6675ae4caed653223a26b5d9d4fdb90910ea"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --target=${OS_TRIPLET} \
        --with-build-sysroot=${sysroot} \
        --enable-separate-code \
        --enable-cet \
        --enable-colored-disassembly \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-ld=default \
        --enable-new-dtags \
        --enable-plugins \
        --enable-relro \
        --enable-threads \
        --disable-werror \
        --with-pic \
        --with-system-zlib
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove unnecessary directory
    rm -rf "${dest_dir}${prefix}"/${OS_TRIPLET}

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
