#! /bin/sh

version=2.46.1
revision=1
tarball_url="https://ftp.gnu.org/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="a5a0578281d6315a43437ccf7636b3b91185c2706f1582b22af6973f55a86f5b4bc7eb03aa9ceaec547070152c08c982bc40ee9ce07679f2e3bb49e050bae76c"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs zlib zstd"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --target=${OS_TRIPLET} \
        --with-build-sysroot=${sysroot} \
        --enable-separate-code \
        --enable-cet \
        --enable-colored-disassembly \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-ld=default \
        --enable-new-dtags \
        --enable-plugins \
        --enable-relro \
        --enable-threads \
        --disable-werror \
        --with-pic \
        --with-system-zlib
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove unnecessary directory
    rm -rf "${dest_dir}${prefix}"/${OS_TRIPLET}

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
