#! /bin/sh

version=16.2.0
tarball_url="https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
tarball_blake2b="ab3ffe16e042da767f3f1eac170da518d6d7de3b0f92e068f79e3bf25fdc0bdf56eea0cd586bd4b9b6e9baebadd110c2ebd77b75c99c45853814f4bea5a98ef0"
clean_workdirs=no
revision=2
imagedeps="build-essential"
hostdeps="pkg-config"
hostrundeps="binutils"
deps="glibc"

. "${base_dir}"/build-support/gcc-ada-helpers

early_prepare() {
    ./contrib/download_prerequisites

    # Gettext causes issues and we don't want it anyways.
    rm -rf gettext*
}

prepare() {
    autotools_recursive_regen
}

configure() {
    ada_symlink_gnat

    cp -rp "${source_dir}"/. ./
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ../configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot}" \
        --with-glibc-version=2.42 \
        --enable-__cxa_atexit \
        --enable-cet=auto \
        --enable-checking=release \
        --enable-clocale=gnu \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-gnu-indirect-function \
        --enable-gnu-unique-object \
        --enable-libstdcxx-backtrace \
        --enable-link-serialization=1 \
        --enable-linker-build-id \
        --enable-languages=c,c++,lto,ada \
        --enable-lto \
        --disable-multilib \
        --enable-plugin \
        --enable-shared \
        --enable-host-shared \
        --enable-threads=posix \
        --disable-libssp \
        --disable-libstdcxx-pch \
        --disable-werror
}

build() {
    ada_symlink_gnat

    cd build
    make -j${parallelism} all-gcc
    make -j${parallelism} -C gcc cross-gnattools ada.all.cross

    make -j${parallelism} all-target-libgcc
    make -j${parallelism} all-target-libstdc++-v3
    make -j${parallelism} all-target-libatomic
}

package() {
    ada_symlink_gnat

    cd build
    DESTDIR="${dest_dir}" make install-gcc

    DESTDIR="${dest_dir}" make install-target-libgcc
    DESTDIR="${dest_dir}" make install-target-libstdc++-v3
    DESTDIR="${dest_dir}" make install-target-libatomic

    ln -s ${OS_TRIPLET}-gnatbind "${dest_dir}${prefix}"/bin/${OS_TRIPLET}-gnatbind-16

        strip_command=strip \
    post_package_strip
}
