#! /bin/sh

version=3.8.9
revision=2
tarball_url="https://github.com/libarchive/libarchive/releases/download/v${version}/libarchive-${version}.tar.gz"
tarball_blake2b="26de23f0faf867897359c1bf02edfdbb3988633b93be5c0da7f85f88dc5447b32dadb2485e4a29ef35d7b2fadc7d3966871c71b0054c1dbcea4d23f663db604b"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libexpat libxml2 xz zlib zstd"

configure() {
    cmake_configure \
        -DENABLE_TEST=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    # Remove static libraries
    rm -v "${dest_dir}${prefix}/lib/libarchive.a"

    post_package_strip
}
