#! /bin/sh

version=3.8.8
revision=1
tarball_url="https://github.com/libarchive/libarchive/releases/download/v${version}/libarchive-${version}.tar.gz"
tarball_blake2b="0b1de81d6fd303e33862a527acb2afeb627dcc6576a3fa92afb9aedf2b0c8586148e682b0b8b06e45b69d2b6f19255ff54b9a89ecd9d8cbd391fd7df9b932deb"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 libexpat libxml2 xz zlib zstd"

configure() {
    cmake_configure \
        -DENABLE_TEST=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    # Remove static libraries
    rm -v "${dest_dir}${prefix}/lib/libarchive.a"

    post_package_strip
}
