#! /bin/sh

skip_pkg_check=yes
version=0.0
revision=13

# Very base packages.
deps="base-files ironclad tzdata xbps"

# Standard POSIX tools that are expected on POSIX system scripting.
deps+=" coreutils file findutils gawk grep util-ironclad sed tar shadow"

# Standard linux toolset that we provide for some semblance of normalcy.
deps+=" pciutils xz bzip2 bzip3 gzip gettext zstd"

# Distro requirements for booting and installing packages.
deps+=" epoch gcon xbps"

# Internet utilities
deps+=" ca-certificates"
