#! /bin/sh

version=5.4.0
revision=1
tarball_url="https://ftp.gnu.org/gnu/gawk/gawk-${version}.tar.xz"
tarball_blake2b="ce326dc386e62d288c4fe1268ba493f9c3a1e8af7dec90f95b2942588370f5a3538837d71dc4208534ace2aa84fce46ab6d5d681451b560fdf884aaf1b89fb11"
hostdeps="gcc pkg-config"
deps="core-libs mpfr gmp readline"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
