#! /bin/sh

version=5.5.1
revision=2
tarball_url="https://github.com/lua/lua/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="1b7f4c8d2efaef34a008a52ad513185ddb20bdc4ca053fb82149de2e75c7b442b1c44fdc39d246db0092a015dda6ae1cb847da28758a6aa09ba3253465c8fb91"
imagedeps="nasm"
hostdeps="gcc pkg-config"
deps="core-libs readline"

build() {
    cp -rp "${source_dir}"/. ./
    sed -i 's|^#define LUA_ROOT "/usr/local/"$|#define LUA_ROOT "/usr/"|' luaconf.h

    make MYLIBS="-lreadline -lncursesw -ltinfow" CFLAGS="$TARGET_CFLAGS -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_USE_READLINE" MYLDFLAGS="$TARGET_LDFLAGS" CC=${OS_TRIPLET}-gcc AR="${OS_TRIPLET}-ar rcu" RANLIB=${OS_TRIPLET}-ranlib -j${parallelism}
}

package() {
    mkdir -p "${dest_dir}${prefix}"/bin
    cp lua "${dest_dir}${prefix}"/bin/

    post_package_strip
}
