#! /bin/sh

version=2.5.1
revision=4
git_url="https://gitlab.freedesktop.org/xdg/shared-mime-info.git"
commit=fd8ab89c20093f1bfba8fa9e302ba584fffd0fd7
hostdeps="gcc pkg-config"
deps="core-libs glib2 libxml2"

configure() {
    meson_configure \
        -Dbuild-tests=false \
        -Dupdate-mimedb=false
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    generate_mime_database_hook
}
