#! /bin/sh

version=2.5.1
revision=2
tarball_url="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${version}/shared-mime-info-${version}.tar.gz"
tarball_blake2b="f807f0f2e449999823f2d667075c6364f7b674a763d9ecae85e08799c6b5996302a6cecf04387ecffdfb571f543962f2766609ff0db594c4658dc7feb8a40fb6"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libxml2"

configure() {
    meson_configure \
        -Dupdate-mimedb=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
