#! /bin/sh

version=2.63.1
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=acf610416c2d5bb1438f723699aca47647fbeba5
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
