#! /bin/sh

version=2.67.0
revision=1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=56da8f811068289f6352db8881418aa6e0f994e8
hostdeps="gcc pkg-config"
deps="core-libs sqlite zlib"

configure() {
    cmake_configure \
        -DBUILD_FLASHFETCH='OFF' \
        -DENABLE_SQLITE3='ON' \
        -DMODULE_DISABLE_LOCALIP='ON' \
        -DMODULE_DISABLE_PUBLICIP='ON'
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
