#! /bin/sh

version=0.9.6
revision=3
git_url="https://github.com/recp/cglm.git"
commit=144d1e7c29b3b0c6dede7917a0476cc95248559c
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile --verbose -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
