#! /bin/sh

version=2.53.0
revision=9
tarball_url="https://www.kernel.org/pub/software/scm/git/git-${version}.tar.xz"
tarball_blake2b="a23ccb2f793d37347e892f6094ad589510c93011a53fb2c14cdcbfbe6d87413edb4585a98253e4ca5124217f66ad783f4fa584f38dc25ffa34772da01dc45f02"
imagedeps="build-essential asciidoc"
hostdeps="gcc pkg-config"
deps="core-libs python zlib curl openssl openssh libexpat pcre2"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp ${source_dir}/. .

        configure_script_path=./configure \
        ac_cv_iconv_omits_bom=yes \
        ac_cv_fread_reads_directories=no \
        ac_cv_snprintf_returns_bogus=no \
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS" \
        --with-gitconfig=/etc/gitconfig \
        --with-libpcre2 \
        --with-python=/usr/bin/python3
}

build() {
    make -j${parallelism} V=1 CURL_CONFIG="${sysroot}${prefix}"/bin/curl-config
    make -j${parallelism} V=1 man

    make -j${parallelism} V=1 -C contrib/subtree all man
}

package() {
    DESTDIR="${dest_dir}" make install install-man \
        CURL_CONFIG="${sysroot}${prefix}"/bin/curl-config

    DESTDIR="${dest_dir}" make -C contrib/subtree install install-man

    post_package_strip

    install_hook_add 'grep -qxF /usr/bin/git-shell /etc/shells 2>/dev/null || echo /usr/bin/git-shell >>/etc/shells'

    remove_hook_add 'if [ -f /etc/shells ]; then
    sed -i '\''\|^/usr/bin/git-shell$|d'\'' /etc/shells
fi'
}
