#! /bin/sh

version=710
revision=1
tarball_url="https://www.greenwoodsoftware.com/less/less-${version}.tar.gz"
tarball_blake2b="defbc6a019b5d6a598bfbd965cd34ec87777e7ee1dd47025ea84d2a7d474285f2add24b2e5d5aabf7cf9e00f5b2be44c42b1406cb6066d2ac0c5a63b5626917c"
hostdeps="gcc pkg-config"
deps="core-libs ncurses pcre2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-regex=pcre2
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    post_package_strip
}
