#! /bin/sh

version=8.0
fixed_version=$(echo ${version} | sed 's/\./_/g')
revision=1
tarball_url="https://github.com/adah1972/libunibreak/releases/download/libunibreak_${fixed_version}/libunibreak-${version}.tar.gz"
tarball_blake2b="db304d19a2255e9ae0738d42dfd7c6f1ead88cd333e8afb71172309eb0e36f85879145c973eba6da9d082a1badae5a4ff9d6a95e5047e695e3dc173a380d9a2f"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
