#! /bin/sh

version=7.3
revision=4
tarball_url="https://ftp.gnu.org/gnu/texinfo/texinfo-${version}.tar.xz"
tarball_blake2b="e9c17aec5ebf9d22eb22b40a06a24de675fca6d511f448170983d474b0906e23c25a00b75907b260abf66e660aefa6d6af928a1785bcf9b2099a0e791aac7025"
source_imagedeps="build-essential"
imagedeps="build-essential help2man"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen

    mkdir build && cd build
    ../configure \
        --disable-perl-xs \
        CFLAGS="$HOST_CFLAGS" \
        LDFLAGS="$HOST_LDFLAGS"

    make -j${parallelism}
    make -C info makedoc

    cd ..
    mv build/info/makedoc info/
    rm -rf build
}

configure() {
        texinfo_cv_sys_iconv_converts_euc_cn=y \
    autotools_configure \
        --disable-perl-xs

    mkdir -p tools/info
    cp -v "${source_dir}"/info/makedoc tools/info/
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
    generate_info_catchall_hook
}
