#! /bin/sh

repology_id=libisoburn
version=1.5.8
revision=1
tarball_url="https://ftp.gnu.org/gnu/xorriso/xorriso-${version}.tar.gz"
tarball_blake2b="2f7fedca895ccca1278c68a03df25e31119c633a9f6e5b77b0d33e34380b306acc047ba7c7ff413af1eecb7f6b54a1059e69bf87e4bae4116b81db3b206457a9"
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs pcre2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
