#! /bin/sh

repology_id=libisoburn
version=1.5.8.pl02
revision=3
tarball_url="https://ftp.gnu.org/gnu/xorriso/xorriso-${version}.tar.gz"
tarball_blake2b="3e15af0ec6082c590c6f13454783c277ff5439e7457e1ef90143f5406c71e6afbadc74b6765b5d5d833541171fec6b164376068b8ca44d0de298ec9ef420b4e2"
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs bzip2 readline zlib texinfo"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip

    generate_info_hooks
}
