#! /bin/sh

from_source=autoconf-archive
revision=2

package() {
    mkdir -p "${dest_dir}${prefix}"/share/aclocal
    cp -r "${source_dir}"/m4/. "${dest_dir}${prefix}"/share/aclocal/

    post_package_strip
}
