name: Gloire CI

on: [push]

jobs:
  ci_build:
    name: On-Push CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch: [riscv64-limine, x86_64-limine]

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make findutils curl git zstd rsync xorriso

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build base
        run: |
          set -ex

          git clone https://git.savannah.nongnu.org/git/ironclad.git ironclad

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              JINX_CONFIG_FILE=jinx-config-riscv64 ./jinx build base ;; \
            x86_64-limine) \
              ./jinx build base ;; \
          esac
