#! /bin/sh

version=0.60.7
revision=2
tarball_url="https://github.com/void-linux/xbps/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="63229a75b5b582efe5b7a181baa166c0b3b1fabf93f65024e9cea8b613cff023268680fece28c5105eca426a3ff3d57d485d9ab1c7193b992ef6e03fe14e9b2c"
hostdeps="gcc pkg-config"
deps="core-libs libarchive openssl zlib"

configure() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="$TARGET_CFLAGS -Wno-error" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ./configure \
        --verbose \
        --host=${OS_TRIPLET} \
        --prefix="${prefix}" \
        --sysconfdir=/etc
}

build() {
    make -j${parallelism} \
        AR="${OS_TRIPLET}-ar" \
        RANLIB="${OS_TRIPLET}-ranlib"
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove static libraries
    rm "${dest_dir}${prefix}"/lib/*.a

    # Change architecture for the main repository as needed.
    sed -i "s/ARCH_HERE/${JINX_ARCH}/g" "${dest_dir}${prefix}"/share/xbps.d/00-repository-main.conf

    post_package_strip
}
